/**
 * Bundled fallback for the staff-picks registry. Mirrors the contents of
 * `atomic-chat-conf/models/staff-picks.json` so Hub can render the curated
 * list on the very first launch (before the manifest fetch resolves) and when
 * the network is unavailable.
 *
 * Platform filtering happens at runtime in `staff-picks-registry.ts` — keep
 * `platforms` declarative here (do NOT inline `IS_MACOS` ternaries) so the
 * baseline mirrors the manifest shape verbatim.
 *
 * Generated from the manifest: edit that file, then mirror it here.
 */

import type { StaffPick } from '@/services/staff-picks-registry'

export const BASELINE_STAFF_PICKS: ReadonlyArray<StaffPick> = [
  {
    model_name: 'AtomicChat/Muse-Glimmer-30B-GGUF',
    title: 'Muse Glimmer 30B',
    summary: "Meta's multimodal Muse Glimmer with adjustable reasoning depth.",
    description_key: 'hub:recVisionKnowledge',
    icon: 'meta',
    format: 'gguf',
    categories: ['general', 'vision', 'reasoning', 'tools'],
    order: 1,
  },
  {
    model_name: 'AtomicChat/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF',
    title: 'Nemotron 3.5 Lightning',
    summary:
      'Sparse Mamba2 Nemotron: 30B total parameters, 3B active per token.',
    description_key: 'hub:recMathReasoning',
    icon: 'nvidia',
    format: 'gguf',
    categories: ['general', 'reasoning', 'tools'],
    order: 2,
  },
  {
    model_name: 'LiquidAI/LFM2.5-2.6B-GGUF',
    title: 'LFM2.5 2.6B',
    summary: 'On-device agent that always thinks before it answers.',
    description_key: 'hub:recEverydayUse',
    icon: 'lfm',
    format: 'gguf',
    categories: ['general', 'compact', 'reasoning', 'tools', 'multilingual'],
    order: 4,
  },
  {
    model_name: 'AtomicChat/Ling-3.0-flash-GGUF',
    title: 'Ling 3.0 flash',
    summary: 'Sparse 124B with linear attention: 5.1B active per token.',
    description_key: 'hub:recMathReasoning',
    icon: 'ling',
    format: 'gguf',
    categories: ['general', 'reasoning', 'tools'],
    order: 5,
  },
  {
    model_name: 'AtomicChat/Qwen3.6-27B-GGUF',
    title: 'Qwen3.6 27B',
    summary: 'Prioritizes stability and real-world coding quality.',
    description_key: 'hub:recCoding',
    icon: 'qwen',
    format: 'gguf',
    categories: ['general', 'coding', 'vision', 'reasoning', 'tools'],
    order: 10,
  },
  {
    model_name: 'AtomicChat/Qwen3.6-27B-MLX-4bit',
    title: 'Qwen3.6 27B (MLX)',
    summary: 'Prioritizes stability and real-world coding quality.',
    description_key: 'hub:recForMlx',
    icon: 'qwen',
    format: 'mlx',
    categories: ['general', 'coding', 'vision', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 15,
  },
  {
    model_name: 'AtomicChat/Qwen3.6-35B-A3B-GGUF',
    title: 'Qwen3.6 35B A3B',
    summary: 'Sparse Qwen3.6: 35B total parameters, 3B active per token.',
    description_key: 'hub:recMathReasoning',
    icon: 'qwen',
    format: 'gguf',
    categories: ['general', 'vision', 'reasoning', 'tools'],
    order: 20,
  },
  {
    model_name: 'mlx-community/Qwen3.6-35B-A3B-4bit',
    title: 'Qwen3.6 35B A3B (MLX)',
    summary: 'Sparse Qwen3.6: 35B total parameters, 3B active per token.',
    description_key: 'hub:recForMlx',
    icon: 'qwen',
    format: 'mlx',
    categories: ['general', 'vision', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 25,
  },
  {
    model_name: 'AtomicChat/Qwen3.5-9B-GGUF',
    title: 'Qwen3.5 9B',
    summary: 'Stronger reasoning while still fitting a 16 GB machine.',
    description_key: 'hub:recMathReasoning',
    icon: 'qwen',
    format: 'gguf',
    categories: ['general', 'vision', 'reasoning', 'tools'],
    order: 30,
  },
  {
    model_name: 'AtomicChat/Qwen3.5-9B-MLX-4bit',
    title: 'Qwen3.5 9B (MLX)',
    summary: 'Stronger reasoning while still fitting a 16 GB machine.',
    description_key: 'hub:recForMlx',
    icon: 'qwen',
    format: 'mlx',
    categories: ['general', 'vision', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 35,
  },
  {
    model_name: 'unsloth/Qwen3.5-35B-A3B-GGUF',
    title: 'Qwen3.5 35B A3B',
    summary: 'Sparse Qwen3.5: 35B total parameters, 3B active per token.',
    description_key: 'hub:recMathReasoning',
    icon: 'qwen',
    format: 'gguf',
    categories: ['general', 'vision', 'reasoning', 'tools'],
    order: 40,
  },
  {
    model_name: 'mlx-community/Qwen3.5-35B-A3B-4bit',
    title: 'Qwen3.5 35B A3B (MLX)',
    summary: 'Sparse Qwen3.5: 35B total parameters, 3B active per token.',
    description_key: 'hub:recForMlx',
    icon: 'qwen',
    format: 'mlx',
    categories: ['general', 'vision', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 45,
  },
  {
    model_name: 'Qwen/Qwen3-Coder-Next-GGUF',
    title: 'Qwen3 Coder Next',
    summary: "Qwen's coding specialist, published by the Qwen team.",
    description_key: 'hub:recCoding',
    icon: 'qwen',
    format: 'gguf',
    categories: ['coding', 'tools'],
    order: 50,
  },
  {
    model_name: 'mlx-community/Qwen3-Coder-Next-4bit',
    title: 'Qwen3 Coder Next (MLX)',
    summary: "Qwen's coding specialist, published by the Qwen team.",
    description_key: 'hub:recForMlx',
    icon: 'qwen',
    format: 'mlx',
    categories: ['coding', 'tools'],
    platforms: ['macos'],
    order: 55,
  },
  {
    model_name: 'AtomicChat/gemma-4-12B-it-GGUF',
    title: 'Gemma 4 12B',
    summary: 'Mid-size Gemma 4 with vision and long-context support.',
    description_key: 'hub:recVisionKnowledge',
    icon: 'gemma',
    format: 'gguf',
    categories: [
      'general',
      'multilingual',
      'vision',
      'audio',
      'reasoning',
      'tools',
    ],
    order: 60,
  },
  {
    model_name: 'AtomicChat/gemma-4-12B-it-MLX-4bit',
    title: 'Gemma 4 12B (MLX)',
    summary: 'Mid-size Gemma 4 with vision and long-context support.',
    description_key: 'hub:recForMlx',
    icon: 'gemma',
    format: 'mlx',
    categories: [
      'general',
      'multilingual',
      'vision',
      'audio',
      'reasoning',
      'tools',
    ],
    platforms: ['macos'],
    order: 65,
  },
  {
    model_name: 'AtomicChat/gemma-4-26B-A4B-it-GGUF',
    title: 'Gemma 4 26B A4B',
    summary: 'Sparse Gemma 4: 26B total parameters, 4B active per token.',
    description_key: 'hub:recVisionKnowledge',
    icon: 'gemma',
    format: 'gguf',
    categories: ['general', 'vision', 'reasoning', 'tools'],
    order: 70,
  },
  {
    model_name: 'AtomicChat/gemma-4-26B-A4B-it-MLX-4bit',
    title: 'Gemma 4 26B A4B (MLX)',
    summary: 'Sparse Gemma 4: 26B total parameters, 4B active per token.',
    description_key: 'hub:recForMlx',
    icon: 'gemma',
    format: 'mlx',
    categories: ['general', 'vision', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 75,
  },
  {
    model_name: 'AtomicChat/gemma-4-31B-it-GGUF',
    title: 'Gemma 4 31B',
    summary: 'Largest Gemma 4 variant, for machines with memory to spare.',
    description_key: 'hub:recVisionKnowledge',
    icon: 'gemma',
    format: 'gguf',
    categories: ['general', 'vision', 'reasoning', 'tools'],
    order: 80,
  },
  {
    model_name: 'AtomicChat/gemma-4-31B-it-MLX-4bit',
    title: 'Gemma 4 31B (MLX)',
    summary: 'Largest Gemma 4 variant, for machines with memory to spare.',
    description_key: 'hub:recForMlx',
    icon: 'gemma',
    format: 'mlx',
    categories: ['general', 'vision', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 85,
  },
  {
    model_name: 'AtomicChat/gemma-4-E4B-it-GGUF',
    title: 'Gemma 4 E4B',
    summary: "Google's efficient multimodal model with vision input.",
    description_key: 'hub:recEverydayUse',
    icon: 'gemma',
    format: 'gguf',
    categories: ['general', 'compact', 'vision', 'audio', 'reasoning', 'tools'],
    order: 90,
  },
  {
    model_name: 'AtomicChat/gemma-4-E4B-it-MLX-4bit',
    title: 'Gemma 4 E4B (MLX)',
    summary: "Google's efficient multimodal model with vision input.",
    description_key: 'hub:recForMlx',
    icon: 'gemma',
    format: 'mlx',
    categories: ['general', 'compact', 'vision', 'audio', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 95,
  },
  {
    model_name: 'AtomicChat/gemma-4-E2B-it-GGUF',
    title: 'Gemma 4 E2B',
    summary: 'The smallest Gemma 4, for laptops with little memory.',
    description_key: 'hub:recEverydayUse',
    icon: 'gemma',
    format: 'gguf',
    categories: ['general', 'compact', 'vision', 'audio', 'reasoning', 'tools'],
    order: 100,
  },
  {
    model_name: 'AtomicChat/gemma-4-E2B-it-MLX-4bit',
    title: 'Gemma 4 E2B (MLX)',
    summary: 'The smallest Gemma 4, for laptops with little memory.',
    description_key: 'hub:recForMlx',
    icon: 'gemma',
    format: 'mlx',
    categories: ['general', 'compact', 'vision', 'audio', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 105,
  },
  {
    model_name: 'LiquidAI/LFM2-24B-A2B-GGUF',
    title: 'LFM2 24B A2B',
    summary: "Liquid's sparse 24B: only 2B parameters active per token.",
    description_key: 'hub:recEverydayUse',
    icon: 'lfm',
    format: 'gguf',
    categories: ['general', 'tools'],
    order: 110,
  },
  {
    model_name: 'mlx-community/LFM2-24B-A2B-4bit',
    title: 'LFM2 24B A2B (MLX)',
    summary: "Liquid's sparse 24B: only 2B parameters active per token.",
    description_key: 'hub:recForMlx',
    icon: 'lfm',
    format: 'mlx',
    categories: ['general', 'tools'],
    platforms: ['macos'],
    order: 115,
  },
  {
    model_name: 'LiquidAI/LFM2.5-1.2B-Instruct-GGUF',
    title: 'LFM2.5 1.2B',
    summary: 'Runs on almost anything, including phones.',
    description_key: 'hub:recEverydayUse',
    icon: 'lfm',
    format: 'gguf',
    categories: ['general', 'compact', 'tools'],
    order: 120,
  },
  {
    model_name: 'mlx-community/LFM2.5-1.2B-Instruct-4bit',
    title: 'LFM2.5 1.2B (MLX)',
    summary: 'Runs on almost anything, including phones.',
    description_key: 'hub:recForMlx',
    icon: 'lfm',
    format: 'mlx',
    categories: ['general', 'compact', 'tools'],
    platforms: ['macos'],
    order: 125,
  },
  {
    model_name: 'LiquidAI/LFM2-1.2B-GGUF',
    title: 'LFM2 1.2B',
    summary: 'Tiny Liquid Foundation Model for edge devices.',
    description_key: 'hub:recEverydayUse',
    icon: 'lfm',
    format: 'gguf',
    categories: ['general', 'compact', 'tools'],
    order: 130,
  },
  {
    model_name: 'mlx-community/LFM2-1.2B-4bit',
    title: 'LFM2 1.2B (MLX)',
    summary: 'Tiny Liquid Foundation Model for edge devices.',
    description_key: 'hub:recForMlx',
    icon: 'lfm',
    format: 'mlx',
    categories: ['general', 'compact', 'tools'],
    platforms: ['macos'],
    order: 135,
  },
  {
    model_name: 'unsloth/DeepSeek-V4-Flash-GGUF',
    title: 'DeepSeek V4 Flash',
    summary: 'The fast variant of the DeepSeek V4 family.',
    description_key: 'hub:recMathReasoning',
    icon: 'deepseek',
    format: 'gguf',
    categories: ['general', 'reasoning', 'tools'],
    order: 140,
  },
  {
    model_name: 'mlx-community/DeepSeek-V4-Flash-4bit',
    title: 'DeepSeek V4 Flash (MLX)',
    summary: 'The fast variant of the DeepSeek V4 family.',
    description_key: 'hub:recForMlx',
    icon: 'deepseek',
    format: 'mlx',
    categories: ['general', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 145,
  },
  {
    model_name: 'AtomicChat/Laguna-S-2.1-GGUF',
    title: 'Laguna S 2.1',
    summary: "Poolside's Laguna S, built around software engineering work.",
    description_key: 'hub:recCoding',
    icon: 'poolside',
    format: 'gguf',
    categories: ['coding', 'reasoning', 'tools'],
    order: 150,
  },
  {
    model_name: 'AtomicChat/Laguna-S-2.1-MLX-4bit',
    title: 'Laguna S 2.1 (MLX)',
    summary: "Poolside's Laguna S, built around software engineering work.",
    description_key: 'hub:recForMlx',
    icon: 'poolside',
    format: 'mlx',
    categories: ['coding', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 155,
  },
  {
    model_name: 'prism-ml/Bonsai-27B-gguf',
    title: 'Bonsai 27B',
    summary: 'Prism ML packs a 27B model into extreme low-bit quantizations.',
    description_key: 'hub:recEverydayUse',
    icon: 'prism',
    format: 'gguf',
    categories: ['general', 'vision', 'reasoning', 'tools'],
    order: 160,
  },
  {
    model_name: 'prism-ml/Bonsai-27B-mlx-1bit',
    title: 'Bonsai 27B (MLX)',
    summary: 'Prism ML packs a 27B model into extreme low-bit quantizations.',
    description_key: 'hub:recForMlx',
    icon: 'prism',
    format: 'mlx',
    categories: ['general', 'vision', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 165,
  },
  {
    model_name: 'owao/Nanbeige4.2-3B-GGUF',
    title: 'Nanbeige4.2 3B',
    summary: 'Compact agentic 3B built for tool use and multi-step tasks.',
    description_key: 'hub:recEverydayUse',
    icon: 'nanbeige',
    format: 'gguf',
    categories: ['general', 'compact', 'reasoning', 'tools'],
    order: 167,
  },
  {
    model_name: 'unsloth/NVIDIA-Nemotron-3-Nano-Omni-30B-A3B-Reasoning-GGUF',
    title: 'Nemotron 3 Nano Omni',
    summary: "NVIDIA's omni-modal Nemotron Nano with reasoning traces.",
    description_key: 'hub:recMathReasoning',
    icon: 'nvidia',
    format: 'gguf',
    categories: ['vision', 'audio', 'reasoning', 'tools'],
    order: 170,
  },
  {
    model_name: 'mlx-community/Nemotron-3-Nano-Omni-30B-A3B-Reasoning-4bit',
    title: 'Nemotron 3 Nano Omni (MLX)',
    summary: "NVIDIA's omni-modal Nemotron Nano with reasoning traces.",
    description_key: 'hub:recForMlx',
    icon: 'nvidia',
    format: 'mlx',
    categories: ['vision', 'audio', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 175,
  },
  {
    model_name: 'unsloth/MiniMax-M2.7-GGUF',
    title: 'MiniMax M2.7',
    summary: 'Agentic coding model from MiniMax.',
    description_key: 'hub:recCoding',
    icon: 'minimax',
    format: 'gguf',
    categories: ['reasoning', 'coding', 'tools'],
    order: 180,
  },
  {
    model_name: 'mlx-community/MiniMax-M2.7-4bit',
    title: 'MiniMax M2.7 (MLX)',
    summary: 'Agentic coding model from MiniMax.',
    description_key: 'hub:recForMlx',
    icon: 'minimax',
    format: 'mlx',
    categories: ['reasoning', 'coding', 'tools'],
    platforms: ['macos'],
    order: 185,
  },
  {
    model_name: 'nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF',
    title: 'Nemotron 3 Nano 4B',
    summary: 'Compact Nemotron published by NVIDIA itself.',
    description_key: 'hub:recEverydayUse',
    icon: 'nvidia',
    format: 'gguf',
    categories: ['general', 'compact', 'reasoning', 'tools'],
    order: 190,
  },
  {
    model_name: 'mlx-community/NVIDIA-Nemotron-3-Nano-4B-4bit',
    title: 'Nemotron 3 Nano 4B (MLX)',
    summary: 'Compact Nemotron published by NVIDIA itself.',
    description_key: 'hub:recForMlx',
    icon: 'nvidia',
    format: 'mlx',
    categories: ['general', 'compact', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 195,
  },
  {
    model_name: 'unsloth/NVIDIA-Nemotron-3-Super-120B-A12B-GGUF',
    title: 'Nemotron 3 Super',
    summary: 'Sparse 120B Nemotron: 12B parameters active per token.',
    description_key: 'hub:recMathReasoning',
    icon: 'nvidia',
    format: 'gguf',
    categories: ['general', 'reasoning', 'tools'],
    order: 200,
  },
  {
    model_name: 'mlx-community/NVIDIA-Nemotron-3-Super-120B-A12B-4bit',
    title: 'Nemotron 3 Super (MLX)',
    summary: 'Sparse 120B Nemotron: 12B parameters active per token.',
    description_key: 'hub:recForMlx',
    icon: 'nvidia',
    format: 'mlx',
    categories: ['general', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 205,
  },
  {
    model_name: 'unsloth/MiniMax-M2.5-GGUF',
    title: 'MiniMax M2.5',
    summary: 'The previous MiniMax generation, still strong at code.',
    description_key: 'hub:recCoding',
    icon: 'minimax',
    format: 'gguf',
    categories: ['reasoning', 'coding', 'tools'],
    order: 210,
  },
  {
    model_name: 'mlx-community/MiniMax-M2.5-4bit',
    title: 'MiniMax M2.5 (MLX)',
    summary: 'The previous MiniMax generation, still strong at code.',
    description_key: 'hub:recForMlx',
    icon: 'minimax',
    format: 'mlx',
    categories: ['reasoning', 'coding', 'tools'],
    platforms: ['macos'],
    order: 215,
  },
  {
    model_name: 'unsloth/GLM-4.7-Flash-GGUF',
    title: 'GLM 4.7 Flash',
    summary: 'The lightweight member of the GLM 4.7 family.',
    description_key: 'hub:recEverydayUse',
    icon: 'glm',
    format: 'gguf',
    categories: ['general', 'reasoning', 'tools'],
    order: 220,
  },
  {
    model_name: 'mlx-community/GLM-4.7-Flash-4bit',
    title: 'GLM 4.7 Flash (MLX)',
    summary: 'The lightweight member of the GLM 4.7 family.',
    description_key: 'hub:recForMlx',
    icon: 'glm',
    format: 'mlx',
    categories: ['general', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 225,
  },
  {
    model_name: 'unsloth/Nemotron-3-Nano-30B-A3B-GGUF',
    title: 'Nemotron 3 Nano',
    summary: 'Sparse 30B Nemotron with 3B parameters active per token.',
    description_key: 'hub:recEverydayUse',
    icon: 'nvidia',
    format: 'gguf',
    categories: ['general', 'reasoning', 'tools'],
    order: 230,
  },
  {
    model_name: 'mlx-community/NVIDIA-Nemotron-3-Nano-30B-A3B-4bit',
    title: 'Nemotron 3 Nano (MLX)',
    summary: 'Sparse 30B Nemotron with 3B parameters active per token.',
    description_key: 'hub:recForMlx',
    icon: 'nvidia',
    format: 'mlx',
    categories: ['general', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 235,
  },
  {
    model_name: 'unsloth/Devstral-Small-2-24B-Instruct-2512-GGUF',
    title: 'Devstral Small 2 2512',
    summary: "Mistral's agentic coding model for local IDE work.",
    description_key: 'hub:recCoding',
    icon: 'mistral',
    format: 'gguf',
    categories: ['coding', 'vision', 'tools'],
    order: 240,
  },
  {
    model_name: 'mlx-community/Devstral-Small-2-24B-Instruct-2512-4bit',
    title: 'Devstral Small 2 2512 (MLX)',
    summary: "Mistral's agentic coding model for local IDE work.",
    description_key: 'hub:recForMlx',
    icon: 'mistral',
    format: 'mlx',
    categories: ['coding', 'vision', 'tools'],
    platforms: ['macos'],
    order: 245,
  },
  {
    model_name: 'mistralai/Ministral-3-14B-Reasoning-2512-GGUF',
    title: 'Ministral 3 14B Reasoning',
    summary: 'Mistral reasoning model at a size that fits one GPU.',
    description_key: 'hub:recMathReasoning',
    icon: 'mistral',
    format: 'gguf',
    categories: ['vision', 'reasoning', 'tools'],
    order: 260,
  },
  {
    model_name: 'mlx-community/Ministral-3-14B-Reasoning-2512-4bit',
    title: 'Ministral 3 14B Reasoning (MLX)',
    summary: 'Mistral reasoning model at a size that fits one GPU.',
    description_key: 'hub:recForMlx',
    icon: 'mistral',
    format: 'mlx',
    categories: ['vision', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 265,
  },
  {
    model_name: 'mistralai/Ministral-3-3B-Instruct-2512-GGUF',
    title: 'Ministral 3 3B',
    summary: 'Small Mistral for quick local answers.',
    description_key: 'hub:recEverydayUse',
    icon: 'mistral',
    format: 'gguf',
    categories: ['general', 'compact', 'vision', 'tools'],
    order: 270,
  },
  {
    model_name: 'mlx-community/Ministral-3-3B-Instruct-2512-4bit',
    title: 'Ministral 3 3B (MLX)',
    summary: 'Small Mistral for quick local answers.',
    description_key: 'hub:recForMlx',
    icon: 'mistral',
    format: 'mlx',
    categories: ['general', 'compact', 'vision', 'tools'],
    platforms: ['macos'],
    order: 275,
  },
  {
    model_name: 'unsloth/Olmo-3-32B-Think-GGUF',
    title: 'Olmo 3 32B Think',
    summary: 'Fully open reasoning model from Ai2, weights and data alike.',
    description_key: 'hub:recMathReasoning',
    icon: 'allenai',
    format: 'gguf',
    categories: ['reasoning', 'tools'],
    order: 280,
  },
  {
    model_name: 'lmstudio-community/Olmo-3-32B-Think-MLX-4bit',
    title: 'Olmo 3 32B Think (MLX)',
    summary: 'Fully open reasoning model from Ai2, weights and data alike.',
    description_key: 'hub:recForMlx',
    icon: 'allenai',
    format: 'mlx',
    categories: ['reasoning', 'tools'],
    platforms: ['macos'],
    order: 285,
  },
  {
    model_name: 'lmstudio-community/olmOCR-2-7B-1025-GGUF',
    title: 'olmOCR 2 7B',
    summary: 'Turns scanned pages into structured text.',
    description_key: 'hub:recVisionKnowledge',
    icon: 'allenai',
    format: 'gguf',
    categories: ['vision'],
    order: 290,
  },
  {
    model_name: 'mlx-community/olmOCR-2-7B-1025-mlx-4bit',
    title: 'olmOCR 2 7B (MLX)',
    summary: 'Turns scanned pages into structured text.',
    description_key: 'hub:recForMlx',
    icon: 'allenai',
    format: 'mlx',
    categories: ['vision'],
    platforms: ['macos'],
    order: 295,
  },
  {
    model_name: 'unsloth/MiniMax-M2-GGUF',
    title: 'MiniMax M2',
    summary: 'The first MiniMax M2 release.',
    description_key: 'hub:recCoding',
    icon: 'minimax',
    format: 'gguf',
    categories: ['reasoning', 'coding', 'tools'],
    order: 300,
  },
  {
    model_name: 'mlx-community/MiniMax-M2-4bit',
    title: 'MiniMax M2 (MLX)',
    summary: 'The first MiniMax M2 release.',
    description_key: 'hub:recForMlx',
    icon: 'minimax',
    format: 'mlx',
    categories: ['reasoning', 'coding', 'tools'],
    platforms: ['macos'],
    order: 305,
  },
  {
    model_name: 'ibm-granite/granite-4.0-h-tiny-GGUF',
    title: 'Granite 4 H Tiny',
    summary: "IBM's small hybrid Granite, published by IBM itself.",
    description_key: 'hub:recEverydayUse',
    icon: 'ibm',
    format: 'gguf',
    categories: ['general', 'compact', 'tools'],
    order: 310,
  },
  {
    model_name: 'mlx-community/granite-4.0-h-tiny-4bit',
    title: 'Granite 4 H Tiny (MLX)',
    summary: "IBM's small hybrid Granite, published by IBM itself.",
    description_key: 'hub:recForMlx',
    icon: 'ibm',
    format: 'mlx',
    categories: ['general', 'compact', 'tools'],
    platforms: ['macos'],
    order: 315,
  },
  {
    model_name: 'unsloth/Hermes-4-70B-GGUF',
    title: 'Hermes 4 70B',
    summary: 'Nous Research fine-tune known for steerable chat.',
    description_key: 'hub:recFinetuningChat',
    icon: 'nous',
    format: 'gguf',
    categories: ['general', 'reasoning', 'tools'],
    order: 320,
  },
  {
    model_name: 'mlx-community/Hermes-4-70B-4bit',
    title: 'Hermes 4 70B (MLX)',
    summary: 'Nous Research fine-tune known for steerable chat.',
    description_key: 'hub:recForMlx',
    icon: 'nous',
    format: 'mlx',
    categories: ['general', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 325,
  },
  {
    model_name: 'unsloth/gpt-oss-20b-GGUF',
    title: 'GPT-OSS 20B',
    summary: "OpenAI's smaller open-weights model, native MXFP4.",
    description_key: 'hub:recEverydayUse',
    icon: 'openai',
    format: 'gguf',
    categories: ['general', 'reasoning', 'tools'],
    order: 330,
  },
  {
    model_name: 'mlx-community/gpt-oss-20b-MXFP4-Q8',
    title: 'GPT-OSS 20B (MLX)',
    summary: "OpenAI's smaller open-weights model, native MXFP4.",
    description_key: 'hub:recForMlx',
    icon: 'openai',
    format: 'mlx',
    categories: ['general', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 335,
  },
  {
    model_name: 'unsloth/gpt-oss-120b-GGUF',
    title: 'GPT-OSS 120B',
    summary: "OpenAI's large open-weights model for workstations.",
    description_key: 'hub:recMathReasoning',
    icon: 'openai',
    format: 'gguf',
    categories: ['general', 'reasoning', 'tools'],
    order: 340,
  },
  {
    model_name: 'mlx-community/gpt-oss-120b-MXFP4-Q8',
    title: 'GPT-OSS 120B (MLX)',
    summary: "OpenAI's large open-weights model for workstations.",
    description_key: 'hub:recForMlx',
    icon: 'openai',
    format: 'mlx',
    categories: ['general', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 345,
  },
  {
    model_name: 'microsoft/phi-4-gguf',
    title: 'Phi 4',
    summary: "Microsoft's 14B model, strong on maths for its size.",
    description_key: 'hub:recMathReasoning',
    icon: 'microsoft',
    format: 'gguf',
    categories: ['general'],
    order: 350,
  },
  {
    model_name: 'mlx-community/phi-4-4bit',
    title: 'Phi 4 (MLX)',
    summary: "Microsoft's 14B model, strong on maths for its size.",
    description_key: 'hub:recForMlx',
    icon: 'microsoft',
    format: 'mlx',
    categories: ['general'],
    platforms: ['macos'],
    order: 355,
  },
  {
    model_name: 'ibm-granite/granite-3.3-8b-instruct-GGUF',
    title: 'Granite 3.3 8B',
    summary: 'Enterprise-oriented Granite with a permissive licence.',
    description_key: 'hub:recEverydayUse',
    icon: 'ibm',
    format: 'gguf',
    categories: ['general', 'reasoning', 'tools'],
    order: 360,
  },
  {
    model_name: 'mlx-community/granite-3.3-8b-instruct-4bit',
    title: 'Granite 3.3 8B (MLX)',
    summary: 'Enterprise-oriented Granite with a permissive licence.',
    description_key: 'hub:recForMlx',
    icon: 'ibm',
    format: 'mlx',
    categories: ['general', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 365,
  },
  {
    model_name: 'unsloth/Llama-3.3-70B-Instruct-GGUF',
    title: 'Llama 3.3 70B',
    summary: 'The classic Llama 70B, still a solid multilingual chat model.',
    description_key: 'hub:recFinetuningChat',
    icon: 'llama',
    format: 'gguf',
    categories: ['general', 'multilingual', 'tools'],
    order: 370,
  },
  {
    model_name: 'mlx-community/Llama-3.3-70B-Instruct-4bit',
    title: 'Llama 3.3 70B (MLX)',
    summary: 'The classic Llama 70B, still a solid multilingual chat model.',
    description_key: 'hub:recForMlx',
    icon: 'llama',
    format: 'mlx',
    categories: ['general', 'multilingual', 'tools'],
    platforms: ['macos'],
    order: 375,
  },
  {
    model_name: 'unsloth/Seed-OSS-36B-Instruct-GGUF',
    title: 'Seed-OSS 36B',
    summary: "ByteDance's open 36B with a very long context window.",
    description_key: 'hub:recEverydayUse',
    icon: 'bytedance',
    format: 'gguf',
    categories: ['general', 'reasoning', 'tools'],
    order: 380,
  },
  {
    model_name: 'mlx-community/Seed-OSS-36B-Instruct-4bit',
    title: 'Seed-OSS 36B (MLX)',
    summary: "ByteDance's open 36B with a very long context window.",
    description_key: 'hub:recForMlx',
    icon: 'bytedance',
    format: 'mlx',
    categories: ['general', 'reasoning', 'tools'],
    platforms: ['macos'],
    order: 385,
  },
]
