"""
User-defined workers: load all *Worker classes from this package and expose (skill_name, class).

Convention: module {skill}_worker.py defines class {Skill}Worker (e.g. my_task_worker.py -> MyTaskWorker -> skill "my_task").
Generated by Web UI or added manually. Engine registers these after built-ins.
"""

from __future__ import annotations

import importlib.util
import logging
import re
from pathlib import Path
from typing import TYPE_CHECKING

from sovereign_os.agents.base import BaseWorker

if TYPE_CHECKING:
    from typing import Type

logger = logging.getLogger(__name__)

_USER_WORKERS_DIR = Path(__file__).resolve().parent
_SKILL_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")


def _skill_from_class_name(class_name: str) -> str | None:
    """MyTaskWorker -> my_task; SummarizerWorker -> summarizer."""
    if not class_name.endswith("Worker"):
        return None
    base = class_name[:-6]  # strip "Worker"
    if not base:
        return None
    # CamelCase to snake_case: insert _ before capitals, then lower
    out: list[str] = []
    for i, c in enumerate(base):
        if c.isupper() and out:
            out.append("_")
        out.append(c.lower() if c.isalpha() else c)
    return "".join(out) if out else None


def get_user_workers() -> list[tuple[str, "Type[BaseWorker]"]]:
    """
    Discover all .py modules in this directory (except __init__), import them,
    and return (skill_name, worker_class) for each BaseWorker subclass.
    """
    result: list[tuple[str, type[BaseWorker]]] = []
    for path in _USER_WORKERS_DIR.glob("*.py"):
        if path.name.startswith("_"):
            continue
        mod_name = path.stem  # e.g. my_task_worker
        if not mod_name.endswith("_worker"):
            continue
        try:
            spec = importlib.util.spec_from_file_location(
                f"sovereign_os.agents.user_workers.{mod_name}",
                path,
            )
            if spec is None or spec.loader is None:
                continue
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            for attr_name in dir(mod):
                if attr_name.startswith("_"):
                    continue
                obj = getattr(mod, attr_name)
                if (
                    isinstance(obj, type)
                    and issubclass(obj, BaseWorker)
                    and obj is not BaseWorker
                ):
                    skill = _skill_from_class_name(obj.__name__)
                    if skill and _SKILL_PATTERN.match(skill):
                        result.append((skill, obj))
                        logger.info("Loaded user worker: %s -> %s", skill, obj.__name__)
                    break
        except Exception as e:
            logger.warning("Failed to load user worker from %s: %s", path.name, e)
    return result
