[
  import_deps: [:phoenix],
  plugins: [Phoenix.LiveView.HTMLFormatter],
  locals_without_parens: [
    action: 1,
    agent: 1,
    agent: 2,
    ash_resource: 1,
    ash_resource: 2,
    browser: 1,
    browser: 2,
    catalog: 1,
    catalog: 2,
    controls: 1,
    context: 1,
    description: 1,
    from: 1,
    from: 2,
    function: 3,
    generation: 1,
    handoff: 1,
    handoff: 2,
    id: 1,
    input: 1,
    instructions: 1,
    load_path: 1,
    max_turns: 1,
    memory: 1,
    mcp_tools: 1,
    model: 1,
    operation: 1,
    operation: 2,
    output: 1,
    result: 1,
    skill: 1,
    steps: 1,
    subagent: 1,
    subagent: 2,
    timeout: 1,
    tools: 1,
    workflow: 1,
    workflow: 2,
    value: 1
  ],
  inputs: [
    "*.{ex,exs}",
    "{config,lib}/**/*.{ex,exs,heex}"
  ]
]
