FROM golang:1.26-alpine
ARG SERVICE
ENV SERVICE=${SERVICE}
RUN apk add --no-cache git
RUN go install github.com/air-verse/air@latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
CMD air -c .air.${SERVICE}.toml
