/**
 * Generates API reference pages from the OpenAPI spec, grouped by tag.
 * Run: bun scripts/generate-docs.ts
 *
 * Reads ../openapi.json and creates:
 * - content/docs/api-reference/index.mdx (overview with version)
 * - content/docs/api-reference/<tag>.mdx (one per tag group)
 * - content/docs/api-reference/meta.json (auto-generated sidebar)
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
// Resolved from the repo-root node_modules (root devDependency) — CI's
// openapi-freshness job installs only root deps, not docs-site's.
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));

const specPath = resolve(__dirname, "../../openapi.json");
const outputDir = resolve(__dirname, "../content/docs/api-reference");

const spec = JSON.parse(readFileSync(specPath, "utf-8"));

const version: string = spec.info?.version ?? "unknown";
const serverUrl: string = spec.servers?.[0]?.url ?? "http://localhost:3013";

// --- Group operations by tag ---

interface Operation {
  path: string;
  method: string;
  summary: string;
}

const tagGroups = new Map<string, Operation[]>();

for (const [path, methods] of Object.entries(spec.paths ?? {})) {
  for (const [method, op] of Object.entries(methods as Record<string, unknown>)) {
    if (typeof op !== "object" || op === null) continue;
    const opObj = op as { tags?: string[]; summary?: string };
    const tags = opObj.tags?.length ? opObj.tags : ["Other"];
    for (const tag of tags) {
      if (!tagGroups.has(tag)) tagGroups.set(tag, []);
      tagGroups.get(tag)!.push({
        path,
        method,
        summary: opObj.summary ?? "",
      });
    }
  }
}

// Sort tags alphabetically, sort operations within each tag
const sortedTags = [...tagGroups.keys()].sort();
for (const tag of sortedTags) {
  tagGroups
    .get(tag)!
    .sort((a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method));
}

// --- Slug helper ---

function slugify(tag: string): string {
  return tag
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

// --- Clean output directory (remove old generated .mdx files) ---

mkdirSync(outputDir, { recursive: true });

if (existsSync(outputDir)) {
  for (const file of readdirSync(outputDir)) {
    if (file.endsWith(".mdx")) {
      rmSync(resolve(outputDir, file));
    }
  }
}

// --- Generate index page ---

const totalOps = [...tagGroups.values()].reduce((sum, ops) => sum + ops.length, 0);

const tagList = sortedTags
  .map((tag) => {
    const slug = slugify(tag);
    const count = tagGroups.get(tag)!.length;
    return `- [${tag}](/docs/api-reference/${slug}) — ${count} endpoint${count !== 1 ? "s" : ""}`;
  })
  .join("\n");

const indexMdx = `---
title: API Reference
description: Complete REST API reference for agent-swarm.dev — ${totalOps} endpoints across tasks, agents, workflows, memory, webhooks, and more. Build multi-agent orchestration with HTTP APIs and real-time event streaming.
---

{/* This file was generated by scripts/generate-docs.ts. Do not edit manually. */}

## agent-swarm.dev API v${version}

Base URL: \`${serverUrl}\`

${totalOps} endpoints across ${sortedTags.length} categories.

### Categories

${tagList}
`;

writeFileSync(resolve(outputDir, "index.mdx"), indexMdx);

// --- Tag descriptions for SEO (used in frontmatter) ---

const tagDescriptions: Record<string, string> = {
  "API Keys": "Manage API keys for authenticating requests to the agent-swarm.dev API",
  "Active Sessions": "Monitor and control active agent sessions running in the swarm",
  "Agents": "CRUD operations for agent profiles — create, configure, update, and manage swarm agents",
  "ApprovalRequests": "Human-in-the-loop approval requests — review and respond to agent-escalated decisions",
  "Budgets": "Configure per-agent and global daily cost budgets to control AI agent spend",
  "Config": "Read and write swarm configuration values — global, agent-scoped, and repo-scoped settings",
  "Debug": "Debug utilities for inspecting swarm state and diagnosing agent issues",
  "Ecosystem": "Query registered community and official agent integrations in the swarm ecosystem",
  "Events": "Stream and query swarm lifecycle events — task transitions, agent state changes, and audit log",
  "Heartbeat": "Health check endpoint — verify the agent-swarm.dev API is running and reachable",
  "Inbox State": "Manage per-user inbox item state — dismiss, snooze, and mark-done flags for swarm notifications and approval items",
  "Integrations": "Configure third-party integrations — Slack, GitHub, GitLab, Linear, Jira, Sentry, and more",
  "KV": "Namespaced key-value store API — read, write, delete, list, and atomically increment KV entries for cross-task agent state",
  "MCP OAuth": "OAuth flows for MCP client authorization — register and manage OAuth connections",
  "MCP Servers": "Register and manage MCP tool servers available to swarm agents",
  "Memory": "Search, retrieve, and manage persistent agent memories across sessions",
  "Pages": "Create, version, launch, and render DB-backed pages — build interactive dashboards and static artifacts served by the swarm",
  "Poll": "Long-poll endpoints for real-time task and message notifications without WebSockets",
  "Pricing": "Retrieve model pricing data used for cost tracking and budget enforcement across agents",
  "PromptTemplates": "Store and retrieve reusable prompt templates for consistent agent instructions",
  "Repos": "Register code repositories and configure VCS integration for automated task triggers",
  "Schedules": "Create and manage scheduled tasks — run agents on cron expressions or one-time delays",
  "Scripts": "Author, search, and run reusable TypeScript scripts — a shared automation catalog callable across swarm agents and workflows",
  "Script Runs":
    "Inspect durable script workflow runs, review journal entries, and monitor swarm-script, raw-LLM, and agent-task execution status through the Script Runs API",
  "Session Data": "Access session-level data including token counts, costs, and context window metrics",
  "Sessions": "Inspect task sessions — list recent root tasks and retrieve the full descendant task chain for a session",
  "Skills": "Install, publish, and manage skills — reusable agent behaviors and tool sets",
  "Stats": "Aggregate statistics for swarm activity — task counts, agent utilization, and cost summaries",
  "Status": "Swarm dashboard status endpoint — identity, setup readiness, live activity, and harness provider credential testing",
  "Tasks": "Core task API — create, assign, update, and monitor tasks across the swarm",
  "Trackers": "Integrate with Linear and Jira ticket trackers — sync issues to swarm tasks bidirectionally",
  "Users": "Manage the user registry — create users, link cross-platform identities, mint tokens, merge duplicates, and triage unmapped senders",
  "Webhooks": "Register and manage webhooks for real-time swarm event delivery to external systems",
  "Workflows": "Define and execute DAG-based multi-step workflows with branching, triggers, and agent task nodes",
};

// --- Generate per-tag pages ---

for (const tag of sortedTags) {
  const slug = slugify(tag);
  const ops = tagGroups.get(tag)!;
  const opsJson = JSON.stringify(ops.map((o) => ({ path: o.path, method: o.method })));
  const description = tagDescriptions[tag] ?? `${tag} API endpoints`;

  const tagMdx = `---
title: "${tag}"
description: "${description}"
full: true
---

{/* This file was generated by scripts/generate-docs.ts. Do not edit manually. */}

<APIPage document={"../openapi.json"} operations={${opsJson}} />
`;


  writeFileSync(resolve(outputDir, `${slug}.mdx`), tagMdx);
}

// --- Generate TypeScript definitions (public/openapi.d.ts) + typescript.mdx ---

const publicDir = resolve(__dirname, "../public");
mkdirSync(publicDir, { recursive: true });
const dtsAst = await openapiTS(spec);
writeFileSync(resolve(publicDir, "openapi.d.ts"), astToString(dtsAst));

const typescriptMdx = `---
title: "TypeScript Types"
description: "Generate a fully type-safe TypeScript SDK from the agent-swarm.dev OpenAPI spec — typed request bodies, params, and response shapes for all ${totalOps} endpoints"
---

{/* This file was generated by scripts/generate-docs.ts. Do not edit manually. */}

Every endpoint in this reference declares its request **and response** schemas in the
OpenAPI 3.1 spec, so a generated client is fully typed end to end — no \`unknown\`
responses. Each operation page also shows its exact response type inline (the
"TypeScript Definitions" panel under each response code).

## Pre-generated definitions

- [openapi.d.ts](/openapi.d.ts) — TypeScript definitions for all ${totalOps} operations (\`paths\` + \`components\`), generated with [openapi-typescript](https://openapi-ts.dev)
- [openapi.json](https://github.com/desplega-ai/agent-swarm/blob/main/openapi.json) — the spec itself (also served at \`GET /openapi.json\` by every running server)

## Generate your own

\`\`\`bash
bunx openapi-typescript http://localhost:3013/openapi.json -o api.d.ts
\`\`\`

## Use with openapi-fetch

\`\`\`ts
import createClient from "openapi-fetch";
import type { components, paths } from "./api";

const client = createClient<paths>({
  baseUrl: "http://localhost:3013",
  headers: { Authorization: \`Bearer \${process.env.AGENT_SWARM_API_KEY}\` },
});

// Fully typed: data is { tasks: AgentTask[] | AgentTaskSummary[]; total: number }
const { data, error } = await client.GET("/api/tasks", {
  params: { query: { status: "in_progress" } },
});

// Entity types come from the named schema components
type AgentTask = components["schemas"]["AgentTask"];
type Workflow = components["schemas"]["Workflow"];
\`\`\`
`;

writeFileSync(resolve(outputDir, "typescript.mdx"), typescriptMdx);

// --- Generate meta.json ---

const pages = ["index", "typescript", ...sortedTags.map(slugify)];

const metaJson = {
  title: `API Reference v${version}`,
  description: "REST API reference for agent-swarm.dev",
  root: true,
  pages,
};

writeFileSync(resolve(outputDir, "meta.json"), `${JSON.stringify(metaJson, null, 2)}\n`);

console.log(
  `Generated API reference: ${sortedTags.length} tag pages + index (${totalOps} operations, v${version})`,
);
