#!/usr/bin/env python3
"""Import a scouted source catalog (CSV) into the deep-research source registry.

The skill catalogs *how to reach* a source (api_sources/) and *what a domain's canonical
sources are* (stat_sources/). It had no registry of concrete verified endpoints per signal
type, so "where do I watch X" had no cheap answer in Phase 4.

Input is a scouting CSV with one row per source and, critically, the columns the skill
actually needs: `signal_type` (what question the source answers), `access` (key/UA/paid),
`credibility`, `value_score`, `access_state`. An earlier attempt grouped an adjacent
TOML export by its `topics` field instead — that field turned out to be an autogenerated
label, not a taxonomy (its "patents" bucket held job boards and LeetCode), so grouping
here is by `signal_type` and nothing else.

The input file is private research data, is NOT part of this repo, and is passed by path.
Only signal types listed in GROUPS are emitted; the importing project's own market-intel
signals are dropped outright, so private competitive research never lands in a public repo.

Usage:
    python scripts/import_source_registry.py --source ~/path/sources.csv --dry-run
    python scripts/import_source_registry.py --source ~/path/sources.csv --min-value 5
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

# signal_type -> output file. A signal type absent from this map is dropped with a reason.
GROUPS: dict[str, str] = {
    "research-frontier": "science.md",
    "research-data-signal": "science.md",
    "citation-index-signal": "science.md",
    "replication-signal": "science.md",
    "benchmark-shift": "science.md",
    "publishing-infrastructure-signal": "science.md",
    "genomic-access-policy-signal": "science.md",
    "macro-risk": "markets.md",
    "market-price-signal": "markets.md",
    "financial-distress-signal": "markets.md",
    "funding-signal": "markets.md",
    "commodity-production-volume-signal": "markets.md",
    "regulatory-risk": "regulatory.md",
    "regulatory-opportunity": "regulatory.md",
    "legislative-process-signal": "regulatory.md",
    "identity-standard-signal": "regulatory.md",
    "resource-rights-registry-signal": "regulatory.md",
    "ip-activity-signal": "registries.md",
    "market-registry-signal": "registries.md",
    "security-advisory-signal": "security.md",
    "threat-intel-signal": "security.md",
    "infra-reliability-signal": "security.md",
    "esg-disclosure-signal": "climate_health.md",
    "historical-climate-reconstruction-signal": "climate_health.md",
    "drug-shortage-signal": "climate_health.md",
    "disaster-response-operations-signal": "climate_health.md",
    "humanitarian-crisis-signal": "climate_health.md",
    "conflict-event-signal": "society.md",
    "state-narrative-signal": "society.md",
    "democracy-index-signal": "society.md",
    "crime-victimization-statistics-signal": "society.md",
    "infrastructure-index-signal": "society.md",
    "talent-flow-signal": "society.md",
    "cultural-heritage-signal": "society.md",
    "gaming-industry-data-signal": "society.md",
    "gaming-content-rating-signal": "society.md",
    "sports-performance-data-signal": "society.md",
    "early-adoption": "technology.md",
    "practitioner-early-signal": "technology.md",
    "oss-release-signal": "technology.md",
    "launch-manifest-signal": "technology.md",
    # 483 library-release endpoints at value 5 alone. A release firehose, not research
    # material, and it would outweigh every other group combined — own file so a run
    # ignores it for free.
    "dependency-ecosystem-signal": "open_source_releases.md",
}

# Signals about the importing project's own market. Never emitted.
DROP_PRIVATE_SIGNALS = {"demand-validation", "competitive-move"}
DROP_PRIVATE_CHANNELS = {"domain-competitive", "domain-competitive-intelligence"}

# Municipal GIS endpoints: near-identical city datasets behind ArcGIS. Real data, wrong
# altitude — geo/municipal questions already route via stat_sources/core/data_aggregators.
DROP_URI_RE = re.compile(r"arcgis", re.IGNORECASE)

# A GitHub releases endpoint is a release feed whatever the scouting label says. Two labels
# leaked such rows into topical files — `ip-activity-signal` (an OSS licence read as IP
# activity) and `early-adoption` — so route by URL shape, which cannot be mislabelled.
RELEASE_URL_RE = re.compile(r"github\.com/[^/]+/[^/]+/releases", re.IGNORECASE)

HEADERS: dict[str, tuple[str, str]] = {
    "science.md": (
        "Наука",
        "Фронтир исследований, датасеты, индексы цитирования, репликации, бенчмарки.",
    ),
    "markets.md": (
        "Рынки и макро",
        "Макрориски, цены, финансовое состояние, раунды и объёмы производства.",
    ),
    "regulatory.md": (
        "Регуляторика и право",
        "Регуляторные риски и возможности, законодательный процесс, стандарты, права на ресурсы.",
    ),
    "registries.md": (
        "Реестры",
        "Корпоративные, сетевые, тендерные и некоммерческие реестры — вход для вопроса «кто это и чем владеет». "
        "Патентных ведомств здесь нет: в разведке их не оказалось, дыра закрывается вручную через api_sources/.",
    ),
    "security.md": (
        "Безопасность и надёжность",
        "Advisory-фиды, threat intel, состояние инфраструктуры.",
    ),
    "climate_health.md": (
        "Климат, ESG и здравоохранение",
        "Раскрытия ESG, климатические реконструкции, дефицит лекарств, ЧС и гуманитарные кризисы.",
    ),
    "society.md": (
        "Общество",
        "Конфликты, госнарративы, индексы демократии и инфраструктуры, рынок труда, культура, игры, спорт.",
    ),
    "technology.md": (
        "Технологии",
        "Раннее внедрение, сигналы от практиков, релизы, пусковые манифесты.",
    ),
    "open_source_releases.md": (
        "Релизы open source",
        "Поток релизов библиотек. Полезен для «что вышло/изменилось в X», бесполезен для "
        "остального — отдельный файл, чтобы не грузить зря.",
    ),
}

# access has 36 free-text variants in the source; collapse to the part before any comment.
_ACCESS_CLEAN_RE = re.compile(r"\s*[(（].*$")


def norm_access(raw: str) -> str:
    v = _ACCESS_CLEAN_RE.sub("", raw).strip().lower()
    if not v:
        return "—"
    if v in {"free", "free-no-key", "free-no-key-required-registration"}:
        return "free"
    if v.startswith("free-rate"):
        return "free, rate-limited"
    if "payment" in v:
        return "платный"
    if "blocked" in v:
        return "blocked"
    if "geo" in v:
        return "geo-restricted"
    if "key" in v or "signup" in v or "registration" in v or "oauth" in v:
        return "нужен ключ"
    if "user-agent" in v:
        return "нужен User-Agent"
    return v


def norm_credibility(raw: str) -> str:
    v = raw.strip().lower()
    for level in ("high", "medium", "low"):
        if v.startswith(level):
            return level
    return "—"


def load(
    path: Path, min_value: int
) -> tuple[dict[str, list[dict]], Counter, list[str]]:
    routed: dict[str, list[dict]] = defaultdict(list)
    dropped: Counter = Counter()
    problems: list[str] = []
    seen: set[str] = set()

    with path.open(encoding="utf-8", newline="") as fh:
        for lineno, row in enumerate(csv.DictReader(fh), start=2):
            url = (row.get("url") or "").strip()
            title = (row.get("title") or "").strip()
            if not url or not title:
                problems.append(f"row {lineno}: missing url/title — skipped")
                continue
            if row.get("signal_type", "") in DROP_PRIVATE_SIGNALS:
                dropped["private-signal"] += 1
                continue
            if row.get("channel", "") in DROP_PRIVATE_CHANNELS:
                dropped["private-channel"] += 1
                continue
            if row.get("access_state", "") == "3" or "blocked" in (
                row.get("access") or ""
            ):
                dropped["known-dead"] += 1
                continue
            if DROP_URI_RE.search(url):
                dropped["municipal-gis"] += 1
                continue
            try:
                value = int(row.get("value_score") or 0)
            except ValueError:
                value = 0
            if value < min_value:
                dropped[f"value<{min_value}"] += 1
                continue
            target = GROUPS.get(row.get("signal_type", ""))
            if target is None:
                dropped["unmapped-signal"] += 1
                continue
            if RELEASE_URL_RE.search(url):
                target = "open_source_releases.md"
            if url in seen:
                dropped["duplicate-url"] += 1
                continue
            seen.add(url)
            routed[target].append(
                {
                    "title": title,
                    "url": url,
                    "signal": row.get("signal_type", ""),
                    "access": norm_access(row.get("access") or ""),
                    "credibility": norm_credibility(row.get("credibility") or ""),
                    "needs_action": row.get("access_state", "") == "2",
                }
            )
    return routed, dropped, problems


def render(filename: str, rows: list[dict], verified: str, min_value: int) -> str:
    title, blurb = HEADERS[filename]
    needs = sum(1 for r in rows if r["needs_action"])
    lines = [
        f"# Реестр источников — {title}",
        "",
        blurb,
        "",
        f"**Проверено:** {verified} — каждый адрес отвечал живым запросом на момент разведки. "
        f"Отобраны только источники ценности {min_value} из 5.",
        "**Адреса конечные, после редиректов** — исходная проверка шла без `curl -L`, "
        "иначе мёртвый адрес красится зелёным ответом с редиректа.",
        f"**Записей:** {len(rows)}"
        + (f", из них {needs} требуют ключ или регистрацию." if needs else "."),
        "",
        "Реестр отвечает на «где смотреть по этому сигналу», а не «насколько источник надёжен»: "
        "колонка достоверности — оценка разведки, а не результат Фазы 5. Провенанс числа всё равно "
        "проверяется по `source_scoring.md`. Срок годности такого списка — месяцы; мёртвый адрес "
        "не баг реестра, а сигнал перепроверить.",
        "",
        "| Источник | Адрес | Сигнал | Доступ | Достоверность |",
        "|---|---|---|---|---|",
    ]
    for r in sorted(rows, key=lambda x: (x["signal"], x["title"])):
        name = r["title"].replace("|", "\\|")
        lines.append(
            f"| {name} | <{r['url']}> | {r['signal']} | {r['access']} | {r['credibility']} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_index(routed: dict[str, list[dict]], verified: str, min_value: int) -> str:
    total = sum(len(v) for v in routed.values())
    lines = [
        "# Source registry — INDEX",
        "",
        f"Конкретные проверенные адреса по типу сигнала: {total} записей, разведка {verified}, "
        f"порог ценности {min_value}/5.",
        "",
        "Читается точечно в Фазе 4, когда подвопрос требует свежего потока по теме "
        "(каналы `news-current`, `industry-specific`, `preprint-servers`, `forum-discussion`, "
        "`api-direct`). В базовый бюджет не входит — грузи нужный файл, не все.",
        "",
        "| Файл | Тема | Записей |",
        "|---|---|---|",
    ]
    for filename in sorted(routed, key=lambda k: -len(routed[k])):
        name, _ = HEADERS[filename]
        lines.append(f"| `{filename}` | {name} | {len(routed[filename])} |")
    lines += [
        "",
        "## Чего здесь нет",
        "",
        "- Оценки источника под конкретное утверждение — это `source_scoring.md` и Фаза 5.5.",
        "- Способа доступа с лимитами и примерами запросов — это `api_sources/`.",
        "- Канонических источников домена — это `stat_sources/`.",
        "- Рыночной разведки импортирующего проекта, муниципальных GIS-датасетов и адресов, "
        "уже помеченных мёртвыми, — отфильтрованы при импорте "
        "(`scripts/import_source_registry.py`).",
        "",
        "## Обновление",
        "",
        "```bash",
        "python scripts/import_source_registry.py --source <путь>/sources.csv --min-value 5",
        "```",
        "",
        "Порог `--min-value 3` даёт примерно втрое больше записей — расширять осознанно, "
        "каталог платит за это контекстом.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--source", type=Path, required=True, help="scouting CSV (private, not in repo)"
    )
    ap.add_argument(
        "--out", type=Path, default=Path("references/registry"), help="output directory"
    )
    ap.add_argument(
        "--min-value", type=int, default=5, help="keep rows with value_score >= this"
    )
    ap.add_argument(
        "--verified", default="2026-08-05", help="scouting date claimed by the input"
    )
    ap.add_argument(
        "--dry-run", action="store_true", help="report counts, write nothing"
    )
    args = ap.parse_args()

    if not args.source.is_file():
        print(f"error: {args.source} not found", file=sys.stderr)
        return 2

    routed, dropped, problems = load(args.source, args.min_value)
    if not routed:
        print(
            "error: nothing passed the filters — check --min-value and the input",
            file=sys.stderr,
        )
        return 1

    print(f"source: {args.source}")
    for label, n in dropped.most_common():
        print(f"  dropped {n:5d}  ({label})")
    print(f"  kept    {sum(len(v) for v in routed.values()):5d}")
    for filename in sorted(routed, key=lambda k: -len(routed[k])):
        print(f"    {filename:28s} {len(routed[filename]):5d}")
    for p in problems:
        print(f"  WARN {p}")

    if args.dry_run:
        return 0

    args.out.mkdir(parents=True, exist_ok=True)
    for filename, rows in routed.items():
        (args.out / filename).write_text(
            render(filename, rows, args.verified, args.min_value), encoding="utf-8"
        )
    (args.out / "INDEX.md").write_text(
        render_index(routed, args.verified, args.min_value), encoding="utf-8"
    )
    print(f"wrote {len(routed) + 1} files to {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
