name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: binex-prod
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build frontend
        run: |
          cd ui
          npm ci
          npm run build
          cp -r dist ../src/binex/ui/static

      - name: Build package
        run: |
          pip install build twine
          python -m build

      - name: Publish to TestPyPI (pre-release)
        if: github.event.release.prerelease
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: twine upload --repository-url https://test.pypi.org/legacy/ dist/*

      - name: Publish to PyPI
        if: "!github.event.release.prerelease"
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
