export type ProviderDef = {
  id: string;
  name: string;
  desc: string;
  authType: "oauth" | "api_key" | "none" | "custom";
  envKey?: string;
  oauthProvider?: "nous" | "openai-codex";
  svgIcon?: string;
  emoji?: string;
  placeholder?: string;
  helpText?: string;
  helpUrl?: string;
  recommended?: boolean;
  popular?: boolean;
  localModels?: boolean;
  privacyFirst?: boolean;
};

const PROVIDER_ICONS: Record<string, string> = {
  anthropic: "anthropic.svg",
  "openai-codex": "openai-codex.svg",
  openrouter: "openrouter.svg",
  ollama: "ollama.svg",
  gemini: "gemini.svg",
  xai: "xai.svg",
  "kimi-coding": "kimi-coding.svg",
  minimax: "minimax.svg",
  moonshot: "moonshot.svg",
  nvidia: "nvidia.svg",
  venice: "venice.svg",
  zai: "zai.svg",
  nous: "nous_portal.svg",
  deepseek: "deepseek.svg",
  huggingface: "huggingface.svg",
  kilocode: "kilocode.svg",
  alibaba: "alibaba_cloud.svg",
  xiaomi: "xiaomi_mimo.svg",
  "ai-gateway": "ai_gateway.svg",
  copilot: "github.svg",
  custom: "custom.svg",
};

export function resolveProviderIconUrl(providerId: string): string | undefined {
  const filename = PROVIDER_ICONS[providerId];
  if (!filename) return undefined;
  return new URL(
    `../../../../assets/ai-providers/${filename}`,
    import.meta.url,
  ).toString();
}

export const PROVIDERS: ProviderDef[] = [
  {
    id: "openrouter",
    name: "OpenRouter",
    desc: "API key required",
    authType: "api_key",
    envKey: "OPENROUTER_API_KEY",
    svgIcon: "openrouter",
    placeholder: "sk-or-...",
    helpText: "Get your API key from OpenRouter.",
    helpUrl: "https://openrouter.ai/keys",
    popular: true,
  },
  {
    id: "openai-codex",
    name: "OpenAI Codex",
    desc: "Free via ChatGPT Pro",
    authType: "oauth",
    oauthProvider: "openai-codex",
    svgIcon: "openai-codex",
    helpText: "Connect your ChatGPT account to use OpenAI Codex at no extra cost.",
    helpUrl: "https://openai.com/codex/",
    popular: true,
  },
  {
    id: "anthropic",
    name: "Anthropic",
    desc: "API key required",
    authType: "api_key",
    envKey: "ANTHROPIC_API_KEY",
    svgIcon: "anthropic",
    placeholder: "sk-ant-...",
    helpText: "Get your API key from the Anthropic Console.",
    helpUrl: "https://console.anthropic.com/settings/keys",
    recommended: true,
  },
  {
    id: "gemini",
    name: "Google AI Studio",
    desc: "API key required",
    authType: "api_key",
    envKey: "GOOGLE_API_KEY",
    svgIcon: "gemini",
    placeholder: "AI...",
    helpText: "Get your API key from Google AI Studio.",
    helpUrl: "https://aistudio.google.com/apikey",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    desc: "API key required",
    authType: "api_key",
    envKey: "DEEPSEEK_API_KEY",
    svgIcon: "deepseek",
    emoji: "🐋",
    placeholder: "sk-...",
    helpText: "Get your API key from the DeepSeek Platform.",
    helpUrl: "https://platform.deepseek.com/api_keys",
  },
  {
    id: "xai",
    name: "xAI",
    desc: "API key required",
    authType: "api_key",
    envKey: "XAI_API_KEY",
    svgIcon: "xai",
    placeholder: "xai-...",
    helpText: "Get your API key from the xAI Console.",
    helpUrl: "https://console.x.ai/",
  },
  {
    id: "copilot",
    name: "GitHub Copilot",
    desc: "API key required",
    authType: "api_key",
    envKey: "COPILOT_GITHUB_TOKEN",
    svgIcon: "copilot",
    emoji: "🐙",
    placeholder: "ghp_...",
    helpText: "Use your GitHub token to access Copilot models.",
    helpUrl: "https://github.com/settings/tokens",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    desc: "API key required",
    authType: "api_key",
    envKey: "HF_TOKEN",
    svgIcon: "huggingface",
    emoji: "🤗",
    placeholder: "hf_...",
    helpText: "Get your access token from Hugging Face.",
    helpUrl: "https://huggingface.co/settings/tokens",
  },
  {
    id: "zai",
    name: "Z.AI / GLM",
    desc: "API key required",
    authType: "api_key",
    envKey: "GLM_API_KEY",
    svgIcon: "zai",
    placeholder: "...",
    helpText: "Get your API key from the Z.AI platform.",
    helpUrl: "https://open.bigmodel.cn/usercenter/apikeys",
  },
  {
    id: "kimi-coding",
    name: "Kimi / Moonshot",
    desc: "API key required",
    authType: "api_key",
    envKey: "KIMI_API_KEY",
    svgIcon: "kimi-coding",
    placeholder: "sk-...",
    helpText: "Get your API key from the Moonshot AI platform.",
    helpUrl: "https://platform.moonshot.ai/console/api-keys",
  },
  {
    id: "minimax",
    name: "MiniMax",
    desc: "API key required",
    authType: "api_key",
    envKey: "MINIMAX_API_KEY",
    svgIcon: "minimax",
    placeholder: "...",
    helpText: "Get your API key from the MiniMax platform.",
    helpUrl: "https://platform.minimaxi.com/",
  },
  {
    id: "kilocode",
    name: "Kilo Code",
    desc: "API key required",
    authType: "api_key",
    envKey: "KILOCODE_API_KEY",
    svgIcon: "kilocode",
    emoji: "⚡",
    placeholder: "...",
    helpText: "Get your API key from Kilo Code.",
    helpUrl: "https://kilo.ai/",
  },
  {
    id: "alibaba",
    name: "Alibaba Cloud (DashScope)",
    desc: "API key required",
    authType: "api_key",
    envKey: "DASHSCOPE_API_KEY",
    svgIcon: "alibaba",
    emoji: "☁️",
    placeholder: "sk-...",
    helpText: "Get your API key from Alibaba Cloud DashScope.",
    helpUrl: "https://dashscope.console.aliyun.com/apiKey",
  },
  {
    id: "xiaomi",
    name: "Xiaomi MiMo",
    desc: "API key required",
    authType: "api_key",
    envKey: "XIAOMI_API_KEY",
    svgIcon: "xiaomi",
    emoji: "📱",
    placeholder: "...",
    helpText: "Get your API key from the Xiaomi MiMo platform.",
    helpUrl: "https://xiaomimimo.com/",
  },
  {
    id: "ai-gateway",
    name: "AI Gateway",
    desc: "API key required",
    authType: "api_key",
    envKey: "AI_GATEWAY_API_KEY",
    svgIcon: "ai-gateway",
    emoji: "🌐",
    placeholder: "...",
    helpText: "Get your API key from Vercel AI Gateway.",
    helpUrl: "https://ai-gateway.vercel.sh/",
  },
  {
    id: "nous",
    name: "Nous Portal",
    desc: "Free via OAuth",
    authType: "oauth",
    oauthProvider: "nous",
    svgIcon: "nous",
    emoji: "🔮",
    helpText: "Connect your Nous account to start using free hosted models.",
    helpUrl: "https://portal.nousresearch.com/",
  },
  {
    id: "ollama",
    name: "Ollama",
    desc: "Local models, no key needed",
    authType: "none",
    svgIcon: "ollama",
    placeholder: "ollama-api-key...",
    helpText: "Run models locally or point Hermes to your Ollama server.",
    helpUrl: "https://ollama.com/",
    localModels: true,
  },
  {
    id: "custom",
    name: "Custom (OpenAI-compat)",
    desc: "Any OpenAI-compatible endpoint",
    authType: "custom",
    svgIcon: "custom",
    emoji: "🔧",
    placeholder: "sk-...",
    helpText: "Configure any OpenAI-compatible API using your base URL and API key.",
  },
];
