// GENERATED by scripts/sync-upstream-baseline.mjs — do not edit by hand.
//
// Offline snapshot of the atomic-chat-conf backend manifest. `fetchRemoteBackends`
// parses it as a last resort when every network transport fails (ATO-243), so it
// deliberately carries real tags and backend ids: the download path keeps
// working, it is just older than the live manifest until the network recovers.
//
// Regenerate with `make sync-upstream-baseline` after the manifest moves. The
// tag here is NOT a pin — a live manifest on a newer tag is followed as-is.
import type { UpstreamManifest } from './backend'

export const BUNDLED_MANIFEST_BASELINE: UpstreamManifest = {
  tag_name: 'b10431',
  download_base: 'https://github.com/AtomicBot-ai/atomic-chat-conf/releases/download',
  assets: [
    { name: 'llama-b10431-bin-macos-arm64.tar.gz', sha256: 'a57fcf1808a3e05f34faa97cb6e77fce966af1140c8ebf6d65583a3f735f2507', size: 11193229 },
    { name: 'llama-b10431-bin-ubuntu-vulkan-x64.tar.gz', sha256: 'c953ae06ddf8305b20d754402c1ec07522b578500aad1935537005bcaacb80c9', size: 33004188 },
    { name: 'llama-b10431-bin-ubuntu-x64.tar.gz', sha256: '876757d3699f3332becb9cd76988b176a7de9531075c2fac58f242e014cf389f', size: 16618545 },
    { name: 'llama-b10431-bin-win-cpu-x64.zip', sha256: '631c8f7b237ca901e2b7b07680791a27c4fc23104f1640409e6c0e7c55f57fcf', size: 18853706 },
    { name: 'llama-b10431-bin-win-cuda-12.4-x64.zip', sha256: '394e12e9151080efe588ba2e6f3609cdfefd5f2f28b7382d784bbceaf32382c9', size: 250659321 },
    { name: 'llama-b10431-bin-win-cuda-13.3-x64.zip', sha256: 'b35f71eeb25c3891ae1ea6d28c6a474b1f79a7071785ee974addfd9c2f77fabc', size: 146578939 },
    { name: 'llama-b10431-bin-win-rocm-7.14-x64.zip', sha256: '7442913fa74b98c96f9fb54dcbee2e1cbe4e26ebcdc6bf3518bb8ec7832fa9cb', size: 196791416 },
    { name: 'llama-b10431-bin-win-vulkan-x64.zip', sha256: '17b7e5042b1da3e870963b7495c1fadb877e79892be2cc9a6b1e3c431639c4c0', size: 34442382 },
    { name: 'cudart-llama-bin-win-cuda-12.4-x64.zip' },
    { name: 'cudart-llama-bin-win-cuda-13.3-x64.zip' },
  ],
}
