%Doctor.Config{
  # Exclude generated DSL modules and implementation-only modules whose
  # `@moduledoc` is false. Public modules remain in the report.
  ignore_modules: [
    ~r/^Jidoka\.Agent\.Dsl(?:\.|$)/,
    ~r/^Jidoka\.Agent\.(ControlCompiler|RuntimeOptions|ServerOptions|SparkDsl|ToolSources)(?:\.|$)/,
    ~r/^Jidoka\.Agent\.Verifiers\./,
    ~r/^Jidoka\.AgentView\.(Events|Runner)$/,
    ~r/^Jidoka\.Adapter\.Jido\.(AgentServer|Browser)$/,
    ~r/^Jidoka\.Adapter\.ReqLLM\.(PromptAdapter|ResponseAdapter)$/,
    ~r/^Jidoka\.Adapter\.Runic\.(OperationBatch|LuaPlan|Workflow)(?:\.|$)/,
    ~r/^Jidoka\.Adapter\.Runic\.Background\.Executor$/,
    ~r/^Jidoka\.Application$/,
    ~r/^Jidoka\.Cancellation\.Token$/,
    ~r/^Jidoka\.Chat(?:\.Async)?$/,
    ~r/^Jidoka\.Chat\.RequestController$/,
    ~r/^Jidoka\.Debug\.Diagnostics$/,
    ~r/^Jidoka\.Error\.(Format|Normalize)(?:\.|$)/,
    ~r/^Jidoka\.Error\.Internal\.UnknownError$/,
    ~r/^Jidoka\.Extension\.Patch$/,
    ~r/^Jidoka\.Import\.(Controls|Decoder|Normalize|Registry|Tools)$/,
    ~r/^Jidoka\.Kino\./,
    ~r/^Jidoka\.Memory\.Runtime$/,
    ~r/^Jidoka\.Operation\.Source\.Catalog\.(Normalize|Parameters)$/,
    ~r/^Jidoka\.Operation\.Source\.MCP\.(Tools|Transport)$/,
    ~r/^Jidoka\.Portable$/,
    ~r/^Jidoka\.Projection\./,
    ~r/^Jidoka\.Review\.Approval$/,
    ~r/^Jidoka\.Runtime\.(CapabilityInvoker|Context|EffectTrace|EventDispatcher|OperationBatchCoordinator)$/,
    ~r/^Jidoka\.Runtime\.Controls\.Decision$/,
    ~r/^Jidoka\.Snapshot\.Codec$/,
    ~r/^Jidoka\.Session\.Execution\.Durability$/,
    ~r/^Jidoka\.Turn\.State\.OperationPlanner$/,
    ~r/^Jidoka\.Workflow\.(Codegen|Definition|Dsl|Graph|ParametersSchema|Resolver|Runtime|Schedule\.Cron|SparkDsl)(?:\.|$)/,
    ~r/^Jidoka\.Workflow\.Lua\.(CallTrace|Plan|Policy)(?:\.|$)/
  ],
  ignore_paths: [],
  min_module_doc_coverage: 50,
  min_module_spec_coverage: 50,
  min_overall_doc_coverage: 98,
  min_overall_moduledoc_coverage: 100,
  min_overall_spec_coverage: 98,
  exception_moduledoc_required: true,
  raise: false,
  reporter: Doctor.Reporters.Summary,
  struct_type_spec_required: true,
  umbrella: false
}
