/**
 * Serializes the shared json-render catalog (`src/lib/json-render/catalog.ts`)
 * into `src/apps/catalog.generated.json` at the repo root, so the API server's
 * page validator can check component types / prop shapes / action params
 * without importing SPA code (root src must not depend on the apps/ui build —
 * same rule as src/http/pages.ts's hand-mirrored action schemas, but generated
 * instead of duplicated).
 *
 * Run from apps/ui: `bun run generate:catalog-schema`. Commit the output.
 */

import { z } from "zod";
import { swarmCatalogSpec } from "../src/lib/json-render/catalog";

function toSchema(schema: z.ZodType): unknown {
  return z.toJSONSchema(schema, { target: "draft-7" });
}

const components: Record<string, unknown> = {};
for (const [name, def] of Object.entries(swarmCatalogSpec.components)) {
  components[name] = {
    description: def.description,
    ...("slots" in def && def.slots ? { slots: def.slots } : {}),
    props: toSchema(def.props),
  };
}

const actions: Record<string, unknown> = {};
for (const [name, def] of Object.entries(swarmCatalogSpec.actions)) {
  actions[name] = {
    description: def.description,
    params: toSchema(def.params),
  };
}

const artifact = {
  $comment:
    "GENERATED by apps/ui/scripts/generate-catalog-schema.ts — do not hand-edit. Regenerate with `cd apps/ui && bun run generate:catalog-schema`.",
  componentTypes: Object.keys(swarmCatalogSpec.components),
  actionTypes: Object.keys(swarmCatalogSpec.actions),
  components,
  actions,
};

const outUrl = new URL("../../../src/apps/catalog.generated.json", import.meta.url);
await Bun.write(outUrl, `${JSON.stringify(artifact, null, 2)}\n`);
// Root `bun run lint` covers the artifact — normalize to the root biome style.
const repoRoot = new URL("../../../", import.meta.url).pathname;
await Bun.$`bunx biome format --write ${outUrl.pathname}`.cwd(repoRoot);
console.log(`wrote ${outUrl.pathname}`);
