"""Iterated graph BFS on random trees (Branch 1 Result AN).

Per-example: random tree on V_BFS_TREE nodes (always connected, V-1 edges,
diameter ~log V to V-1 depending on shape). Target at loop r = bitmask of
nodes reachable in ≤ r hops from a chosen start.

Random tree generated by: permute nodes, then connect each new node to a
uniformly-chosen earlier node. Produces uniform-random labeled trees
(modulo permutation), with diameter typically O(sqrt(V)) to O(log V) but
sometimes O(V) (path graphs).

Why a tree: forces non-trivial BFS iteration past trained depth — diameter
larger than V=6 dense BFS (Result AM was too easy because diameter ~3
reached fixed point fast).
"""
from __future__ import annotations

import torch

from .data_chain import EQ, PAD, VOCAB_SIZE  # noqa: F401

V_BFS_TREE = 12
BFS_TREE_INPUT_LEN = V_BFS_TREE + V_BFS_TREE * V_BFS_TREE        # 12 + 144 = 156
BFS_TREE_SEQ_LEN = BFS_TREE_INPUT_LEN + 1 + V_BFS_TREE            # 156 + 1 + 12 = 169
BFS_TREE_OUTPUT_START = BFS_TREE_INPUT_LEN + 1                    # 157


def _random_tree_adj(batch_size: int, V: int, device: str) -> torch.Tensor:
    """Random tree on V nodes via Aldous-Broder–like construction:
    each new node i ∈ [1, V) attaches to a uniformly random node j ∈ [0, i).
    Returns symmetric adjacency [B, V, V] in {0,1}.
    """
    adj = torch.zeros((batch_size, V, V), dtype=torch.long, device=device)
    if V <= 1:
        return adj
    # For each node i in 1..V-1, pick parent j in [0, i)
    parents = torch.empty((batch_size, V - 1), dtype=torch.long, device=device)
    for i in range(V - 1):
        parents[:, i] = torch.randint(0, i + 1, (batch_size,), device=device)
    # Node i+1 connects to parents[i]
    bs = torch.arange(batch_size, device=device).unsqueeze(1).expand(-1, V - 1)
    children = torch.arange(1, V, device=device).unsqueeze(0).expand(batch_size, -1)
    adj[bs, children, parents] = 1
    adj[bs, parents, children] = 1
    return adj


def make_batch_bfs_tree_iter(batch_size: int, n_steps: int,
                               device: str = "cuda"
                               ) -> tuple[torch.Tensor, torch.Tensor]:
    """Returns (tokens, iter_targets):
      tokens       : [B, BFS_TREE_SEQ_LEN]
      iter_targets : [n_steps+1, B, V_BFS_TREE]
    """
    adj = _random_tree_adj(batch_size, V_BFS_TREE, device)
    start_idx = torch.randint(0, V_BFS_TREE, (batch_size,), device=device)
    initial = torch.zeros((batch_size, V_BFS_TREE), dtype=torch.long, device=device)
    initial.scatter_(1, start_idx.unsqueeze(1), 1)

    iters = [initial.clone()]
    cur = initial.clone()
    for _ in range(n_steps):
        reachable = (adj * cur.unsqueeze(1)).any(dim=-1).long()
        cur = (cur | reachable).long()
        iters.append(cur.clone())
    iter_targets = torch.stack(iters, dim=0)

    tokens = torch.full((batch_size, BFS_TREE_SEQ_LEN), PAD,
                         dtype=torch.long, device=device)
    tokens[:, :V_BFS_TREE] = initial
    tokens[:, V_BFS_TREE:V_BFS_TREE + V_BFS_TREE * V_BFS_TREE] = adj.reshape(batch_size, -1)
    tokens[:, BFS_TREE_INPUT_LEN] = EQ
    return tokens, iter_targets
