"""Self-edit analogue: **Gödel Agent** (Arvid-pku/Godel_Agent@bbb50879).

Preserved: the artifact owns both the solve prompt and the
**self-improvement prompt** -- each proposal is generated by the artifact's own
current ``self_improvement_prompt`` applied to its own source, which is the
recursive self-reference the paper is about.

Deliberate substitution, stated as such: **upstream has no acceptance gate at
all** -- monkey-patched edits are kept unless they crash, and recovery is
error-triggered only (the paper reports 92% of trials dipping before
improving). This study's premise is measuring methods under the framework
gate, so the gate stays; it is a substitution, not a preserved mechanism.
``--gateless`` runs the faithful variant: any compiling edit is accepted.
"""

from __future__ import annotations

from typing import Optional

from agentdescent.evolution import Task
from agentdescent.policies import AcceptDecision, Policies

from examples._measure import extract_python
from examples._method_policy import MethodPolicy, ValidatedSlot
from examples._method_runner import standard_main
from examples._gsmhard_domain import (feedback, gsmhard_reward,
                                      gsmhard_splits)
from examples.sica.sica_self_edit import compile_policy, policy_prompt


FIDELITY = "self_edit_analogue"

GODEL_INITIAL_SOURCE = '''def solve_prompt(question):
    return "Solve the arithmetic problem carefully. Return only the final answer.\\n\\n" + question

def self_improvement_prompt(source, feedback):
    return "Inspect and improve your complete policy source. Feedback:\\n" + feedback + "\\n\\nSource:\\n" + source
'''

_SURFACE = {"solve_prompt": 1, "self_improvement_prompt": 2}


class AcceptAnyCompiling:
    """Gödel Agent's actual acceptance rule: keep every edit that runs.

    Compilation already happened in the strategy's validator, so by the time a
    candidate reaches this gate it is exactly the upstream situation -- a
    monkey-patch that did not crash -- and it is accepted unconditionally.
    """

    def accept(self, ctx) -> AcceptDecision:
        return AcceptDecision(accept=True, detail="gateless: compiling edit kept")


def _godel_source(text: str) -> str:
    source = extract_python(text)
    compile_policy(source, _SURFACE)
    return source.strip() + "\n"


def build(seed: int, *, gateless: bool = False) -> MethodPolicy:
    def solve(llm, rendered: str, task: Task) -> str:
        functions = compile_policy(rendered, _SURFACE)
        return llm(policy_prompt(functions["solve_prompt"], task), unit=task.id)

    def propose(llm, rendered: str, task: Task, output: str,
                reward: float) -> Optional[str]:
        functions = compile_policy(rendered, _SURFACE)
        improvement = functions["self_improvement_prompt"](
            rendered, feedback(task, output))
        return llm(
            (
                f"{improvement}\n\nReward: {reward}\n"
                "Recursively improve either or both functions while preserving "
                "exactly solve_prompt(question) and self_improvement_prompt("
                "source, feedback). Each has one return expression using only "
                "string constants, +, and its arguments. No imports, calls, "
                "assignments, attributes, or comments. Return complete Python "
                "source only."
            ),
            unit=task.id,
        )

    train, held_out, test = gsmhard_splits(seed)
    return MethodPolicy(
        name="godel_agent",
        fidelity=FIDELITY,
        notes=(
            "The artifact owns both solve and self-improvement prompt functions; each proposal is produced by the artifact's own current self-improvement prompt.",
            "Upstream is gateless (edits kept unless they crash); the held-out gate here is a deliberate substitution, not a preserved mechanism. --gateless runs the faithful accept-any-compiling variant -- a flag five documents described and the parser rejected until it was wired.",
            "An unparseable self-edit costs its candidate and produces no diff; there is no substitute source.",
            "AST-gated replacement stands in for monkey-patching the full scaffold.",
        ),
        strategy=ValidatedSlot(initial_value=GODEL_INITIAL_SOURCE,
                               validator=_godel_source),
        train_tasks=tuple(train),
        held_out_tasks=tuple(held_out),
        test_tasks=tuple(test),
        solve=solve,
        propose=propose,
        reward=gsmhard_reward,
        proposal_calls_per_candidate=1,
        engine=(Policies(acceptance=AcceptAnyCompiling()) if gateless
                else Policies()),
        reflective=True,
    )


def _gateless_flag(parser) -> None:
    parser.add_argument(
        "--gateless",
        action="store_true",
        help=("run the faithful variant: every edit that compiles is kept, as "
              "upstream keeps every monkey-patch that does not crash. The "
              "default installs the framework's held-out gate instead, which is "
              "a deliberate substitution rather than a preserved mechanism -- "
              "this study measures methods under that gate"))


def main(argv=None) -> int:
    return standard_main(build, argv, extra_args=_gateless_flag,
                         build_kwargs=lambda args: {"gateless": args.gateless})


if __name__ == "__main__":
    raise SystemExit(main())
