"""Customer countersignature flow for air-gap wheelhouses.

Bernstein already signs every wheel + the manifest with cosign (the org
signature). A sovereign customer who refuses to deploy code signed only
by an upstream vendor needs a second signature that *they* control --
applied inside their perimeter, before the bundle reaches the
production network.

This module implements that two-key chain:

1. **Org signature** (existing) -- cosign over each wheel + the
   manifest. Signed by Bernstein's release pipeline.
2. **Customer signature** (new, this module) -- detached Ed25519 over
   ``MANIFEST.json``. Generated by the customer's compliance team via
   ``bernstein wheelhouse countersign`` with their own key. Verified
   by ``bernstein verify`` against the
   ``.bernstein/trust/customer-keys/`` allowlist on the deploy host.

File layout in the bundle::

    <bundle>/MANIFEST.json
    <bundle>/MANIFEST.sig            -- org cosign signature
    <bundle>/<wheel>.whl
    <bundle>/<wheel>.whl.sig         -- org cosign signature per-wheel
    <bundle>/MANIFEST.customer.sig   -- customer Ed25519 signature (NEW)
    <bundle>/MANIFEST.customer.json  -- which org/key produced it (NEW)

Why sign only the manifest, not every wheel?
    The manifest already pins each wheel's sha256. A signature over
    ``MANIFEST.json`` therefore transitively covers every wheel: any
    tampered wheel changes its hash, the manifest no longer matches,
    and the existing per-wheel sha256 check fails before the
    countersignature is even looked at. Signing one file instead of
    N files keeps the customer's signing ceremony fast (single
    ``cryptography``-or-``cosign`` call) and the verifier path simple.

Trust store
-----------
The deploy host's ``.bernstein/trust/customer-keys/`` directory is a
flat directory of PEM-encoded Ed25519 public keys. Each file maps to
one allowed signer; the filename sans suffix is the org name printed
in verify output. The verifier accepts the bundle if at least one key
in the directory validates the signature -- multiple keys are allowed
so a customer who rotates keys (or has multiple compliance officers)
does not need to overwrite the file.
"""

from __future__ import annotations

import base64
import json
from dataclasses import dataclass
from pathlib import Path

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)

# Filenames are well-known so a customer's compliance pipeline can
# generate / verify them without invoking Bernstein code.
CUSTOMER_SIG_FILENAME = "MANIFEST.customer.sig"
CUSTOMER_META_FILENAME = "MANIFEST.customer.json"
DEFAULT_TRUST_DIR = Path(".bernstein/trust/customer-keys")


class CustomerCountersignError(RuntimeError):
    """Raised on countersign / verify input errors (bad key, bad bundle)."""


@dataclass(frozen=True)
class CustomerSignature:
    """Single customer countersignature row materialised on disk."""

    org_name: str
    """Human-readable org / key id (filename of the trusted public key)."""

    sig_bytes: bytes
    """Raw Ed25519 detached signature over ``MANIFEST.json`` bytes."""

    public_key_pem: bytes
    """PEM-encoded public key (for the metadata sidecar)."""


@dataclass(frozen=True)
class CustomerVerifyOutcome:
    """One row in the customer-signature verify pass."""

    present: bool
    """True iff ``MANIFEST.customer.sig`` exists alongside the manifest."""

    valid: bool | None
    """True/False/None. ``None`` means "no trust store / no sig to check"."""

    matched_org: str | None
    """Filename (sans suffix) of the trust-store key that validated."""

    error: str = ""
    """Human-readable failure detail; empty on success."""


def _load_private_key(key_path: Path) -> Ed25519PrivateKey:
    """Load a PEM PKCS#8 or raw 32-byte Ed25519 private key from *key_path*."""
    if not key_path.exists():
        raise CustomerCountersignError(f"customer key not found: {key_path}")
    data = key_path.read_bytes()
    if data.lstrip().startswith(b"-----BEGIN"):
        try:
            private_key = serialization.load_pem_private_key(data, password=None)
        except (ValueError, TypeError) as exc:
            raise CustomerCountersignError(f"invalid PEM private key {key_path}: {exc}") from exc
        if not isinstance(private_key, Ed25519PrivateKey):
            raise CustomerCountersignError(f"private key {key_path} is not Ed25519")
        return private_key
    raw = data.strip() if len(data) > 32 else data
    if len(raw) != 32:
        raise CustomerCountersignError(
            f"raw Ed25519 private key must be 32 bytes (got {len(raw)} from {key_path})",
        )
    try:
        return Ed25519PrivateKey.from_private_bytes(raw)
    except ValueError as exc:
        raise CustomerCountersignError(f"cannot load raw Ed25519 key from {key_path}: {exc}") from exc


def _load_public_key(key_path: Path) -> Ed25519PublicKey:
    """Load a PEM or raw 32-byte Ed25519 public key from *key_path*."""
    if not key_path.exists():
        raise CustomerCountersignError(f"public key not found: {key_path}")
    data = key_path.read_bytes()
    if data.lstrip().startswith(b"-----BEGIN"):
        try:
            public_key = serialization.load_pem_public_key(data)
        except ValueError as exc:
            raise CustomerCountersignError(f"invalid PEM public key {key_path}: {exc}") from exc
        if not isinstance(public_key, Ed25519PublicKey):
            raise CustomerCountersignError(f"public key {key_path} is not Ed25519")
        return public_key
    raw = data.strip() if len(data) > 32 else data
    if len(raw) != 32:
        raise CustomerCountersignError(
            f"raw Ed25519 public key must be 32 bytes (got {len(raw)} from {key_path})",
        )
    return Ed25519PublicKey.from_public_bytes(raw)


def countersign_bundle(
    bundle_path: Path,
    *,
    customer_key_path: Path,
    org_name: str | None = None,
    out_path: Path | None = None,
) -> Path:
    """Append a customer Ed25519 signature to *bundle_path*.

    Reads ``MANIFEST.json`` from the bundle, signs the bytes with the
    customer's Ed25519 private key, and writes the detached signature to
    ``MANIFEST.customer.sig`` plus a metadata sidecar
    (``MANIFEST.customer.json``) describing which org produced the
    signature.

    The sidecar carries the PEM-encoded public key so the verifier on
    a different host can pin the trust without out-of-band key
    distribution. The trust store on the deploy host is still the
    primary trust anchor -- the sidecar is informational.

    Args:
        bundle_path: Path to the wheelhouse directory.
        customer_key_path: Path to the customer's Ed25519 PRIVATE key
            (PEM PKCS#8 or raw 32 bytes).
        org_name: Logical org name embedded in the sidecar metadata.
            Defaults to the key file's stem.
        out_path: Optional override for the bundle directory the
            customer-signed copy lands in. Defaults to *bundle_path*
            (in-place countersign).

    Returns:
        Path to the signature file (``MANIFEST.customer.sig``).

    Raises:
        CustomerCountersignError: When the bundle layout is invalid or
            the key cannot be loaded.
    """
    if not bundle_path.is_dir():
        raise CustomerCountersignError(f"bundle is not a directory: {bundle_path}")
    manifest_path = bundle_path / "MANIFEST.json"
    if not manifest_path.exists():
        raise CustomerCountersignError(f"missing MANIFEST.json in bundle: {bundle_path}")

    private_key = _load_private_key(customer_key_path)
    manifest_bytes = manifest_path.read_bytes()
    sig_bytes = private_key.sign(manifest_bytes)

    target_dir = out_path or bundle_path
    if out_path is not None and out_path != bundle_path:
        # Mirror the bundle into the destination so the customer-signed
        # copy is self-contained.
        target_dir.mkdir(parents=True, exist_ok=True)
        for entry in bundle_path.iterdir():
            if entry.is_file():
                (target_dir / entry.name).write_bytes(entry.read_bytes())

    sig_path = target_dir / CUSTOMER_SIG_FILENAME
    sig_path.write_bytes(sig_bytes)

    public_pem = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    meta = {
        "org_name": org_name or customer_key_path.stem,
        "alg": "EdDSA",
        "manifest_sha256_covered_by": "MANIFEST.json bytes (verbatim)",
        "public_key_pem": public_pem.decode("ascii"),
        "signature_b64": base64.b64encode(sig_bytes).decode("ascii"),
    }
    (target_dir / CUSTOMER_META_FILENAME).write_text(
        json.dumps(meta, indent=2, sort_keys=True) + "\n",
    )
    return sig_path


def load_trust_store(trust_dir: Path) -> dict[str, Ed25519PublicKey]:
    """Return a mapping of ``org_name -> Ed25519PublicKey`` from *trust_dir*.

    Each file in *trust_dir* whose suffix is ``.pem`` (or absent) and
    whose contents parse as an Ed25519 public key contributes one
    allowed signer. The org name is the file stem -- ``acme.pem`` is
    the org ``acme``.

    Returns an empty mapping when *trust_dir* does not exist; callers
    treat that as "no trust store configured" and apply the
    ``require_customer_sig`` policy.
    """
    if not trust_dir.exists() or not trust_dir.is_dir():
        return {}
    out: dict[str, Ed25519PublicKey] = {}
    for entry in sorted(trust_dir.iterdir()):
        if not entry.is_file():
            continue
        if entry.suffix not in {".pem", ".pub", ""}:
            continue
        try:
            public_key = _load_public_key(entry)
        except CustomerCountersignError:
            # Bad keys in the trust store get skipped silently rather
            # than fail the verify -- compliance teams sometimes drop
            # README.txt files in there. The verifier path will still
            # report "no matching trust key" which surfaces cleanly.
            continue
        out[entry.stem] = public_key
    return out


def verify_customer_signature(
    bundle_path: Path,
    *,
    trust_dir: Path | None = None,
) -> CustomerVerifyOutcome:
    """Validate ``MANIFEST.customer.sig`` against the trust store.

    Returns a structured outcome rather than raising so the wheelhouse
    verifier can render it alongside the org-signature outcome on the
    same report.

    Logic:

    * If neither the signature file nor the trust store exist, return
      ``CustomerVerifyOutcome(present=False, valid=None)`` -- the
      wheelhouse-level ``require_customer_sig`` flag decides whether
      that is a failure.
    * If the signature file is present but the trust store is empty,
      return ``valid=None`` with an explanatory error -- the operator
      configured a countersign without a way to verify it, which is a
      misconfiguration.
    * If both exist, walk every key in the trust store and accept the
      first match; ``matched_org`` records which key validated.
    """
    manifest_path = bundle_path / "MANIFEST.json"
    sig_path = bundle_path / CUSTOMER_SIG_FILENAME
    if not manifest_path.exists():
        return CustomerVerifyOutcome(
            present=False,
            valid=None,
            matched_org=None,
            error="missing MANIFEST.json",
        )
    if not sig_path.exists():
        return CustomerVerifyOutcome(present=False, valid=None, matched_org=None)

    resolved_trust_dir = trust_dir if trust_dir is not None else DEFAULT_TRUST_DIR
    trust = load_trust_store(resolved_trust_dir)
    if not trust:
        return CustomerVerifyOutcome(
            present=True,
            valid=None,
            matched_org=None,
            error=(
                f"customer signature present but no trust keys in {resolved_trust_dir}; "
                "drop a PEM Ed25519 public key in that directory to enable validation"
            ),
        )

    manifest_bytes = manifest_path.read_bytes()
    sig_bytes = sig_path.read_bytes()
    for org_name, public_key in trust.items():
        try:
            public_key.verify(sig_bytes, manifest_bytes)
        except InvalidSignature:
            continue
        return CustomerVerifyOutcome(present=True, valid=True, matched_org=org_name)

    return CustomerVerifyOutcome(
        present=True,
        valid=False,
        matched_org=None,
        error=f"no key in {resolved_trust_dir} validates the customer signature ({len(trust)} keys tried)",
    )


__all__ = [
    "CUSTOMER_META_FILENAME",
    "CUSTOMER_SIG_FILENAME",
    "DEFAULT_TRUST_DIR",
    "CustomerCountersignError",
    "CustomerSignature",
    "CustomerVerifyOutcome",
    "countersign_bundle",
    "load_trust_store",
    "verify_customer_signature",
]
