"""Sigstore-attestation verifier for release artefacts.

This module verifies Sigstore-based build-provenance attestations
generated by the GitHub-Actions ``actions/attest-build-provenance``
workflow on each tagged release. The on-disk artefact (a wheel, an
sdist, or any byte blob) carries no separate ``.sig`` file in this
flow -- the attestation lives in the Sigstore transparency log keyed
by the artefact's sha256 digest. Verification therefore happens via
the official ``gh attestation verify`` CLI, which:

* downloads the matching attestation from the GitHub attestations
  endpoint (online mode), or reads an attestation bundle from disk
  (offline mode via ``--bundle``);
* re-checks the Sigstore certificate chain (Fulcio CA), the inclusion
  proof in the public Rekor transparency log, and the OIDC identity
  that issued the keyless certificate; and
* exits zero only when every check passes against the expected
  ``--owner`` (and optionally a specific ``--repo``).

Design constraints:

* Pure subprocess wrapper -- no fancy SDK in the runtime path so the
  runtime closure stays small and the air-gap wheelhouse keeps
  working for customers who never opt into Sigstore.
* The verifier is additive: the default ``bernstein verify
  <wheelhouse>`` flow keeps cosign/GPG/PEM-key behaviour unchanged.
  Sigstore is opt-in via the ``--sigstore`` flag in the CLI, and the
  pluggable :class:`bernstein.core.distribution.WheelhouseVerifier`
  protocol lets it run after / alongside the existing verifiers.
* Honest failure modes: when ``gh`` is unavailable on the host, when
  the network is unavailable to fetch the attestation, or when the
  artefact has no attestation at all, we surface the cause in the
  returned :class:`SigstoreVerifyOutcome` instead of pretending
  verification passed.

The module pairs with the workflow change in
``.github/workflows/publish.yml`` (and ``auto-release.yml``) where
``actions/attest-build-provenance@v2`` produces the attestation on
every published release artefact.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

# Default repository owner used by ``gh attestation verify --owner``.
# This matches the GitHub org that hosts the Bernstein release flow.
DEFAULT_OWNER = "sipyourdrink-ltd"

# Default subprocess timeout in seconds. ``gh attestation verify`` makes
# a small number of HTTPS calls; 60 s is well above the p99 latency we
# saw against the public attestations endpoint while leaving headroom
# for slow CI runners.
DEFAULT_TIMEOUT_S = 60


@dataclass(frozen=True)
class SigstoreVerifyOutcome:
    """Result of one ``gh attestation verify`` invocation against an artefact.

    Attributes:
        artefact: Path of the file that was verified.
        ok: True iff the GH CLI exited 0 and the attestation matched
            the expected owner / repo. ``None`` means the check was
            skipped (e.g. ``gh`` missing, network unavailable, or the
            artefact has no attestation and the caller did not require
            one). ``False`` means a hard failure -- the artefact has
            an attestation but it did not validate.
        reason: Human-readable explanation. Always set; on success it
            states which verifier path ran ("gh-attestation-verify")
            and which owner was checked.
        gh_stdout: Raw stdout from ``gh``. Empty when not run.
        gh_stderr: Raw stderr from ``gh``. Empty when not run.
    """

    artefact: Path
    ok: bool | None
    reason: str
    gh_stdout: str = ""
    gh_stderr: str = ""


@dataclass
class SigstoreAttestationVerifier:
    """Verifier that delegates to the ``gh`` CLI's attestation subcommand.

    Two configurations are supported:

    * Online (default): ``offline=False``. ``gh`` reaches the GitHub
      attestations endpoint to fetch the matching bundle keyed on the
      artefact's sha256 digest, then re-verifies the Sigstore chain.
    * Offline: ``offline=True`` plus ``bundle_dir`` pointing at a
      directory of pre-downloaded ``*.sigstore`` bundles. ``gh
      attestation verify --bundle`` re-validates the bundle without a
      network call. This is the air-gap-friendly path and is the same
      bundle format ``gh attestation download`` produces.

    The verifier never raises on a missing ``gh`` binary or a network
    error. It returns a :class:`SigstoreVerifyOutcome` with ``ok=None``
    so the caller can decide whether to fail closed (strict mode) or
    treat the result as advisory (default mode).
    """

    owner: str = DEFAULT_OWNER
    repo: str | None = None
    offline: bool = False
    bundle_dir: Path | None = None
    timeout_s: int = DEFAULT_TIMEOUT_S
    name: str = "sigstore"

    def available(self) -> bool:
        """Return True iff ``gh`` is on PATH.

        We do not probe authentication or network reachability here --
        that surfaces as a graceful failure via the verify call.
        """
        return shutil.which("gh") is not None

    def verify(self, blob: Path) -> SigstoreVerifyOutcome:
        """Verify a single artefact via ``gh attestation verify``.

        Returns:
            :class:`SigstoreVerifyOutcome` with ``ok`` set to True / False
            on a definitive answer, or None when the check was skipped
            for an honest reason (no ``gh`` binary, no bundle for this
            artefact in offline mode, etc.).
        """
        if not blob.exists():
            return SigstoreVerifyOutcome(
                artefact=blob,
                ok=False,
                reason=f"artefact does not exist: {blob}",
            )

        gh = shutil.which("gh")
        if gh is None:
            return SigstoreVerifyOutcome(
                artefact=blob,
                ok=None,
                reason="gh CLI not on PATH -- skipping Sigstore verify",
            )

        cmd: list[str] = [gh, "attestation", "verify", str(blob), "--owner", self.owner]
        if self.repo:
            cmd += ["--repo", self.repo]
        if self.offline:
            bundle = self._resolve_bundle(blob)
            if bundle is None:
                return SigstoreVerifyOutcome(
                    artefact=blob,
                    ok=None,
                    reason=("offline mode: no .sigstore bundle alongside artefact or in --bundle-dir"),
                )
            cmd += ["--bundle", str(bundle)]

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=self.timeout_s,
                check=False,
            )
        except FileNotFoundError:
            return SigstoreVerifyOutcome(
                artefact=blob,
                ok=None,
                reason="gh CLI vanished mid-verify -- skipping",
            )
        except subprocess.TimeoutExpired:
            return SigstoreVerifyOutcome(
                artefact=blob,
                ok=None,
                reason=(
                    f"gh attestation verify timed out after {self.timeout_s}s -- "
                    "network unavailable, treating as skipped"
                ),
            )

        if result.returncode == 0:
            return SigstoreVerifyOutcome(
                artefact=blob,
                ok=True,
                reason=f"gh-attestation-verify (owner={self.owner})",
                gh_stdout=result.stdout,
                gh_stderr=result.stderr,
            )

        # Distinguish "no attestation found" (skipped) from "attestation
        # found but invalid" (hard failure). gh prints distinctive text
        # for the no-attestation case; everything else is a real failure.
        merged = (result.stdout + result.stderr).lower()
        if "no attestations" in merged or "no matching attestations" in merged:
            return SigstoreVerifyOutcome(
                artefact=blob,
                ok=None,
                reason="no Sigstore attestation found for this artefact",
                gh_stdout=result.stdout,
                gh_stderr=result.stderr,
            )

        return SigstoreVerifyOutcome(
            artefact=blob,
            ok=False,
            reason=f"gh attestation verify failed (rc={result.returncode})",
            gh_stdout=result.stdout,
            gh_stderr=result.stderr,
        )

    def _resolve_bundle(self, blob: Path) -> Path | None:
        """Locate an offline ``.sigstore`` bundle for *blob*.

        The lookup order matches the ``gh attestation download`` layout:
        first a sibling ``<artefact>.sigstore`` next to the artefact,
        then ``<bundle_dir>/<artefact-name>.sigstore`` when the operator
        configured an explicit bundle directory.
        """
        sibling = blob.with_suffix(blob.suffix + ".sigstore")
        if sibling.exists():
            return sibling
        if self.bundle_dir is not None:
            candidate = self.bundle_dir / f"{blob.name}.sigstore"
            if candidate.exists():
                return candidate
        return None


@dataclass(frozen=True)
class SigstoreBatchReport:
    """Aggregate outcome across every artefact in a wheelhouse.

    Attributes:
        verifier_available: True iff the ``gh`` binary was found on
            PATH and we attempted at least one verify call.
        outcomes: Per-artefact rows in the order they were processed.
        ok: True iff every outcome ended in ``ok=True`` (no failures
            and no skips). False on any hard failure. ``None`` means
            no failures but at least one skip -- the caller decides.
        failures: Human-readable failure reasons -- one line per
            offending artefact.
        skips: Human-readable skip reasons.
        passes: Number of artefacts whose attestation validated.
    """

    verifier_available: bool
    outcomes: tuple[SigstoreVerifyOutcome, ...]
    ok: bool | None
    failures: tuple[str, ...]
    skips: tuple[str, ...]
    passes: int


def verify_artefacts_with_sigstore(
    artefacts: list[Path],
    *,
    verifier: SigstoreAttestationVerifier | None = None,
    require_attestation: bool = False,
) -> SigstoreBatchReport:
    """Run :class:`SigstoreAttestationVerifier` over a batch of artefacts.

    Args:
        artefacts: Files to verify (typically every wheel + the sdist
            in a release bundle).
        verifier: Pre-configured verifier; defaults to one targeting
            the canonical ``DEFAULT_OWNER``.
        require_attestation: When True, a missing attestation (the
            ``ok=None`` case) is promoted to a hard failure. Use this
            in strict CI / compliance modes where every release artefact
            must carry provenance.

    Returns:
        :class:`SigstoreBatchReport` -- aggregated outcome the CLI
        renders into operator-facing output.
    """
    v = verifier or SigstoreAttestationVerifier()
    if not v.available():
        return SigstoreBatchReport(
            verifier_available=False,
            outcomes=(),
            ok=None if not require_attestation else False,
            failures=(("gh CLI not on PATH",) if require_attestation else ()),
            skips=(("gh CLI not on PATH",) if not require_attestation else ()),
            passes=0,
        )

    outcomes: list[SigstoreVerifyOutcome] = []
    failures: list[str] = []
    skips: list[str] = []
    passes = 0
    for artefact in artefacts:
        outcome = v.verify(artefact)
        outcomes.append(outcome)
        if outcome.ok is True:
            passes += 1
        elif outcome.ok is False:
            failures.append(f"{artefact.name}: {outcome.reason}")
        else:
            if require_attestation:
                failures.append(f"{artefact.name}: {outcome.reason}")
            else:
                skips.append(f"{artefact.name}: {outcome.reason}")

    if failures:
        ok: bool | None = False
    elif skips:
        ok = None
    else:
        ok = True

    return SigstoreBatchReport(
        verifier_available=True,
        outcomes=tuple(outcomes),
        ok=ok,
        failures=tuple(failures),
        skips=tuple(skips),
        passes=passes,
    )
