"""Per-installation service token — shared resolution logic.

One random token, generated by `atlas init`, stored at
`<root>/secrets/service-token` (file 0600, dir 0700), authenticates
internal service-to-service and CLI-to-service requests as
`Authorization: Bearer <token>`.

Resolution order (first hit wins):
  1. ATLAS_SERVICE_TOKEN_FILE — explicit path (containers use the
     read-only mount /run/atlas-secrets/service-token)
  2. <repo root>/secrets/service-token — the host-side default

Absent/unreadable file => "" => auth disabled (services accept
unauthenticated requests; `atlas doctor` warns). The token value is
never logged, never placed in argv, never written to .env, and never
included in diagnostics.
"""

import os
import stat
import urllib.request
from typing import Optional, Tuple

from atlas.env import atlas_root as _find_root

DEFAULT_RELATIVE_PATH = os.path.join("secrets", "service-token")
CONTAINER_PATH = "/run/atlas-secrets/service-token"
HEADER = "Authorization"


def token_path(atlas_root: Optional[str] = None) -> str:
    explicit = os.environ.get("ATLAS_SERVICE_TOKEN_FILE", "").strip()
    if explicit:
        return explicit
    root = atlas_root or _find_root()
    return os.path.join(root, DEFAULT_RELATIVE_PATH)


def read_token(atlas_root: Optional[str] = None) -> str:
    """The installation token, or "" when unconfigured."""
    path = token_path(atlas_root)
    try:
        with open(path) as fh:
            return fh.read().strip()
    except OSError:
        return ""


def auth_headers(atlas_root: Optional[str] = None) -> dict:
    """Headers dict to merge into internal requests ({} when no token)."""
    tok = read_token(atlas_root)
    if not tok:
        return {}
    return {HEADER: f"Bearer {tok}"}


def check_file_permissions(atlas_root: Optional[str] = None
                           ) -> Tuple[bool, str]:
    """(ok, detail) — detail never contains the token value."""
    path = token_path(atlas_root)
    if not os.path.isfile(path):
        return False, f"no service token at {path} — internal auth disabled"
    mode = stat.S_IMODE(os.stat(path).st_mode)
    if mode & 0o077:
        return False, (f"{path} has loose permissions ({oct(mode)}); "
                       f"expected 0600 — run `chmod 600 {path}`")
    parent_mode = stat.S_IMODE(os.stat(os.path.dirname(path)).st_mode)
    if parent_mode & 0o077:
        return False, (f"{os.path.dirname(path)} has loose permissions "
                       f"({oct(parent_mode)}); expected 0700")
    return True, f"service token present at {path} (0600)"


def install_urllib_opener(atlas_root: Optional[str] = None) -> None:
    """Global opener so every CLI urllib call site (client, doctor,
    lens, events, runtime, onboard) sends the token. urllib merges
    addheaders under explicit per-request headers, so requests that
    set their own Authorization keep it. No-op without a token."""
    tok = read_token(atlas_root)
    if not tok:
        return
    opener = urllib.request.build_opener()
    opener.addheaders = [(HEADER, f"Bearer {tok}")]
    urllib.request.install_opener(opener)
