"""
demo/templates.py — HTML gallery builder for the multi-agent demo.

Ported from google-gemma/cookbook's build_page(). Kept separate from
demo/scenarios.py so scenario definitions stay focused on prompts and per-card
rendering, while this module owns the final page layout + Tailwind/Inter
boilerplate.
"""

from __future__ import annotations

from typing import Any


def build_page(
    topic: str,
    scenario: dict[str, Any],
    results: dict[str, str],
    tasks: list[dict] | None = None,
) -> str:
    """Render all per-agent cards into a single static HTML page."""
    agents: list[dict] = scenario["agents"]
    title: str = scenario["title"]
    render_card = scenario["render_card"]
    extra_head: str = scenario.get("extra_head", "")
    extra_body: str = scenario.get("extra_body", "")

    task_map: dict[str, dict] = {}
    if tasks:
        for task in tasks:
            task_map[task.get("name", "")] = task

    cards_html: list[str] = []
    for agent in agents:
        result = results.get(agent["name"], "")
        task = task_map.get(agent["name"])
        inner = render_card(agent, result, task)
        cards_html.append(
            '            <div class="bg-gray-50 rounded-lg p-4 border border-gray-200 '
            'hover:shadow-md transition-all">\n'
            f"{inner}\n"
            "            </div>"
        )

    newline = "\n"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
        body {{ font-family: 'Inter', sans-serif; }}
        svg {{ width: 100%; height: 100%; }}
    </style>
{extra_head}
</head>
<body class="bg-white text-gray-900 min-h-screen">
    <div class="mx-auto px-8 py-16" style="max-width: 1920px;">
        <h1 class="text-4xl font-bold text-center mb-2 text-gray-900">
            {title}
        </h1>
        <p class="text-center text-gray-500 text-base mb-12">{topic}</p>
        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
{newline.join(cards_html)}
        </div>
        <p class="text-center text-gray-400 text-xs mt-12 tracking-wide uppercase">
            Generated by {len(agents)} concurrent Atomic-Chat agents
        </p>
    </div>
{extra_body}
</body>
</html>"""
