"""Scaffold template registry and rendering.

A scaffold template is a small, deterministic recipe: a tuple of files plus
the keywords that route a free-form prompt to it. Rendering is a plain
string-template ``$placeholder`` substitution - no Jinja, no LLM, no I/O
beyond writing the rendered files.

Three template families ship today, one per common stack shape:

* ``python-cli`` - pyproject.toml + entrypoint + README.
* ``node-cli``   - package.json + entrypoint + README.
* ``static-site`` - index.html + style.css + README.

Richer scaffolds (Next.js + SQLite, FastAPI + React, Streamlit) and a
multi-stage flow plug into this same registry as follow-ups.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path  # noqa: TC003 - used at runtime in materialize_template
from string import Template


@dataclass(frozen=True)
class ScaffoldFile:
    """One file produced by a scaffold template.

    Attributes:
        relative_path: POSIX-style path relative to the scaffold output
            directory (e.g. ``"src/main.py"``).
        content: File body. Substrings of the form ``$placeholder`` are
            substituted at render time using ``string.Template``.
    """

    relative_path: str
    content: str


@dataclass(frozen=True)
class ScaffoldTemplate:
    """Immutable description of one scaffold template.

    Attributes:
        name: Stable lookup key (e.g. ``"python-cli"``).
        description: Short human-readable summary for ``--help`` output.
        keywords: Lower-case tokens used by :func:`pick_template` to route
            free-form prompts. Order matters only for tie-breaking.
        files: Files materialised on disk, in deterministic order.
    """

    name: str
    description: str
    keywords: tuple[str, ...]
    files: tuple[ScaffoldFile, ...]


class ScaffoldError(RuntimeError):
    """Raised on user-facing scaffold errors (target dir not empty, etc.)."""


# ---------------------------------------------------------------------------
# Built-in templates
# ---------------------------------------------------------------------------


_PYTHON_CLI = ScaffoldTemplate(
    name="python-cli",
    description="Python CLI app - pyproject.toml + entrypoint + README.",
    keywords=(
        "python",
        "cli",
        "command",
        "script",
        "fastapi",
        "flask",
        "django",
        "streamlit",
        "convert",
        "automation",
        "pipeline",
        "data",
    ),
    files=(
        ScaffoldFile(
            relative_path="pyproject.toml",
            content=(
                "[project]\n"
                'name = "$slug"\n'
                'version = "0.1.0"\n'
                'description = "$prompt"\n'
                'requires-python = ">=3.10"\n'
                "dependencies = []\n"
                "\n"
                "[project.scripts]\n"
                '$slug = "$slug.main:main"\n'
                "\n"
                "[build-system]\n"
                'requires = ["setuptools>=68"]\n'
                'build-backend = "setuptools.build_meta"\n'
            ),
        ),
        ScaffoldFile(
            relative_path="src/$slug/__init__.py",
            content='"""$prompt."""\n\n__version__ = "0.1.0"\n',
        ),
        ScaffoldFile(
            relative_path="src/$slug/main.py",
            content=(
                '"""Entrypoint for $slug: $prompt."""\n\n'
                "from __future__ import annotations\n\n\n"
                "def main() -> int:\n"
                '    """Run the CLI; returns a process exit code."""\n'
                '    print("hello from $slug")\n'
                "    return 0\n\n\n"
                'if __name__ == "__main__":\n'
                "    raise SystemExit(main())\n"
            ),
        ),
        ScaffoldFile(
            relative_path="README.md",
            content=(
                "# $slug\n\n"
                "$prompt\n\n"
                "## Run\n\n"
                "```bash\n"
                "pip install -e .\n"
                "$slug\n"
                "```\n\n"
                "Generated by `bernstein scaffold`.\n"
            ),
        ),
    ),
)


_NODE_CLI = ScaffoldTemplate(
    name="node-cli",
    description="Node.js CLI app - package.json + entrypoint + README.",
    keywords=(
        "node",
        "nodejs",
        "javascript",
        "typescript",
        "npm",
        "next",
        "nextjs",
        "react",
        "express",
        "vite",
    ),
    files=(
        ScaffoldFile(
            relative_path="package.json",
            content=(
                "{\n"
                '  "name": "$slug",\n'
                '  "version": "0.1.0",\n'
                '  "description": "$prompt",\n'
                '  "type": "module",\n'
                '  "bin": {\n'
                '    "$slug": "./bin/cli.js"\n'
                "  },\n"
                '  "scripts": {\n'
                '    "start": "node ./bin/cli.js"\n'
                "  }\n"
                "}\n"
            ),
        ),
        ScaffoldFile(
            relative_path="bin/cli.js",
            content=('#!/usr/bin/env node\n// Entrypoint for $slug - $prompt.\nconsole.log("hello from $slug");\n'),
        ),
        ScaffoldFile(
            relative_path="README.md",
            content=(
                "# $slug\n\n"
                "$prompt\n\n"
                "## Run\n\n"
                "```bash\n"
                "npm install\n"
                "npm start\n"
                "```\n\n"
                "Generated by `bernstein scaffold`.\n"
            ),
        ),
    ),
)


_STATIC_SITE = ScaffoldTemplate(
    name="static-site",
    description="Plain static site - index.html + style.css + README.",
    keywords=(
        "static",
        "site",
        "landing",
        "page",
        "html",
        "blog",
        "portfolio",
        "tailwind",
        "marketing",
    ),
    files=(
        ScaffoldFile(
            relative_path="index.html",
            content=(
                "<!doctype html>\n"
                '<html lang="en">\n'
                "<head>\n"
                '  <meta charset="utf-8">\n'
                "  <title>$slug</title>\n"
                '  <link rel="stylesheet" href="style.css">\n'
                "</head>\n"
                "<body>\n"
                "  <main>\n"
                "    <h1>$slug</h1>\n"
                "    <p>$prompt</p>\n"
                "  </main>\n"
                "</body>\n"
                "</html>\n"
            ),
        ),
        ScaffoldFile(
            relative_path="style.css",
            content=(
                "body { font: 16px/1.5 system-ui, sans-serif; "
                "margin: 2rem auto; max-width: 40rem; }\n"
                "h1 { font-size: 1.6rem; }\n"
            ),
        ),
        ScaffoldFile(
            relative_path="README.md",
            content=(
                "# $slug\n\n"
                "$prompt\n\n"
                "## Run\n\n"
                "Open `index.html` in a browser, or:\n\n"
                "```bash\n"
                "python3 -m http.server\n"
                "```\n\n"
                "Generated by `bernstein scaffold`.\n"
            ),
        ),
    ),
)


SCAFFOLD_TEMPLATES: dict[str, ScaffoldTemplate] = {
    _PYTHON_CLI.name: _PYTHON_CLI,
    _NODE_CLI.name: _NODE_CLI,
    _STATIC_SITE.name: _STATIC_SITE,
}

# Default fallback when no keyword matches the prompt.
_DEFAULT_TEMPLATE_NAME = "python-cli"


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------


def list_template_names() -> list[str]:
    """Return scaffold template keys in deterministic, sorted order."""
    return sorted(SCAFFOLD_TEMPLATES.keys())


def pick_template(prompt: str) -> ScaffoldTemplate:
    """Pick a scaffold template via a deterministic keyword heuristic.

    Each template lists keywords; we count how many distinct keywords appear
    as whole-word substrings of the lower-cased *prompt*. The template with
    the highest count wins; ties resolve by alphabetical name to keep the
    function fully deterministic. When no template scores a hit we fall back
    to ``python-cli`` as the most general default.

    Args:
        prompt: Free-form goal prompt from the user.

    Returns:
        The chosen :class:`ScaffoldTemplate`.
    """
    haystack = prompt.lower()
    scores: dict[str, int] = {}
    for name, template in SCAFFOLD_TEMPLATES.items():
        scores[name] = sum(1 for kw in template.keywords if kw in haystack)

    best_score = max(scores.values()) if scores else 0
    if best_score == 0:
        return SCAFFOLD_TEMPLATES[_DEFAULT_TEMPLATE_NAME]
    best_name = min(name for name, s in scores.items() if s == best_score)
    return SCAFFOLD_TEMPLATES[best_name]


def materialize_template(
    template: ScaffoldTemplate,
    dest: Path,
    *,
    prompt: str,
    force: bool = False,
) -> list[Path]:
    """Render *template* into *dest*, returning the absolute paths created.

    Substitutions: ``$prompt`` and ``$slug`` (derived from *dest*'s name).
    The slug is sanitised to alphanumerics and dashes so it is safe to use
    inside ``pyproject.toml`` / ``package.json`` ``name`` fields.

    Args:
        template: Template to render.
        dest: Output directory. Created if missing.
        prompt: Original user prompt (substituted into READMEs etc.).
        force: When False and *dest* already contains files, raise
            :class:`ScaffoldError` rather than silently overwriting.

    Returns:
        Absolute paths of files written, in template-declared order.

    Raises:
        ScaffoldError: When *dest* exists and is non-empty without *force*.
    """
    dest = dest.resolve()
    if dest.exists() and any(dest.iterdir()) and not force:
        raise ScaffoldError(
            f"Destination {dest} already exists and is not empty; pass --force to overwrite.",
        )
    dest.mkdir(parents=True, exist_ok=True)

    slug = _sanitize_slug(dest.name)
    mapping = {"prompt": prompt, "slug": slug}
    written: list[Path] = []
    for spec in template.files:
        rel = Template(spec.relative_path).safe_substitute(mapping)
        body = Template(spec.content).safe_substitute(mapping)
        target = dest / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(body, encoding="utf-8")
        written.append(target)
    return written


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


def _sanitize_slug(name: str) -> str:
    """Return *name* reduced to package-safe characters.

    Replaces non-alphanumeric runs with single dashes, lower-cases the
    result, and falls back to ``scaffold-app`` for empty inputs so we never
    emit an invalid ``pyproject.toml`` ``name`` field.
    """
    cleaned: list[str] = []
    prev_dash = False
    for ch in name.lower():
        if ch.isalnum():
            cleaned.append(ch)
            prev_dash = False
        elif not prev_dash:
            cleaned.append("-")
            prev_dash = True
    slug = "".join(cleaned).strip("-")
    return slug or "scaffold-app"
