/**
 * Deterministic icon picker for agent avatars. Lead always gets a crown so
 * the coordinator visually pops. Workers get one of 30 distinct lucide
 * icons seeded by agent id (NOT name — names can change, ids don't).
 */

import {
  Accessibility,
  Activity,
  Airplay,
  Ambulance,
  Amphora,
  Anchor,
  Angry,
  Annoyed,
  Antenna,
  Anvil,
  Aperture,
  Apple,
  AppWindow,
  Archive,
  Armchair,
  Asterisk,
  Atom,
  AtSign,
  Award,
  Axe,
  Baby,
  Backpack,
  Badge,
  Balloon,
  Banana,
  Banknote,
  Barcode,
  Bath,
  Battery,
  Beaker,
  Bed,
  Beef,
  Beer,
  Bell,
  Bike,
  Binoculars,
  Biohazard,
  Bird,
  Blocks,
  Bluetooth,
  Bolt,
  Book,
  Bookmark,
  Bot,
  Box,
  Brain,
  BrickWall,
  Briefcase,
  Brush,
  Bug,
  Building,
  Bus,
  Cable,
  CableCar,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Candy,
  Cannabis,
  Captions,
  Car,
  Caravan,
  CarFront,
  Carrot,
  Castle,
  Cat,
  Cctv,
  Check,
  ChefHat,
  Cherry,
  ChessKing,
  ChessKnight,
  ChessQueen,
  Church,
  Circle,
  Citrus,
  Clapperboard,
  Clipboard,
  Clock,
  Cloud,
  Clover,
  Club,
  Code,
  Coffee,
  Cog,
  Compass,
  Cookie,
  Copyright,
  Cpu,
  CreditCard,
  Croissant,
  Cross,
  Crosshair,
  Crown,
  Database,
  Dessert,
  Diamond,
  Dices,
  Disc,
  Dna,
  Dock,
  Dog,
  DollarSign,
  Donut,
  DoorOpen,
  Drama,
  Drone,
  Droplet,
  Droplets,
  Drum,
  Drumstick,
  Dumbbell,
  Ear,
  Earth,
  Eclipse,
  Egg,
  Eraser,
  Euro,
  Eye,
  Factory,
  Fan,
  Feather,
  File as FileIcon,
  Film,
  FingerprintPattern,
  Fish,
  Flag,
  Flame,
  Flashlight,
  FlaskConical,
  Flower2,
  Folder,
  Footprints,
  Forklift,
  Frown,
  Fuel,
  Gamepad2,
  Gauge,
  Gavel,
  Gem,
  Ghost,
  Gift,
  Glasses,
  Globe,
  Gpu,
  GraduationCap,
  Grape,
  Guitar,
  Ham,
  Hamburger,
  Hammer,
  Hand,
  Handbag,
  HandHeart,
  HandMetal,
  Handshake,
  HardDrive,
  HardHat,
  Hash,
  Headphones,
  Headset,
  Heart,
  HeartCrack,
  HeartPulse,
  Helicopter,
  Hexagon,
  Hospital,
  Hotel,
  Hourglass,
  House,
  IceCreamCone,
  IdCard,
  Image as ImageIcon,
  IndianRupee,
  Infinity as InfinityIcon,
  JapaneseYen,
  Joystick,
  Kayak,
  Key,
  Keyboard,
  KeyRound,
  Lamp,
  Landmark,
  Languages,
  Laptop,
  Laugh,
  Layers,
  Leaf,
  LeafyGreen,
  Library,
  Lightbulb,
  Lock,
  Lollipop,
  type LucideIcon,
  Luggage,
  Magnet,
  Mail,
  Map as MapIcon,
  MapPin,
  Medal,
  Megaphone,
  Meh,
  MessageCircle,
  MessageSquare,
  Metronome,
  Mic,
  Microchip,
  Microscope,
  Microwave,
  Milk,
  Monitor,
  Moon,
  Motorbike,
  Mountain,
  Mouse,
  Music,
  Navigation,
  Network,
  Newspaper,
  Notebook,
  NotebookPen,
  Nut,
  Octagon,
  Omega,
  Orbit,
  Origami,
  Package,
  PaintBucket,
  Palette,
  Panda,
  ParkingMeter,
  PartyPopper,
  PawPrint,
  Pen,
  Pencil,
  Pentagon,
  Percent,
  PersonStanding,
  PhilippinePeso,
  Phone,
  Piano,
  Pickaxe,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  PocketKnife,
  Podcast,
  Popcorn,
  PoundSterling,
  Power,
  Printer,
  Projector,
  Puzzle,
  Pyramid,
  QrCode,
  Quote,
  Rabbit,
  Radar,
  Radiation,
  Radio,
  RadioTower,
  Rainbow,
  Rat,
  Receipt,
  Recycle,
  Refrigerator,
  Ribbon,
  Rocket,
  Rose,
  Router,
  Rss,
  Ruler,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  SatelliteDish,
  Scale,
  School,
  Scissors,
  Scooter,
  Scroll,
  Shapes,
  Shell,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Shovel,
  Shrimp,
  Shrub,
  Sigma,
  Signal,
  Signpost,
  Siren,
  Skull,
  Smartphone,
  Smile,
  Snail,
  Snowflake,
  Sofa,
  Soup,
  Space,
  Spade,
  Sparkles,
  Speaker,
  Speech,
  Spotlight,
  Sprout,
  Square,
  Squirrel,
  Stamp,
  Star,
  Stethoscope,
  Sticker,
  StickyNote,
  Stone,
  Store,
  Sun,
  Sunrise,
  Sunset,
  SwissFranc,
  Sword,
  Swords,
  Syringe,
  Table,
  Tag,
  Target,
  Telescope,
  Tent,
  Terminal,
  Theater,
  Thermometer,
  ThumbsUp,
  Ticket,
  Tickets,
  Timer,
  Toilet,
  Toolbox,
  Tornado,
  Tractor,
  TrafficCone,
  TrainFront,
  Trash2,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Trees,
  TrendingUp,
  Triangle,
  Trophy,
  Truck,
  Turtle,
  Tv,
  Umbrella,
  University,
  Usb,
  User,
  Utensils,
  UtilityPole,
  Van,
  Vault,
  Vegan,
  Video,
  Voicemail,
  Volleyball,
  Volume2,
  Vote,
  Wallet,
  WandSparkles,
  Warehouse,
  Watch,
  Waves,
  Waypoints,
  Webcam,
  Weight,
  Wheat,
  Wifi,
  Wind,
  Wine,
  Workflow,
  Worm,
  Wrench,
  Zap,
} from "lucide-react";
import type { AgentAvatar } from "@/api/types";

/**
 * Compatibility-sensitive: do not reorder, add, or remove entries. Existing
 * agents rely on FNV-1a(agentId) % 30 resolving to the same fallback icon.
 */
export const WORKER_ICONS: LucideIcon[] = [
  Bot,
  Cat,
  Dog,
  Bird,
  Fish,
  Bug,
  Snail,
  Turtle,
  Squirrel,
  Cherry,
  Apple,
  Carrot,
  Leaf,
  Sprout,
  TreeDeciduous,
  Flower2,
  Mountain,
  Sun,
  Moon,
  Cloud,
  Snowflake,
  Sparkles,
  Star,
  Rocket,
  Plane,
  Anchor,
  Compass,
  Telescope,
  Atom,
  Crown, // (also in pool — only worker w/ crown is statistically rare; included to fill 30)
];

function hash(str: string): number {
  let h = 2166136261;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function getAgentIcon(input: {
  agentId?: string | null;
  isLead?: boolean | null;
  role?: string | null;
  agentName?: string | null;
}): LucideIcon {
  const role = input.role?.toLowerCase();
  const name = input.agentName?.toLowerCase();
  if (input.isLead || role === "lead" || name === "lead") return Crown;
  const seed = input.agentId ?? input.agentName ?? "";
  if (!seed) return Bot;
  return WORKER_ICONS[hash(seed) % 30] ?? Bot;
}

/**
 * Curated catalog for the avatar picker + custom-avatar renderer. Superset of
 * `WORKER_ICONS` (kept separate — that pool stays untouched so the
 * deterministic fallback for existing agents never shifts). Keys are the
 * kebab-case names stored in `AgentAvatar.icon`; adding an icon here is a
 * UI-only change (no migration, no server change — the server only validates
 * the kebab-case shape).
 *
 * Curated across the full a-z alphabet (not an alphabetical head-slice) and
 * scrubbed of deprecated lucide-react aliases: every key here maps to that
 * icon's current canonical export, so a future lucide-react major bump that
 * drops old aliases (e.g. AreaChart, BookTemplate) cannot silently break this
 * file. Generic UI-glyph families (arrow-*, align-*, chart-*, chevron-*,
 * between-*, badge-*, alarm-clock-*, etc.) are deliberately kept to a token
 * few or dropped entirely — they read as app chrome, not as something a
 * person would pick to represent an agent.
 */
export const AVATAR_ICON_CATALOG: Record<string, LucideIcon> = {
  accessibility: Accessibility,
  activity: Activity,
  airplay: Airplay,
  ambulance: Ambulance,
  amphora: Amphora,
  anchor: Anchor,
  angry: Angry,
  annoyed: Annoyed,
  antenna: Antenna,
  anvil: Anvil,
  aperture: Aperture,
  "app-window": AppWindow,
  apple: Apple,
  archive: Archive,
  armchair: Armchair,
  asterisk: Asterisk,
  "at-sign": AtSign,
  atom: Atom,
  award: Award,
  axe: Axe,
  baby: Baby,
  backpack: Backpack,
  badge: Badge,
  balloon: Balloon,
  banana: Banana,
  banknote: Banknote,
  barcode: Barcode,
  bath: Bath,
  battery: Battery,
  beaker: Beaker,
  bed: Bed,
  beef: Beef,
  beer: Beer,
  bell: Bell,
  bike: Bike,
  binoculars: Binoculars,
  biohazard: Biohazard,
  bird: Bird,
  blocks: Blocks,
  bluetooth: Bluetooth,
  bolt: Bolt,
  book: Book,
  bookmark: Bookmark,
  bot: Bot,
  box: Box,
  brain: Brain,
  "brick-wall": BrickWall,
  briefcase: Briefcase,
  brush: Brush,
  bug: Bug,
  building: Building,
  bus: Bus,
  cable: Cable,
  "cable-car": CableCar,
  cake: Cake,
  calculator: Calculator,
  calendar: Calendar,
  camera: Camera,
  candy: Candy,
  cannabis: Cannabis,
  captions: Captions,
  car: Car,
  "car-front": CarFront,
  caravan: Caravan,
  carrot: Carrot,
  castle: Castle,
  cat: Cat,
  cctv: Cctv,
  check: Check,
  "chef-hat": ChefHat,
  cherry: Cherry,
  "chess-king": ChessKing,
  "chess-knight": ChessKnight,
  "chess-queen": ChessQueen,
  church: Church,
  circle: Circle,
  citrus: Citrus,
  clapperboard: Clapperboard,
  clipboard: Clipboard,
  clock: Clock,
  cloud: Cloud,
  clover: Clover,
  club: Club,
  code: Code,
  coffee: Coffee,
  cog: Cog,
  compass: Compass,
  cookie: Cookie,
  copyright: Copyright,
  cpu: Cpu,
  "credit-card": CreditCard,
  croissant: Croissant,
  cross: Cross,
  crosshair: Crosshair,
  crown: Crown,
  database: Database,
  dessert: Dessert,
  diamond: Diamond,
  dices: Dices,
  disc: Disc,
  dna: Dna,
  dock: Dock,
  dog: Dog,
  "dollar-sign": DollarSign,
  donut: Donut,
  "door-open": DoorOpen,
  drama: Drama,
  drone: Drone,
  droplet: Droplet,
  droplets: Droplets,
  drum: Drum,
  drumstick: Drumstick,
  dumbbell: Dumbbell,
  ear: Ear,
  earth: Earth,
  eclipse: Eclipse,
  egg: Egg,
  eraser: Eraser,
  euro: Euro,
  eye: Eye,
  factory: Factory,
  fan: Fan,
  feather: Feather,
  file: FileIcon,
  film: Film,
  "fingerprint-pattern": FingerprintPattern,
  fish: Fish,
  flag: Flag,
  flame: Flame,
  flashlight: Flashlight,
  "flask-conical": FlaskConical,
  flower: Flower2,
  folder: Folder,
  footprints: Footprints,
  forklift: Forklift,
  frown: Frown,
  fuel: Fuel,
  "gamepad-2": Gamepad2,
  gauge: Gauge,
  gavel: Gavel,
  gem: Gem,
  ghost: Ghost,
  gift: Gift,
  glasses: Glasses,
  globe: Globe,
  gpu: Gpu,
  "graduation-cap": GraduationCap,
  grape: Grape,
  guitar: Guitar,
  ham: Ham,
  hamburger: Hamburger,
  hammer: Hammer,
  hand: Hand,
  "hand-heart": HandHeart,
  "hand-metal": HandMetal,
  handbag: Handbag,
  handshake: Handshake,
  "hard-drive": HardDrive,
  "hard-hat": HardHat,
  hash: Hash,
  headphones: Headphones,
  headset: Headset,
  heart: Heart,
  "heart-crack": HeartCrack,
  "heart-pulse": HeartPulse,
  helicopter: Helicopter,
  hexagon: Hexagon,
  hospital: Hospital,
  hotel: Hotel,
  hourglass: Hourglass,
  house: House,
  "ice-cream-cone": IceCreamCone,
  "id-card": IdCard,
  image: ImageIcon,
  "indian-rupee": IndianRupee,
  infinity: InfinityIcon,
  "japanese-yen": JapaneseYen,
  joystick: Joystick,
  kayak: Kayak,
  key: Key,
  "key-round": KeyRound,
  keyboard: Keyboard,
  lamp: Lamp,
  landmark: Landmark,
  languages: Languages,
  laptop: Laptop,
  laugh: Laugh,
  layers: Layers,
  leaf: Leaf,
  "leafy-green": LeafyGreen,
  library: Library,
  lightbulb: Lightbulb,
  lock: Lock,
  lollipop: Lollipop,
  luggage: Luggage,
  magnet: Magnet,
  mail: Mail,
  map: MapIcon,
  "map-pin": MapPin,
  medal: Medal,
  megaphone: Megaphone,
  meh: Meh,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  metronome: Metronome,
  mic: Mic,
  microchip: Microchip,
  microscope: Microscope,
  microwave: Microwave,
  milk: Milk,
  monitor: Monitor,
  moon: Moon,
  motorbike: Motorbike,
  mountain: Mountain,
  mouse: Mouse,
  music: Music,
  navigation: Navigation,
  network: Network,
  newspaper: Newspaper,
  notebook: Notebook,
  "notebook-pen": NotebookPen,
  nut: Nut,
  octagon: Octagon,
  omega: Omega,
  orbit: Orbit,
  origami: Origami,
  package: Package,
  "paint-bucket": PaintBucket,
  palette: Palette,
  panda: Panda,
  "parking-meter": ParkingMeter,
  "party-popper": PartyPopper,
  "paw-print": PawPrint,
  pen: Pen,
  pencil: Pencil,
  pentagon: Pentagon,
  percent: Percent,
  "person-standing": PersonStanding,
  "philippine-peso": PhilippinePeso,
  phone: Phone,
  piano: Piano,
  pickaxe: Pickaxe,
  "piggy-bank": PiggyBank,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  plug: Plug,
  "pocket-knife": PocketKnife,
  podcast: Podcast,
  popcorn: Popcorn,
  "pound-sterling": PoundSterling,
  power: Power,
  printer: Printer,
  projector: Projector,
  puzzle: Puzzle,
  pyramid: Pyramid,
  "qr-code": QrCode,
  quote: Quote,
  rabbit: Rabbit,
  radar: Radar,
  radiation: Radiation,
  radio: Radio,
  "radio-tower": RadioTower,
  rainbow: Rainbow,
  rat: Rat,
  receipt: Receipt,
  recycle: Recycle,
  refrigerator: Refrigerator,
  ribbon: Ribbon,
  rocket: Rocket,
  rose: Rose,
  router: Router,
  rss: Rss,
  ruler: Ruler,
  sailboat: Sailboat,
  salad: Salad,
  sandwich: Sandwich,
  satellite: Satellite,
  "satellite-dish": SatelliteDish,
  scale: Scale,
  school: School,
  scissors: Scissors,
  scooter: Scooter,
  scroll: Scroll,
  shapes: Shapes,
  shell: Shell,
  shield: Shield,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  shovel: Shovel,
  shrimp: Shrimp,
  shrub: Shrub,
  sigma: Sigma,
  signal: Signal,
  signpost: Signpost,
  siren: Siren,
  skull: Skull,
  smartphone: Smartphone,
  smile: Smile,
  snail: Snail,
  snowflake: Snowflake,
  sofa: Sofa,
  soup: Soup,
  space: Space,
  spade: Spade,
  sparkles: Sparkles,
  speaker: Speaker,
  speech: Speech,
  spotlight: Spotlight,
  sprout: Sprout,
  square: Square,
  squirrel: Squirrel,
  stamp: Stamp,
  star: Star,
  stethoscope: Stethoscope,
  sticker: Sticker,
  "sticky-note": StickyNote,
  stone: Stone,
  store: Store,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  "swiss-franc": SwissFranc,
  sword: Sword,
  swords: Swords,
  syringe: Syringe,
  table: Table,
  tag: Tag,
  target: Target,
  telescope: Telescope,
  tent: Tent,
  terminal: Terminal,
  theater: Theater,
  thermometer: Thermometer,
  "thumbs-up": ThumbsUp,
  ticket: Ticket,
  tickets: Tickets,
  timer: Timer,
  toilet: Toilet,
  toolbox: Toolbox,
  tornado: Tornado,
  tractor: Tractor,
  "traffic-cone": TrafficCone,
  "train-front": TrainFront,
  "trash-2": Trash2,
  "tree-deciduous": TreeDeciduous,
  "tree-palm": TreePalm,
  "tree-pine": TreePine,
  trees: Trees,
  "trending-up": TrendingUp,
  triangle: Triangle,
  trophy: Trophy,
  truck: Truck,
  turtle: Turtle,
  tv: Tv,
  umbrella: Umbrella,
  university: University,
  usb: Usb,
  user: User,
  utensils: Utensils,
  "utility-pole": UtilityPole,
  van: Van,
  vault: Vault,
  vegan: Vegan,
  video: Video,
  voicemail: Voicemail,
  volleyball: Volleyball,
  "volume-2": Volume2,
  vote: Vote,
  wallet: Wallet,
  wand: WandSparkles,
  warehouse: Warehouse,
  watch: Watch,
  waves: Waves,
  waypoints: Waypoints,
  webcam: Webcam,
  weight: Weight,
  wheat: Wheat,
  wifi: Wifi,
  wind: Wind,
  wine: Wine,
  workflow: Workflow,
  worm: Worm,
  wrench: Wrench,
  zap: Zap,
};

/**
 * The original familiar shortlist shown until a search narrows the catalog.
 * An explicit list (not `Object.keys(...).slice(0, 64)`) so it can't drift
 * if the catalog above is ever reordered or alphabetized.
 */
export const DEFAULT_AVATAR_ICON_NAMES: string[] = [
  "bot",
  "cat",
  "dog",
  "bird",
  "fish",
  "bug",
  "snail",
  "turtle",
  "squirrel",
  "rabbit",
  "cherry",
  "apple",
  "carrot",
  "leaf",
  "sprout",
  "tree-deciduous",
  "flower",
  "mountain",
  "sun",
  "moon",
  "cloud",
  "snowflake",
  "sparkles",
  "star",
  "rocket",
  "plane",
  "anchor",
  "compass",
  "telescope",
  "atom",
  "crown",
  "award",
  "book",
  "box",
  "briefcase",
  "camera",
  "coffee",
  "diamond",
  "droplet",
  "feather",
  "flag",
  "flame",
  "gem",
  "ghost",
  "gift",
  "globe",
  "heart",
  "key",
  "lock",
  "map",
  "music",
  "package",
  "palette",
  "pizza",
  "puzzle",
  "shield",
  "skull",
  "sword",
  "target",
  "trophy",
  "umbrella",
  "wand",
  "zap",
  "wrench",
];
export const MAX_AVATAR_ICON_SEARCH_RESULTS = 100;

/**
 * Filters the static picker catalog without coupling the search behavior to
 * the popover. Spaces and hyphens are intentionally equivalent so people can
 * discover names such as `tree-deciduous` by typing natural words.
 */
export function searchAvatarIcons(query: string): { iconResults: string[]; totalMatches: number } {
  const normalizedQuery = query.toLowerCase().replace(/[\s-]+/g, "");
  if (!normalizedQuery) {
    return {
      iconResults: DEFAULT_AVATAR_ICON_NAMES,
      totalMatches: DEFAULT_AVATAR_ICON_NAMES.length,
    };
  }

  const matches = Object.keys(AVATAR_ICON_CATALOG).filter((icon) =>
    icon
      .toLowerCase()
      .replace(/[\s-]+/g, "")
      .includes(normalizedQuery),
  );
  return {
    iconResults: matches.slice(0, MAX_AVATAR_ICON_SEARCH_RESULTS),
    totalMatches: matches.length,
  };
}

/** Resolves an agent's rendered icon: stored catalog icon wins; unset/unknown
 * falls back to the existing deterministic derivation, so a stale or
 * hand-set icon name can never break rendering. */
export function resolveAgentIcon(
  avatar: AgentAvatar | null | undefined,
  fallbackInputs: {
    agentId?: string | null;
    isLead?: boolean | null;
    role?: string | null;
    agentName?: string | null;
  },
): LucideIcon {
  if (avatar?.type === "lucide") {
    const catalogIcon = AVATAR_ICON_CATALOG[avatar.icon];
    if (catalogIcon) return catalogIcon;
  }
  return getAgentIcon(fallbackInputs);
}
