// GENERATED by scripts/gen-amd-rocm-pci-ids.mjs -- do not edit by hand.
//
// AMD PCI device id -> LLVM gfx target, for GPUs that BOTH AMD supports on
// Windows and the upstream `windows-rocm` archive is compiled for. Windows has
// no `/sys/class/kfd`, so the PCI device id from Vulkan is the only gfx signal
// available before the binary runs.
//
// Sources:
//   https://rocm.docs.amd.com/projects/install-on-windows/en/latest/reference/system-requirements.html
//   https://pci-ids.ucw.cz/v2.2/pci.ids
//
// Not covered, because pci.ids carries no board name matching AMD's row:
//   - AMD Radeon RX 9060
//   - AMD Radeon RX 7650 GRE
//   - AMD Ryzen AI Max+ Pro 395
//   - AMD Ryzen AI Max+ 395
//   - AMD Ryzen AI Max Pro 390
//   - AMD Ryzen AI Max 390
//   - AMD Ryzen AI Max Pro 385
//   - AMD Ryzen AI Max 385
//   - AMD Ryzen AI Max Pro 380
//   - AMD Ryzen AI 300 Series
//   - AMD Ryzen AI 9 400 Series
//   - AMD Ryzen AI MAX+ 495
//   - AMD Ryzen AI MAX+ 492
//   - AMD Ryzen AII MAX PRO 490
// These reach ROCm only through the manual backend picker.
pub const AMD_ROCM_WINDOWS_PCI_IDS: &[(u32, &str)] = &[
    (0x73f0, "gfx1102"), // Navi 33 [Radeon RX 7600M XT]
    (0x7448, "gfx1100"), // Navi 31 [Radeon Pro W7900]
    (0x7449, "gfx1100"), // Navi 31 [Radeon Pro W7800 48GB]
    (0x744a, "gfx1100"), // Navi 31 [Radeon Pro W7900 Dual Slot]
    (0x744b, "gfx1100"), // Navi 31 [Radeon Pro W7900D]
    (0x744c, "gfx1100"), // Navi 31 [Radeon RX 7900 XT/7900 XTX/7900 GRE/7900M]
    (0x745e, "gfx1100"), // Navi 31 [Radeon Pro W7800]
    (0x7460, "gfx1101"), // Navi 32 GL-XL [AMD Radeon PRO V710]
    (0x7461, "gfx1101"), // Navi 32 [AMD Radeon PRO V710]
    (0x7470, "gfx1101"), // Navi 32 [Radeon PRO W7700]
    (0x747e, "gfx1101"), // Navi 32 [Radeon RX 7700 XT / 7800 XT]
    (0x7480, "gfx1102"), // Navi 33 [Radeon RX 7600/7600 XT/7600M XT/7600S/7700S / PRO W7600]
    (0x7481, "gfx1102"), // Navi 33 [Radeon Graphics]
    (0x7483, "gfx1102"), // Navi 33 [Radeon RX 7600M/7600M XT]
    (0x7487, "gfx1102"), // Navi 33 [Radeon Graphics]
    (0x7489, "gfx1102"), // Navi 33 [Radeon Pro W7500]
    (0x748b, "gfx1102"), // Navi 33 [Radeon Graphics]
    (0x7499, "gfx1102"), // Navi 33 [Radeon RX 7400/7300/Pro W7400]
    (0x749f, "gfx1102"), // Navi 33 [Radeon RX 7500]
    (0x7550, "gfx1201"), // Navi 48 [Radeon RX 9070/9070 XT/9070 GRE]
    (0x7551, "gfx1201"), // Navi 48 [Radeon AI PRO R9700]
    (0x7590, "gfx1200"), // Navi 44 [Radeon RX 9050 / 9060 XT]
];
