bench:
  enabled: true
  dataset: "molbench-ms-1"
  data_path: "molbench/data/molbench-ms-1/molbench-ms-1.csv"
  model_name: "pure-llm"
  tasks: ["rdkit_bench"]
  max_process: 1

model:
  llm_model:

settings:
  seed: 42
  loop_count: 1
  max_iter: 15
  enable_manual_input: 0
