# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""nooa completion — Generate shell completion scripts.

Usage:
    nooa completion bash     # Print bash completion script
    nooa completion zsh      # Print zsh completion script
    nooa completion fish     # Print fish completion script
    nooa completion install  # Auto-install for current shell
"""

import os
from pathlib import Path

import click

# Completion script templates — generated by Click 8.x, embedded to avoid
# subprocess overhead and capture issues.
_BASH_SCRIPT = r"""
%(complete_func)s() {
    local IFS=$'\n'
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   %(complete_var)s=bash_complete $1 ) )
    return 0
}

%(complete_func)ssetup() {
    complete -o default -F %(complete_func)s %(prog_name)s
}

%(complete_func)ssetup;
""".strip()

_ZSH_SCRIPT = r"""
#compdef %(prog_name)s

%(complete_func)s() {
    local -a completions
    local -a completions_with_descriptions
    local -a response
    (( ! $+commands[%(prog_name)s] )) && return 1

    response=("${(@f)$(env COMP_WORDS="${words[*]}" COMP_CWORD=$((CURRENT-1)) %(complete_var)s=zsh_complete %(prog_name)s)}")

    for type key descr in ${response}; do
        if [[ "$type" == "plain" ]]; then
            if [[ "$descr" == "_" ]]; then
                completions+=("$key")
            else
                completions_with_descriptions+=("$key":"$descr")
            fi
        elif [[ "$type" == "dir" ]]; then
            _path_files -/
        elif [[ "$type" == "file" ]]; then
            _path_files -f
        fi
    done

    if [ -n "$completions_with_descriptions" ]; then
        _describe -V unsorted completions_with_descriptions -U
    fi

    if [ -n "$completions" ]; then
        compadd -U -V unsorted -a completions
    fi
}

if [[ $zsh_eval_context[-1] == loadautofun ]]; then
    # autoload from fpath
    %(complete_func)s "$@"
else
    compdef %(complete_func)s %(prog_name)s
fi
""".strip()

_FISH_SCRIPT = r"""
complete -c %(prog_name)s -f -a "(env %(complete_var)s=fish_complete COMP_WORDS=(commandline -cp) COMP_CWORD=(commandline -t) %(prog_name)s)"
""".strip()


def _render_script(template: str) -> str:
    """Render a completion script template with nooa-specific values."""
    return template % {
        "complete_func": "_nooa_completion",
        "complete_var": "_NOOA_COMPLETE",
        "prog_name": "nooa",
    }


@click.group()
def completion():
    """Generate shell completion scripts for nooa.

    \b
    Quick setup (add to your shell profile):

        # bash (~/.bashrc)
        eval "$(_NOOA_COMPLETE=bash_source nooa)"

        # zsh (~/.zshrc)
        eval "$(_NOOA_COMPLETE=zsh_source nooa)"

        # fish (~/.config/fish/config.fish)
        _NOOA_COMPLETE=fish_source nooa | source
    """


@completion.command()
def bash():
    """Print bash completion script.

    \b
    Usage:
        eval "$(nooa completion bash)"
        # Or append to profile:
        nooa completion bash >> ~/.bashrc
    """
    click.echo(_render_script(_BASH_SCRIPT))


@completion.command()
def zsh():
    """Print zsh completion script.

    \b
    Usage:
        eval "$(nooa completion zsh)"
        # Or append to profile:
        nooa completion zsh >> ~/.zshrc
    """
    click.echo(_render_script(_ZSH_SCRIPT))


@completion.command()
def fish():
    """Print fish completion script.

    \b
    Usage:
        nooa completion fish > ~/.config/fish/completions/nooa.fish
    """
    click.echo(_render_script(_FISH_SCRIPT))


@completion.command()
def install():
    """Auto-detect shell and install completions.

    Detects your current shell and appends the completion script
    to the appropriate profile file.
    """
    shell = _detect_shell()
    if not shell:
        click.secho("Could not detect your shell. Use one of:", fg="red")
        click.echo("  nooa completion bash")
        click.echo("  nooa completion zsh")
        click.echo("  nooa completion fish")
        raise SystemExit(1)

    click.echo(f"Detected shell: {shell}")

    if shell == "bash":
        profile = Path.home() / ".bashrc"
        line = 'eval "$(_NOOA_COMPLETE=bash_source nooa)"'
    elif shell == "zsh":
        profile = Path.home() / ".zshrc"
        line = 'eval "$(_NOOA_COMPLETE=zsh_source nooa)"'
    elif shell == "fish":
        profile = Path.home() / ".config" / "fish" / "completions" / "nooa.fish"
        line = None  # Fish uses a completions file with the script directly
    else:
        click.secho(f"Unsupported shell: {shell}", fg="red")
        raise SystemExit(1)

    # Remove stale pre-rename fish completions file if present.
    if shell == "fish":
        old_fish = Path.home() / ".config" / "fish" / "completions" / "nemo.fish"
        if old_fish.exists():
            old_fish.unlink()
            click.secho(f"Removed stale pre-rename completions: {old_fish}", fg="yellow")

    # Check if already installed; drop stale pre-rename lines. Old installs
    # wrote `_NEMO_COMPLETE=... nooa` — now that the `nooa` binary
    # exists, click ignores the wrong variable and the eval'd help text
    # errors on every shell startup.
    if profile.exists():
        existing = _read_preserving_newlines(profile)
        line_ending = _detect_line_ending(existing)
        lines = existing.splitlines()
        stale_indices = {
            i for i, ln in enumerate(lines) if "_NEMO_COMPLETE" in ln and "_NOOA_COMPLETE" not in ln
        }
        # Also mark preceding comment lines that belong to the same block
        # (e.g. "# nemo shell completions" immediately above a stale eval).
        for i in sorted(stale_indices):
            prev = i - 1
            while prev >= 0 and prev not in stale_indices:
                stripped = lines[prev].strip()
                if stripped.startswith("#") and "nemo" in stripped.lower():
                    stale_indices.add(prev)
                    prev -= 1
                else:
                    break
        if stale_indices:
            cleaned = line_ending.join(ln for i, ln in enumerate(lines) if i not in stale_indices)
            profile.write_text(cleaned + (line_ending if cleaned else ""))
            existing = cleaned
            click.secho(
                f"Removed stale _NEMO_COMPLETE completion line(s) from {profile}",
                fg="yellow",
            )
        if "_NOOA_COMPLETE" in existing:
            click.secho(f"Completions already installed in {profile}", fg="green")
            return

    if shell == "fish":
        # Fish: write completions file
        profile.parent.mkdir(parents=True, exist_ok=True)
        script = _render_script(_FISH_SCRIPT)
        profile.write_text(script + "\n")
        click.secho(f"Completions written to {profile}", fg="green")
    else:
        # Bash/zsh: append eval one-liner to profile
        with open(profile, "a") as f:
            f.write(f"\n# nooa shell completions\n{line}\n")
        click.secho(f"Completions added to {profile}", fg="green")
        click.echo(f"Run: source {profile}")


def _detect_line_ending(text: str) -> str:
    """Return the dominant line ending in *text*."""
    if "\r\n" in text:
        return "\r\n"
    return "\n"


def _read_preserving_newlines(path: Path) -> str:
    """Read file without Python's universal newline translation."""
    with open(path, newline="") as f:
        return f.read()


def _detect_shell() -> str | None:
    """Detect the current shell."""
    shell = os.environ.get("SHELL", "")
    if "zsh" in shell:
        return "zsh"
    elif "bash" in shell:
        return "bash"
    elif "fish" in shell:
        return "fish"
    return None
