"""baseline schema

The pre-channel-centralization schema: every table the app owned before the
centralized Slack/Lark channel work. This represents what existing deployments
already have, so production is brought onto Alembic by stamping THIS revision
(no DDL runs). Fresh databases run it to build the core schema. The channel
delta (team_channel* tables, users.slack_id/lark_id, the OAuth routing indexes)
lives in the next, idempotent revision.

Revision ID: d904723340f2
Revises:
Create Date: 2026-06-26 23:52:27.589828

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d904723340f2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_activities",
        sa.Column(
            "id",
            sa.String(),
            nullable=False,
            comment="Unique identifier for the activity",
        ),
        sa.Column("agent_id", sa.String(), nullable=False, comment="ID of the agent"),
        sa.Column("text", sa.String(), nullable=False, comment="Content"),
        sa.Column(
            "images",
            postgresql.ARRAY(sa.String()),
            nullable=True,
            comment="List of image URLs",
        ),
        sa.Column("video", sa.String(), nullable=True, comment="Video URL"),
        sa.Column("link", sa.String(), nullable=True, comment="Link URL"),
        sa.Column(
            "link_meta",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Link metadata",
        ),
        sa.Column("post_id", sa.String(), nullable=True, comment="Related post ID"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when created",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_activities_agent_id"),
        "agent_activities",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_activities_post_id"),
        "agent_activities",
        ["post_id"],
        unique=False,
    )
    op.create_table(
        "agent_data",
        sa.Column("id", sa.String(), nullable=False, comment="Same as Agent.id"),
        sa.Column(
            "evm_wallet_address",
            sa.String(),
            nullable=True,
            comment="EVM wallet address",
        ),
        sa.Column(
            "solana_wallet_address",
            sa.String(),
            nullable=True,
            comment="Solana wallet address",
        ),
        sa.Column(
            "cdp_wallet_data", sa.String(), nullable=True, comment="CDP wallet data"
        ),
        sa.Column(
            "privy_wallet_data", sa.String(), nullable=True, comment="Privy wallet data"
        ),
        sa.Column(
            "native_wallet_data",
            sa.String(),
            nullable=True,
            comment="Native wallet data (encrypted private key)",
        ),
        sa.Column("twitter_id", sa.String(), nullable=True, comment="Twitter user ID"),
        sa.Column(
            "twitter_username", sa.String(), nullable=True, comment="Twitter username"
        ),
        sa.Column(
            "twitter_name", sa.String(), nullable=True, comment="Twitter display name"
        ),
        sa.Column(
            "twitter_access_token",
            sa.String(),
            nullable=True,
            comment="Twitter access token",
        ),
        sa.Column(
            "twitter_access_token_expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Twitter access token expiration time",
        ),
        sa.Column(
            "twitter_refresh_token",
            sa.String(),
            nullable=True,
            comment="Twitter refresh token",
        ),
        sa.Column(
            "twitter_self_key_refreshed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Twitter self-key userinfo last refresh time",
        ),
        sa.Column(
            "twitter_is_verified",
            sa.Boolean(),
            nullable=False,
            comment="Whether the Twitter account is verified",
        ),
        sa.Column(
            "telegram_id", sa.String(), nullable=True, comment="Telegram user ID"
        ),
        sa.Column(
            "telegram_username", sa.String(), nullable=True, comment="Telegram username"
        ),
        sa.Column(
            "telegram_name", sa.String(), nullable=True, comment="Telegram display name"
        ),
        sa.Column("discord_id", sa.String(), nullable=True, comment="Discord user ID"),
        sa.Column(
            "discord_username", sa.String(), nullable=True, comment="Discord username"
        ),
        sa.Column(
            "discord_name", sa.String(), nullable=True, comment="Discord display name"
        ),
        sa.Column(
            "long_term_memory",
            sa.String(),
            nullable=True,
            comment="Long-term memory content",
        ),
        sa.Column(
            "error_message", sa.String(), nullable=True, comment="Last error message"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the agent data was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the agent data was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_drafts",
        sa.Column(
            "id",
            sa.String(),
            nullable=False,
            comment="Unique identifier for the agent. Must be URL-safe, containing only lowercase letters, numbers, and hyphens",
        ),
        sa.Column("agent_id", sa.String(), nullable=False, comment="Agent id"),
        sa.Column(
            "owner",
            sa.String(),
            nullable=True,
            comment="Owner identifier of the agent, used for access control",
        ),
        sa.Column(
            "team_id",
            sa.String(),
            nullable=True,
            comment="Team identifier of the agent, used for access control",
        ),
        sa.Column(
            "version", sa.String(), nullable=True, comment="Version hash of the agent"
        ),
        sa.Column(
            "project_id",
            sa.String(),
            nullable=True,
            comment="Project ID, forward compatible",
        ),
        sa.Column(
            "last_draft_id",
            sa.String(),
            nullable=True,
            comment="ID of the last draft that was deployed",
        ),
        sa.Column(
            "deployed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the agent was deployed",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the agent was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the agent was last updated",
        ),
        sa.Column(
            "name", sa.String(), nullable=True, comment="Display name of the agent"
        ),
        sa.Column(
            "picture", sa.String(), nullable=True, comment="Picture of the agent"
        ),
        sa.Column(
            "purpose",
            sa.String(),
            nullable=True,
            comment="Purpose or role of the agent",
        ),
        sa.Column(
            "personality",
            sa.String(),
            nullable=True,
            comment="Personality traits of the agent",
        ),
        sa.Column(
            "principles",
            sa.String(),
            nullable=True,
            comment="Principles or values of the agent",
        ),
        sa.Column(
            "model",
            sa.String(),
            nullable=False,
            comment="AI model identifier to be used by this agent for processing requests.",
        ),
        sa.Column(
            "prompt",
            sa.String(),
            nullable=True,
            comment="Base system prompt that defines the agent's behavior and capabilities",
        ),
        sa.Column(
            "prompt_append",
            sa.String(),
            nullable=True,
            comment="Additional system prompt that has higher priority than the base prompt",
        ),
        sa.Column(
            "temperature",
            sa.Float(),
            nullable=True,
            comment="Controls response randomness (0.0~2.0). Higher values increase creativity but may reduce accuracy. For rigorous tasks, use lower values.",
        ),
        sa.Column(
            "frequency_penalty",
            sa.Float(),
            nullable=True,
            comment="Controls repetition in responses (-2.0~2.0). Higher values reduce repetition, lower values allow more repetition.",
        ),
        sa.Column(
            "presence_penalty",
            sa.Float(),
            nullable=True,
            comment="Controls topic adherence (-2.0~2.0). Higher values allow more topic deviation, lower values enforce stricter topic adherence.",
        ),
        sa.Column(
            "wallet_provider",
            sa.String(),
            nullable=True,
            comment="Provider of the agent's wallet",
        ),
        sa.Column(
            "readonly_wallet_address",
            sa.String(),
            nullable=True,
            comment="Readonly wallet address of the agent",
        ),
        sa.Column(
            "weekly_spending_limit",
            sa.Float(),
            nullable=True,
            comment="Weekly spending limit in USDC when wallet_provider is safe",
        ),
        sa.Column(
            "network_id", sa.String(), nullable=True, comment="Network identifier"
        ),
        sa.Column(
            "tools",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Dict of tools and their corresponding configurations",
        ),
        sa.Column(
            "search_internet",
            sa.Boolean(),
            nullable=True,
            comment="Enable LLM native internet search",
        ),
        sa.Column(
            "super_mode",
            sa.Boolean(),
            nullable=True,
            comment="Enable super mode with higher recursion limit",
        ),
        sa.Column(
            "enable_todo",
            sa.Boolean(),
            nullable=True,
            comment="Enable todo list middleware for task planning and tracking",
        ),
        sa.Column(
            "enable_activity",
            sa.Boolean(),
            nullable=True,
            comment="Enable activity tools (create activity, recent activities)",
        ),
        sa.Column(
            "enable_post",
            sa.Boolean(),
            nullable=True,
            comment="Enable post tools (create post, get post, recent posts)",
        ),
        sa.Column(
            "enable_long_term_memory",
            sa.Boolean(),
            nullable=True,
            comment="Enable long-term memory for the agent",
        ),
        sa.Column(
            "sub_agents",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="List of sub-agent IDs or slugs",
        ),
        sa.Column(
            "sub_agent_prompt",
            sa.String(),
            nullable=True,
            comment="Additional instructions for sub-agents",
        ),
        sa.Column(
            "telegram_entrypoint_enabled",
            sa.Boolean(),
            nullable=True,
            comment="Whether the agent can receive events from Telegram",
        ),
        sa.Column(
            "telegram_entrypoint_prompt",
            sa.String(),
            nullable=True,
            comment="Extra prompt for telegram entrypoint",
        ),
        sa.Column(
            "telegram_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Telegram integration configuration settings",
        ),
        sa.Column(
            "discord_entrypoint_enabled",
            sa.Boolean(),
            nullable=True,
            comment="Whether the agent can receive events from Discord",
        ),
        sa.Column(
            "discord_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Discord integration configuration settings",
        ),
        sa.Column(
            "xmtp_entrypoint_prompt",
            sa.String(),
            nullable=True,
            comment="Extra prompt for xmtp entrypoint",
        ),
        sa.Column(
            "wechat_entrypoint_prompt",
            sa.String(),
            nullable=True,
            comment="Extra prompt for wechat entrypoint",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_agent_drafts_agent_owner",
        "agent_drafts",
        ["agent_id", "owner"],
        unique=False,
    )
    op.create_index(
        "idx_agent_drafts_agent_owner_created",
        "agent_drafts",
        ["agent_id", "owner", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_agent_drafts_created_at", "agent_drafts", ["created_at"], unique=False
    )
    op.create_table(
        "agent_posts",
        sa.Column(
            "id", sa.String(), nullable=False, comment="Unique identifier for the post"
        ),
        sa.Column(
            "agent_id",
            sa.String(),
            nullable=False,
            comment="ID of the agent who created the post",
        ),
        sa.Column("title", sa.String(), nullable=False, comment="Title of the post"),
        sa.Column(
            "cover", sa.String(), nullable=True, comment="URL of the cover image"
        ),
        sa.Column(
            "markdown",
            sa.String(),
            nullable=False,
            comment="Content of the post in markdown format",
        ),
        sa.Column("slug", sa.String(), nullable=True, comment="URL slug for the post"),
        sa.Column(
            "excerpt", sa.String(), nullable=True, comment="Short excerpt of the post"
        ),
        sa.Column(
            "tags", postgresql.ARRAY(sa.String()), nullable=True, comment="List of tags"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the post was created",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_posts_agent_id"), "agent_posts", ["agent_id"], unique=False
    )
    op.create_table(
        "agent_quotas",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("plan", sa.String(), nullable=False),
        sa.Column("message_count_total", sa.BigInteger(), nullable=False),
        sa.Column("message_limit_total", sa.BigInteger(), nullable=False),
        sa.Column("message_count_monthly", sa.BigInteger(), nullable=False),
        sa.Column("message_limit_monthly", sa.BigInteger(), nullable=False),
        sa.Column("message_count_daily", sa.BigInteger(), nullable=False),
        sa.Column("message_limit_daily", sa.BigInteger(), nullable=False),
        sa.Column("last_message_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("autonomous_count_total", sa.BigInteger(), nullable=False),
        sa.Column("autonomous_limit_total", sa.BigInteger(), nullable=False),
        sa.Column("autonomous_count_monthly", sa.BigInteger(), nullable=False),
        sa.Column("autonomous_limit_monthly", sa.BigInteger(), nullable=False),
        sa.Column("last_autonomous_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("twitter_count_total", sa.BigInteger(), nullable=False),
        sa.Column("twitter_limit_total", sa.BigInteger(), nullable=False),
        sa.Column("twitter_count_monthly", sa.BigInteger(), nullable=False),
        sa.Column("twitter_limit_monthly", sa.BigInteger(), nullable=False),
        sa.Column("twitter_count_daily", sa.BigInteger(), nullable=False),
        sa.Column("twitter_limit_daily", sa.BigInteger(), nullable=False),
        sa.Column("last_twitter_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "free_income_daily", sa.Numeric(precision=22, scale=4), nullable=False
        ),
        sa.Column("avg_action_cost", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column("min_action_cost", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column("max_action_cost", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column("low_action_cost", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column(
            "medium_action_cost", sa.Numeric(precision=22, scale=4), nullable=False
        ),
        sa.Column(
            "high_action_cost", sa.Numeric(precision=22, scale=4), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_tool_data",
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("tool", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("agent_id", "tool", "key"),
    )
    op.create_table(
        "agents",
        sa.Column(
            "id",
            sa.String(),
            nullable=False,
            comment="Unique identifier for the agent. Must be URL-safe, containing only lowercase letters, numbers, and hyphens",
        ),
        sa.Column(
            "slug",
            sa.String(length=60),
            nullable=True,
            comment="URL-friendly slug for the agent, immutable once set",
        ),
        sa.Column(
            "owner",
            sa.String(),
            nullable=True,
            comment="Owner identifier of the agent, used for access control",
        ),
        sa.Column(
            "team_id",
            sa.String(),
            nullable=True,
            comment="Team identifier of the agent, used for access control",
        ),
        sa.Column(
            "template_id",
            sa.String(),
            nullable=True,
            comment="Template identifier of the agent",
        ),
        sa.Column(
            "extra_prompt",
            sa.String(length=20000),
            nullable=True,
            comment="Only when the agent is created from a template.",
        ),
        sa.Column(
            "upstream_id",
            sa.String(),
            nullable=True,
            comment="Upstream reference ID for idempotent operations",
        ),
        sa.Column(
            "upstream_extra",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional data store for upstream use",
        ),
        sa.Column(
            "version", sa.String(), nullable=True, comment="Version hash of the agent"
        ),
        sa.Column(
            "statistics",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Statistics of the agent, update every 1 hour for query",
        ),
        sa.Column(
            "assets",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Assets of the agent, update every 1 hour for query",
        ),
        sa.Column(
            "account_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Account snapshot of the agent, update every 1 hour for query",
        ),
        sa.Column(
            "extra",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Other helper data fields for query, come from agent and agent data",
        ),
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
            comment="Description of the agent, for public view, not contained in prompt",
        ),
        sa.Column(
            "external_website",
            sa.String(),
            nullable=True,
            comment="Link of external website of the agent, if you have one",
        ),
        sa.Column(
            "ticker", sa.String(), nullable=True, comment="Ticker symbol of the agent"
        ),
        sa.Column(
            "token_address",
            sa.String(),
            nullable=True,
            comment="Token address of the agent",
        ),
        sa.Column(
            "token_pool", sa.String(), nullable=True, comment="Pool of the agent token"
        ),
        sa.Column(
            "fee_percentage",
            sa.Numeric(precision=22, scale=4),
            nullable=True,
            comment="Fee percentage of the agent",
        ),
        sa.Column(
            "example_intro",
            sa.String(),
            nullable=True,
            comment="Introduction for example interactions",
        ),
        sa.Column(
            "examples",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="List of example interactions for the agent",
        ),
        sa.Column(
            "tags",
            postgresql.ARRAY(sa.String()),
            nullable=True,
            comment="Tags for categorizing the agent",
        ),
        sa.Column(
            "public_extra",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Public extra data of the agent",
        ),
        sa.Column(
            "deployed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the agent was deployed",
        ),
        sa.Column(
            "public_info_updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the agent public info was last updated",
        ),
        sa.Column(
            "x402_price", sa.Float(), nullable=True, comment="Price of the x402 request"
        ),
        sa.Column(
            "visibility",
            sa.Integer(),
            nullable=True,
            comment="Visibility level: 0=private, 10=team, 20=public",
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the agent was archived. NULL means not archived",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the agent was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the agent was last updated",
        ),
        sa.Column(
            "name", sa.String(), nullable=True, comment="Display name of the agent"
        ),
        sa.Column(
            "picture", sa.String(), nullable=True, comment="Picture of the agent"
        ),
        sa.Column(
            "purpose",
            sa.String(),
            nullable=True,
            comment="Purpose or role of the agent",
        ),
        sa.Column(
            "personality",
            sa.String(),
            nullable=True,
            comment="Personality traits of the agent",
        ),
        sa.Column(
            "principles",
            sa.String(),
            nullable=True,
            comment="Principles or values of the agent",
        ),
        sa.Column(
            "model",
            sa.String(),
            nullable=False,
            comment="AI model identifier to be used by this agent for processing requests.",
        ),
        sa.Column(
            "prompt",
            sa.String(),
            nullable=True,
            comment="Base system prompt that defines the agent's behavior and capabilities",
        ),
        sa.Column(
            "prompt_append",
            sa.String(),
            nullable=True,
            comment="Additional system prompt that has higher priority than the base prompt",
        ),
        sa.Column(
            "temperature",
            sa.Float(),
            nullable=True,
            comment="Controls response randomness (0.0~2.0). Higher values increase creativity but may reduce accuracy. For rigorous tasks, use lower values.",
        ),
        sa.Column(
            "frequency_penalty",
            sa.Float(),
            nullable=True,
            comment="Controls repetition in responses (-2.0~2.0). Higher values reduce repetition, lower values allow more repetition.",
        ),
        sa.Column(
            "presence_penalty",
            sa.Float(),
            nullable=True,
            comment="Controls topic adherence (-2.0~2.0). Higher values allow more topic deviation, lower values enforce stricter topic adherence.",
        ),
        sa.Column(
            "wallet_provider",
            sa.String(),
            nullable=True,
            comment="Provider of the agent's wallet",
        ),
        sa.Column(
            "readonly_wallet_address",
            sa.String(),
            nullable=True,
            comment="Readonly wallet address of the agent",
        ),
        sa.Column(
            "weekly_spending_limit",
            sa.Float(),
            nullable=True,
            comment="Weekly spending limit in USDC when wallet_provider is safe",
        ),
        sa.Column(
            "network_id", sa.String(), nullable=True, comment="Network identifier"
        ),
        sa.Column(
            "tools",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Dict of tools and their corresponding configurations",
        ),
        sa.Column(
            "search_internet",
            sa.Boolean(),
            nullable=True,
            comment="Enable LLM native internet search",
        ),
        sa.Column(
            "super_mode",
            sa.Boolean(),
            nullable=True,
            comment="Enable super mode with higher recursion limit",
        ),
        sa.Column(
            "enable_todo",
            sa.Boolean(),
            nullable=True,
            comment="Enable todo list middleware for task planning and tracking",
        ),
        sa.Column(
            "enable_activity",
            sa.Boolean(),
            nullable=True,
            comment="Enable activity tools (create activity, recent activities)",
        ),
        sa.Column(
            "enable_post",
            sa.Boolean(),
            nullable=True,
            comment="Enable post tools (create post, get post, recent posts)",
        ),
        sa.Column(
            "enable_long_term_memory",
            sa.Boolean(),
            nullable=True,
            comment="Enable long-term memory for the agent",
        ),
        sa.Column(
            "sub_agents",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="List of sub-agent IDs or slugs",
        ),
        sa.Column(
            "sub_agent_prompt",
            sa.String(),
            nullable=True,
            comment="Additional instructions for sub-agents",
        ),
        sa.Column(
            "telegram_entrypoint_enabled",
            sa.Boolean(),
            nullable=True,
            comment="Whether the agent can receive events from Telegram",
        ),
        sa.Column(
            "telegram_entrypoint_prompt",
            sa.String(),
            nullable=True,
            comment="Extra prompt for telegram entrypoint",
        ),
        sa.Column(
            "telegram_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Telegram integration configuration settings",
        ),
        sa.Column(
            "discord_entrypoint_enabled",
            sa.Boolean(),
            nullable=True,
            comment="Whether the agent can receive events from Discord",
        ),
        sa.Column(
            "discord_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Discord integration configuration settings",
        ),
        sa.Column(
            "xmtp_entrypoint_prompt",
            sa.String(),
            nullable=True,
            comment="Extra prompt for xmtp entrypoint",
        ),
        sa.Column(
            "wechat_entrypoint_prompt",
            sa.String(),
            nullable=True,
            comment="Extra prompt for wechat entrypoint",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agents_slug"), "agents", ["slug"], unique=True)
    op.create_index(
        op.f("ix_agents_upstream_id"), "agents", ["upstream_id"], unique=False
    )
    op.create_index(
        op.f("ix_agents_visibility"), "agents", ["visibility"], unique=False
    )
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "autonomous_executions",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column(
            "task_id",
            sa.String(length=20),
            nullable=False,
            comment="Autonomous task this execution belongs to",
        ),
        sa.Column(
            "team_id", sa.String(), nullable=False, comment="Team that owns the task"
        ),
        sa.Column(
            "agent_id",
            sa.String(),
            nullable=False,
            comment="Effective executor: target agent or synthetic team lead id",
        ),
        sa.Column(
            "target_agent_id",
            sa.String(),
            nullable=True,
            comment="Task target agent at run time; null means lead-orchestrated",
        ),
        sa.Column(
            "chat_id",
            sa.String(),
            nullable=False,
            comment="Chat thread the run's messages live in",
        ),
        sa.Column(
            "message_id",
            sa.String(),
            nullable=False,
            comment="Trigger chat message id; log messages reply_to this id",
        ),
        sa.Column(
            "trigger",
            sa.String(),
            nullable=False,
            comment="How the execution was triggered: cron/manual",
        ),
        sa.Column(
            "triggered_by",
            sa.String(),
            nullable=True,
            comment="User who triggered a manual run",
        ),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            comment="Execution status: running/success/error",
        ),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column(
            "result", sa.String(), nullable=True, comment="Truncated final agent reply"
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_input_tokens", sa.Integer(), nullable=False),
        sa.Column("credit_cost", sa.Numeric(precision=22, scale=4), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("cold_start_cost", sa.Float(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_autonomous_executions_task_id_id",
        "autonomous_executions",
        ["task_id", "id"],
        unique=False,
    )
    op.create_index(
        "uq_autonomous_executions_task_running",
        "autonomous_executions",
        ["task_id"],
        unique=True,
        postgresql_where=sa.text("status = 'running'"),
    )
    op.create_table(
        "autonomous_tasks",
        sa.Column("id", sa.String(length=20), nullable=False),
        sa.Column(
            "team_id",
            sa.String(),
            nullable=False,
            comment="Team that owns this autonomous task",
        ),
        sa.Column(
            "target_agent_id",
            sa.String(),
            nullable=True,
            comment="Optional agent to run directly; null means lead-orchestrated",
        ),
        sa.Column(
            "created_by",
            sa.String(),
            nullable=True,
            comment="User ID of the team member who created the task",
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "cron",
            sa.String(),
            nullable=False,
            comment="Cron expression for scheduling operations",
        ),
        sa.Column(
            "prompt",
            sa.String(),
            nullable=False,
            comment="Special prompt used during autonomous operation",
        ),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "has_memory", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "status",
            sa.String(),
            nullable=True,
            comment="Runtime status: waiting/running/error (scheduler-managed)",
        ),
        sa.Column(
            "next_run_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Next scheduled run time (scheduler-managed)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_autonomous_tasks_enabled", "autonomous_tasks", ["enabled"], unique=False
    )
    op.create_index(
        op.f("ix_autonomous_tasks_team_id"),
        "autonomous_tasks",
        ["team_id"],
        unique=False,
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("chat_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("author_id", sa.String(), nullable=False),
        sa.Column("author_type", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("thread_type", sa.String(), nullable=True),
        sa.Column("reply_to", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column(
            "attachments", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("tool_calls", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_input_tokens", sa.Integer(), nullable=False),
        sa.Column("time_cost", sa.Float(), nullable=False),
        sa.Column("credit_event_id", sa.String(), nullable=True),
        sa.Column("credit_cost", sa.Numeric(precision=22, scale=4), nullable=True),
        sa.Column("cold_start_cost", sa.Float(), nullable=False),
        sa.Column("thinking", sa.String(), nullable=True),
        sa.Column("app_id", sa.String(), nullable=True),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chat_messages_agent_id_author_type",
        "chat_messages",
        ["agent_id", "author_type"],
        unique=False,
    )
    op.create_index(
        "ix_chat_messages_agent_id_chat_id",
        "chat_messages",
        ["agent_id", "chat_id"],
        unique=False,
    )
    op.create_index(
        "ix_chat_messages_chat_id", "chat_messages", ["chat_id"], unique=False
    )
    op.create_table(
        "chat_tool_data",
        sa.Column("chat_id", sa.String(), nullable=False),
        sa.Column("tool", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("chat_id", "tool", "key"),
    )
    op.create_table(
        "chats",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("rounds", sa.Integer(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chats_agent_user", "chats", ["agent_id", "user_id"], unique=False
    )
    op.create_table(
        "credit_accounts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("owner_type", sa.String(), nullable=False),
        sa.Column("owner_id", sa.String(), nullable=False),
        sa.Column("free_quota", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column("refill_amount", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column("free_credits", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column("reward_credits", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column("credits", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column("income_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expense_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_event_id", sa.String(), nullable=True),
        sa.Column("total_income", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column(
            "total_free_income", sa.Numeric(precision=22, scale=4), nullable=False
        ),
        sa.Column(
            "total_reward_income", sa.Numeric(precision=22, scale=4), nullable=False
        ),
        sa.Column(
            "total_permanent_income", sa.Numeric(precision=22, scale=4), nullable=False
        ),
        sa.Column("total_expense", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column(
            "total_free_expense", sa.Numeric(precision=22, scale=4), nullable=False
        ),
        sa.Column(
            "total_reward_expense", sa.Numeric(precision=22, scale=4), nullable=False
        ),
        sa.Column(
            "total_permanent_expense", sa.Numeric(precision=22, scale=4), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_credit_accounts_owner",
        "credit_accounts",
        ["owner_type", "owner_id"],
        unique=False,
    )
    op.create_table(
        "credit_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("team_id", sa.String(), nullable=True),
        sa.Column("upstream_type", sa.String(), nullable=False),
        sa.Column("upstream_tx_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.Column("agent_wallet_address", sa.String(), nullable=True),
        sa.Column("start_message_id", sa.String(), nullable=True),
        sa.Column("message_id", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("tool_call_id", sa.String(), nullable=True),
        sa.Column("tool_name", sa.String(), nullable=True),
        sa.Column("direction", sa.String(), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column("credit_type", sa.String(), nullable=False),
        sa.Column("credit_types", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("balance_after", sa.Numeric(precision=22, scale=4), nullable=True),
        sa.Column("base_amount", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column(
            "base_discount_amount", sa.Numeric(precision=22, scale=4), nullable=True
        ),
        sa.Column(
            "base_original_amount", sa.Numeric(precision=22, scale=4), nullable=True
        ),
        sa.Column("base_llm_amount", sa.Numeric(precision=22, scale=4), nullable=True),
        sa.Column("base_tool_amount", sa.Numeric(precision=22, scale=4), nullable=True),
        sa.Column("base_free_amount", sa.Numeric(precision=22, scale=4), nullable=True),
        sa.Column(
            "base_reward_amount", sa.Numeric(precision=22, scale=4), nullable=True
        ),
        sa.Column(
            "base_permanent_amount", sa.Numeric(precision=22, scale=4), nullable=True
        ),
        sa.Column(
            "fee_platform_amount", sa.Numeric(precision=22, scale=4), nullable=True
        ),
        sa.Column(
            "fee_platform_free_amount", sa.Numeric(precision=22, scale=4), nullable=True
        ),
        sa.Column(
            "fee_platform_reward_amount",
            sa.Numeric(precision=22, scale=4),
            nullable=True,
        ),
        sa.Column(
            "fee_platform_permanent_amount",
            sa.Numeric(precision=22, scale=4),
            nullable=True,
        ),
        sa.Column("fee_dev_account", sa.String(), nullable=True),
        sa.Column("fee_dev_amount", sa.Numeric(precision=22, scale=4), nullable=True),
        sa.Column(
            "fee_dev_free_amount", sa.Numeric(precision=22, scale=4), nullable=True
        ),
        sa.Column(
            "fee_dev_reward_amount", sa.Numeric(precision=22, scale=4), nullable=True
        ),
        sa.Column(
            "fee_dev_permanent_amount", sa.Numeric(precision=22, scale=4), nullable=True
        ),
        sa.Column("fee_agent_account", sa.String(), nullable=True),
        sa.Column("fee_agent_amount", sa.Numeric(precision=22, scale=4), nullable=True),
        sa.Column(
            "fee_agent_free_amount", sa.Numeric(precision=22, scale=4), nullable=True
        ),
        sa.Column(
            "fee_agent_reward_amount", sa.Numeric(precision=22, scale=4), nullable=True
        ),
        sa.Column(
            "fee_agent_permanent_amount",
            sa.Numeric(precision=22, scale=4),
            nullable=True,
        ),
        sa.Column("free_amount", sa.Numeric(precision=22, scale=4), nullable=True),
        sa.Column("reward_amount", sa.Numeric(precision=22, scale=4), nullable=True),
        sa.Column("permanent_amount", sa.Numeric(precision=22, scale=4), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_credit_events_account_id", "credit_events", ["account_id"], unique=False
    )
    op.create_index(
        "ix_credit_events_agent_id", "credit_events", ["agent_id"], unique=False
    )
    op.create_index(
        "ix_credit_events_created_at", "credit_events", ["created_at"], unique=False
    )
    op.create_index(
        "ix_credit_events_fee_dev", "credit_events", ["fee_dev_account"], unique=False
    )
    op.create_index(
        "ix_credit_events_upstream",
        "credit_events",
        ["upstream_type", "upstream_tx_id"],
        unique=True,
    )
    op.create_index(
        "ix_credit_events_user_id", "credit_events", ["user_id"], unique=False
    )
    op.create_table(
        "credit_price_logs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("price_id", sa.String(), nullable=False),
        sa.Column("old_price", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column("new_price", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("modified_by", sa.String(), nullable=False),
        sa.Column(
            "modified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "credit_prices",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("price_entity", sa.String(), nullable=False),
        sa.Column("price_entity_id", sa.String(), nullable=False),
        sa.Column("discount_type", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "credit_transactions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("tx_type", sa.String(), nullable=False),
        sa.Column("credit_debit", sa.String(), nullable=False),
        sa.Column("change_amount", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column("free_amount", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column("reward_amount", sa.Numeric(precision=22, scale=4), nullable=False),
        sa.Column(
            "permanent_amount", sa.Numeric(precision=22, scale=4), nullable=False
        ),
        sa.Column("credit_type", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_credit_transactions_account",
        "credit_transactions",
        ["account_id"],
        unique=False,
    )
    op.create_index(
        "ix_credit_transactions_event_id",
        "credit_transactions",
        ["event_id"],
        unique=False,
    )
    op.create_table(
        "share_links",
        sa.Column(
            "id",
            sa.String(),
            nullable=False,
            comment="Unique identifier for the share link",
        ),
        sa.Column(
            "target_type",
            sa.String(),
            nullable=False,
            comment="Type of the shared target (chat or post)",
        ),
        sa.Column(
            "target_id", sa.String(), nullable=False, comment="ID of the shared target"
        ),
        sa.Column(
            "agent_id",
            sa.String(),
            nullable=False,
            comment="ID of the agent associated with the target",
        ),
        sa.Column(
            "user_id",
            sa.String(),
            nullable=True,
            comment="User who created the link; NULL for agent-initiated links",
        ),
        sa.Column(
            "team_id",
            sa.String(),
            nullable=True,
            comment="Team in which the link was created; NULL for agent-initiated links",
        ),
        sa.Column(
            "view_count",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Number of times the share link has been viewed via the public API",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the share link was created",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the share link expires",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_share_links_expires_at", "share_links", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_share_links_target",
        "share_links",
        ["target_type", "target_id", "agent_id", "expires_at"],
        unique=False,
    )
    op.create_table(
        "team_activity_feed",
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("activity_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("team_id", "activity_id"),
    )
    op.create_index(
        "ix_team_activity_feed_team_created",
        "team_activity_feed",
        ["team_id", "created_at"],
        unique=False,
    )
    # team_channel_chats / team_channel_data / team_channels are created in the
    # channel-centralization migration (next revision), not the baseline.
    op.create_table(
        "team_invites",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("invited_by", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("use_count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        "ix_team_invites_team_id", "team_invites", ["team_id"], unique=False
    )
    op.create_table(
        "team_members",
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("team_id", "user_id"),
    )
    op.create_index(
        "ix_team_members_user_team",
        "team_members",
        ["user_id", "team_id"],
        unique=False,
    )
    op.create_table(
        "team_post_feed",
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("post_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("team_id", "post_id"),
    )
    op.create_index(
        "ix_team_post_feed_team_created",
        "team_post_feed",
        ["team_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "team_subscriptions",
        sa.Column("team_id", sa.String(), nullable=False),
        sa.Column("agent_id", sa.String(), nullable=False),
        sa.Column(
            "subscribed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("team_id", "agent_id"),
    )
    op.create_index(
        op.f("ix_team_subscriptions_agent_id"),
        "team_subscriptions",
        ["agent_id"],
        unique=False,
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("default_channel", sa.String(), nullable=True),
        sa.Column("default_channel_chat_id", sa.String(), nullable=True),
        sa.Column("plan", sa.String(), server_default="none", nullable=False),
        sa.Column(
            "public_agent_limit",
            sa.Integer(),
            server_default="1",
            nullable=False,
            comment="Maximum number of agents this team is allowed to publish",
        ),
        sa.Column("plan_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_credit_issue_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "lead_agent",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Persisted lead agent config (name, avatar, personality)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "templates",
        sa.Column(
            "id",
            sa.String(),
            nullable=False,
            comment="Unique identifier for the template",
        ),
        sa.Column(
            "owner",
            sa.String(),
            nullable=True,
            comment="Owner identifier of the template, used for access control",
        ),
        sa.Column(
            "team_id",
            sa.String(),
            nullable=True,
            comment="Team identifier of the template, used for access control",
        ),
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
            comment="Description of the template",
        ),
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=True,
            comment="Display name of the template",
        ),
        sa.Column(
            "picture", sa.String(), nullable=True, comment="Avatar of the template"
        ),
        sa.Column(
            "purpose",
            sa.String(),
            nullable=True,
            comment="Purpose or role of the template",
        ),
        sa.Column(
            "personality",
            sa.String(),
            nullable=True,
            comment="Personality traits of the template",
        ),
        sa.Column(
            "principles",
            sa.String(),
            nullable=True,
            comment="Principles or values of the template",
        ),
        sa.Column("model", sa.String(), nullable=False, comment="LLM of the template"),
        sa.Column(
            "prompt",
            sa.String(),
            nullable=True,
            comment="Base system prompt that defines the template's behavior and capabilities",
        ),
        sa.Column(
            "prompt_append",
            sa.String(),
            nullable=True,
            comment="Additional system prompt that has higher priority than the base prompt",
        ),
        sa.Column(
            "temperature",
            sa.Float(),
            nullable=True,
            comment="The randomness of the generated results (0.0~2.0)",
        ),
        sa.Column(
            "frequency_penalty",
            sa.Float(),
            nullable=True,
            comment="The frequency penalty (-2.0~2.0)",
        ),
        sa.Column(
            "presence_penalty",
            sa.Float(),
            nullable=True,
            comment="The presence penalty (-2.0~2.0)",
        ),
        sa.Column(
            "wallet_provider",
            sa.String(),
            nullable=True,
            comment="Provider of the template's wallet",
        ),
        sa.Column(
            "network_id", sa.String(), nullable=True, comment="Network identifier"
        ),
        sa.Column(
            "tools",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Dict of tools and their corresponding configurations",
        ),
        sa.Column(
            "search_internet",
            sa.Boolean(),
            nullable=True,
            comment="Enable LLM native internet search",
        ),
        sa.Column(
            "super_mode",
            sa.Boolean(),
            nullable=True,
            comment="Enable super mode with higher recursion limit",
        ),
        sa.Column(
            "enable_todo",
            sa.Boolean(),
            nullable=True,
            comment="Enable todo list middleware for task planning and tracking",
        ),
        sa.Column(
            "enable_activity",
            sa.Boolean(),
            nullable=True,
            comment="Enable activity tools (create activity, recent activities)",
        ),
        sa.Column(
            "enable_post",
            sa.Boolean(),
            nullable=True,
            comment="Enable post tools (create post, get post, recent posts)",
        ),
        sa.Column(
            "enable_long_term_memory",
            sa.Boolean(),
            nullable=True,
            comment="Enable long-term memory for the agent",
        ),
        sa.Column(
            "sub_agents",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="List of sub-agent IDs or slugs that this agent can call",
        ),
        sa.Column(
            "sub_agent_prompt",
            sa.String(),
            nullable=True,
            comment="Additional instructions for how to use sub-agents",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the template was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when the template was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_data",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", "key"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("nft_count", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("x_username", sa.String(), nullable=True),
        sa.Column("github_username", sa.String(), nullable=True),
        sa.Column("telegram_username", sa.String(), nullable=True),
        sa.Column("telegram_id", sa.String(), nullable=True),
        sa.Column("wechat_id", sa.String(), nullable=True),
        # lark_id / slack_id columns + indexes are added in the channel-centralization
        # migration (next revision), not the baseline.
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("evm_wallet_address", sa.String(), nullable=True),
        sa.Column("solana_wallet_address", sa.String(), nullable=True),
        sa.Column("server_wallet_address", sa.String(), nullable=True),
        sa.Column(
            "linked_accounts", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("current_team_id", sa.String(), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_telegram_id", "users", ["telegram_id"], unique=False)
    op.create_index(
        "ix_users_telegram_username", "users", ["telegram_username"], unique=False
    )
    op.create_index("ix_users_wechat_id", "users", ["wechat_id"], unique=False)
    op.create_index("ix_users_x_username", "users", ["x_username"], unique=False)
    op.create_table(
        "x402_orders",
        sa.Column(
            "id", sa.String(), nullable=False, comment="Unique identifier for the order"
        ),
        sa.Column(
            "agent_id",
            sa.String(),
            nullable=False,
            comment="Agent that initiated the transaction",
        ),
        sa.Column(
            "chat_id", sa.String(), nullable=False, comment="Chat/conversation ID"
        ),
        sa.Column(
            "user_id", sa.String(), nullable=True, comment="User ID from context"
        ),
        sa.Column("task_id", sa.String(), nullable=True, comment="Autonomous task ID"),
        sa.Column("tool_name", sa.String(), nullable=False, comment="Tool name"),
        sa.Column("method", sa.String(), nullable=False, comment="HTTP method"),
        sa.Column("url", sa.String(), nullable=False, comment="Target URL"),
        sa.Column(
            "max_value", sa.BigInteger(), nullable=True, comment="Max payment limit"
        ),
        sa.Column(
            "amount",
            sa.BigInteger(),
            nullable=False,
            comment="Payment amount in base units",
        ),
        sa.Column("asset", sa.String(), nullable=False, comment="Payment asset"),
        sa.Column("network", sa.String(), nullable=False, comment="Payment network"),
        sa.Column("pay_to", sa.String(), nullable=False, comment="Recipient address"),
        sa.Column("payer", sa.String(), nullable=True, comment="Payer address"),
        sa.Column("tx_hash", sa.String(), nullable=True, comment="Transaction hash"),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            comment="Status: pending, success, failed",
        ),
        sa.Column("error", sa.String(), nullable=True, comment="Error message"),
        sa.Column(
            "http_status",
            sa.Integer(),
            nullable=True,
            comment="HTTP response status code",
        ),
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
            comment="Payment description from x402 protocol",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Timestamp when created",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_x402_orders_agent_id"), "x402_orders", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_x402_orders_chat_id"), "x402_orders", ["chat_id"], unique=False
    )
    op.create_index(
        op.f("ix_x402_orders_created_at"), "x402_orders", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_x402_orders_status"), "x402_orders", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_x402_orders_status"), table_name="x402_orders")
    op.drop_index(op.f("ix_x402_orders_created_at"), table_name="x402_orders")
    op.drop_index(op.f("ix_x402_orders_chat_id"), table_name="x402_orders")
    op.drop_index(op.f("ix_x402_orders_agent_id"), table_name="x402_orders")
    op.drop_table("x402_orders")
    op.drop_index("ix_users_x_username", table_name="users")
    op.drop_index("ix_users_wechat_id", table_name="users")
    op.drop_index("ix_users_telegram_username", table_name="users")
    op.drop_index("ix_users_telegram_id", table_name="users")
    op.drop_table("users")
    op.drop_table("user_data")
    op.drop_table("templates")
    op.drop_table("teams")
    op.drop_index(
        op.f("ix_team_subscriptions_agent_id"), table_name="team_subscriptions"
    )
    op.drop_table("team_subscriptions")
    op.drop_index("ix_team_post_feed_team_created", table_name="team_post_feed")
    op.drop_table("team_post_feed")
    op.drop_index("ix_team_members_user_team", table_name="team_members")
    op.drop_table("team_members")
    op.drop_index("ix_team_invites_team_id", table_name="team_invites")
    op.drop_table("team_invites")
    op.drop_index("ix_team_activity_feed_team_created", table_name="team_activity_feed")
    op.drop_table("team_activity_feed")
    op.drop_index("ix_share_links_target", table_name="share_links")
    op.drop_index("ix_share_links_expires_at", table_name="share_links")
    op.drop_table("share_links")
    op.drop_index("ix_credit_transactions_event_id", table_name="credit_transactions")
    op.drop_index("ix_credit_transactions_account", table_name="credit_transactions")
    op.drop_table("credit_transactions")
    op.drop_table("credit_prices")
    op.drop_table("credit_price_logs")
    op.drop_index("ix_credit_events_user_id", table_name="credit_events")
    op.drop_index("ix_credit_events_upstream", table_name="credit_events")
    op.drop_index("ix_credit_events_fee_dev", table_name="credit_events")
    op.drop_index("ix_credit_events_created_at", table_name="credit_events")
    op.drop_index("ix_credit_events_agent_id", table_name="credit_events")
    op.drop_index("ix_credit_events_account_id", table_name="credit_events")
    op.drop_table("credit_events")
    op.drop_index("ix_credit_accounts_owner", table_name="credit_accounts")
    op.drop_table("credit_accounts")
    op.drop_index("ix_chats_agent_user", table_name="chats")
    op.drop_table("chats")
    op.drop_table("chat_tool_data")
    op.drop_index("ix_chat_messages_chat_id", table_name="chat_messages")
    op.drop_index("ix_chat_messages_agent_id_chat_id", table_name="chat_messages")
    op.drop_index("ix_chat_messages_agent_id_author_type", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_autonomous_tasks_team_id"), table_name="autonomous_tasks")
    op.drop_index("ix_autonomous_tasks_enabled", table_name="autonomous_tasks")
    op.drop_table("autonomous_tasks")
    op.drop_index(
        "uq_autonomous_executions_task_running",
        table_name="autonomous_executions",
        postgresql_where=sa.text("status = 'running'"),
    )
    op.drop_index(
        "ix_autonomous_executions_task_id_id", table_name="autonomous_executions"
    )
    op.drop_table("autonomous_executions")
    op.drop_table("app_settings")
    op.drop_index(op.f("ix_agents_visibility"), table_name="agents")
    op.drop_index(op.f("ix_agents_upstream_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_slug"), table_name="agents")
    op.drop_table("agents")
    op.drop_table("agent_tool_data")
    op.drop_table("agent_quotas")
    op.drop_index(op.f("ix_agent_posts_agent_id"), table_name="agent_posts")
    op.drop_table("agent_posts")
    op.drop_index("idx_agent_drafts_created_at", table_name="agent_drafts")
    op.drop_index("idx_agent_drafts_agent_owner_created", table_name="agent_drafts")
    op.drop_index("idx_agent_drafts_agent_owner", table_name="agent_drafts")
    op.drop_table("agent_drafts")
    op.drop_table("agent_data")
    op.drop_index(op.f("ix_agent_activities_post_id"), table_name="agent_activities")
    op.drop_index(op.f("ix_agent_activities_agent_id"), table_name="agent_activities")
    op.drop_table("agent_activities")
    # ### end Alembic commands ###
