# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""ATIF v1.7 Pydantic models — schema + serializer + validator.

Mirrors the spec at ``0001-trajectory-format-2.md`` §II "Schema".

These models are the canonical in-memory representation of an ATIF
trajectory. The exporter assembles instances of these, and downstream
consumers (validators, dashboards, SFT pipelines) parse JSON into them
via ``Trajectory.model_validate_json(...)``.

Validation is intentionally structural-only at this layer: schema-level
required fields, enum values, conditional fields (e.g. ``ContentPart``
text vs image, ``SubagentTrajectoryRef`` resolution mechanism).
Normative cross-cutting rules (sequential step_ids, joinability,
context-management boundary semantics, ``is_copied_context``
propagation) are enforced separately in :mod:`tests.atif.test_normative_rules`
and at exporter build-time.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

SCHEMA_VERSION: Literal["ATIF-v1.7"] = "ATIF-v1.7"


# ---------------------------------------------------------------------------
# Leaf schemas
# ---------------------------------------------------------------------------


class ImageSource(BaseModel):
    """Image storage reference for multimodal content (spec §II ImageSourceSchema, v1.6+)."""

    model_config = ConfigDict(extra="forbid")

    media_type: Literal["image/jpeg", "image/png", "image/gif", "image/webp"] = Field(
        description="MIME type of the image."
    )
    path: str = Field(description="Location of the image. Relative path, absolute path, or URL.")


class ContentPart(BaseModel):
    """Multimodal content part (spec §II ContentPartSchema, v1.6+).

    ``type='text'`` requires ``text`` and forbids ``source``;
    ``type='image'`` requires ``source`` and forbids ``text``.
    """

    model_config = ConfigDict(extra="forbid")

    type: Literal["text", "image"] = Field(description="Content kind.")
    text: str | None = Field(default=None, description="Text content (type=text only).")
    source: ImageSource | None = Field(default=None, description="Image source (type=image only).")

    @model_validator(mode="after")
    def _check_conditional_fields(self) -> ContentPart:
        if self.type == "text":
            if self.text is None:
                raise ValueError("ContentPart.type='text' requires `text`")
            if self.source is not None:
                raise ValueError("ContentPart.type='text' must omit `source`")
        else:  # image
            if self.source is None:
                raise ValueError("ContentPart.type='image' requires `source`")
            if self.text is not None:
                raise ValueError("ContentPart.type='image' must omit `text`")
        return self


# ---------------------------------------------------------------------------
# Metrics schemas
# ---------------------------------------------------------------------------


class MetricsSchema(BaseModel):
    """Per-step LLM metrics (spec §II MetricsSchema). All fields optional."""

    model_config = ConfigDict(extra="forbid")

    prompt_tokens: int | None = Field(
        default=None,
        description=("Total input tokens (incl. cached and non-cached) for this step."),
    )
    completion_tokens: int | None = Field(
        default=None, description="Total tokens generated by the LLM for this step."
    )
    cached_tokens: int | None = Field(
        default=None, description="Subset of prompt_tokens served from cache."
    )
    cost_usd: float | None = Field(default=None, description="Monetary cost of this step in USD.")
    prompt_token_ids: list[int] | None = Field(
        default=None, description="Token ids for the prompt (length == prompt_tokens)."
    )
    completion_token_ids: list[int] | None = Field(
        default=None,
        description="Token ids for the completion (length == completion_tokens).",
    )
    logprobs: list[float] | None = Field(
        default=None, description="Log probabilities aligned with completion_token_ids."
    )
    extra: dict[str, Any] | None = Field(
        default=None,
        description="Provider-specific metrics (e.g. reasoning_tokens, cache_creation_input_tokens).",
    )


class FinalMetricsSchema(BaseModel):
    """Trajectory-aggregate metrics (spec §II FinalMetricsSchema). All optional."""

    model_config = ConfigDict(extra="forbid")

    total_prompt_tokens: int | None = None
    total_completion_tokens: int | None = None
    total_cached_tokens: int | None = None
    total_cost_usd: float | None = None
    total_steps: int | None = None
    extra: dict[str, Any] | None = None


# ---------------------------------------------------------------------------
# Tool-call + observation schemas
# ---------------------------------------------------------------------------


class ToolCallSchema(BaseModel):
    """A single tool invocation by the agent (spec §II ToolCallSchema)."""

    model_config = ConfigDict(extra="forbid")

    tool_call_id: str = Field(
        description="Unique id; joins to ObservationResultSchema.source_call_id."
    )
    function_name: str = Field(description="Name of the tool/function invoked.")
    arguments: dict[str, Any] = Field(description="Arguments JSON object (may be empty).")
    extra: dict[str, Any] | None = Field(
        default=None, description="Custom tool-call metadata (v1.7)."
    )


class SubagentTrajectoryRef(BaseModel):
    """Reference to a delegated subagent trajectory (spec §II SubagentTrajectoryRefSchema)."""

    model_config = ConfigDict(extra="forbid")

    trajectory_id: str | None = Field(
        default=None,
        description=(
            "Canonical id for an embedded subagent trajectory; resolves "
            "against root.subagent_trajectories[].trajectory_id (v1.7)."
        ),
    )
    trajectory_path: str | None = Field(
        default=None,
        description="External-file reference (path, URL, DB ref) to a subagent trajectory.",
    )
    session_id: str | None = Field(
        default=None,
        description=(
            "Run-scoped session id of the subagent. **Informational only** in v1.7 — "
            "NOT a resolution key (see spec §II)."
        ),
    )
    extra: dict[str, Any] | None = None

    @model_validator(mode="after")
    def _check_at_least_one_resolver(self) -> SubagentTrajectoryRef:
        if self.trajectory_id is None and self.trajectory_path is None:
            raise ValueError(
                "SubagentTrajectoryRef MUST set at least one of "
                "trajectory_id (embedded) or trajectory_path (external) "
                "(spec §II v1.7)."
            )
        return self


class ObservationResultSchema(BaseModel):
    """One result entry within an Observation (spec §II ObservationResultSchema)."""

    model_config = ConfigDict(extra="forbid")

    source_call_id: str | None = Field(
        default=None,
        description=(
            "Joins back to ToolCallSchema.tool_call_id in the same step. "
            "Null when the result has no associated tool call."
        ),
    )
    content: str | list[ContentPart] | None = Field(
        default=None,
        description=(
            "Tool/action output. Text-only (string) or multimodal "
            "(list[ContentPart], v1.6+). MAY be omitted if "
            "subagent_trajectory_ref is set."
        ),
    )
    subagent_trajectory_ref: list[SubagentTrajectoryRef] | None = Field(
        default=None,
        description="References to delegated subagent trajectories.",
    )
    extra: dict[str, Any] | None = None


class ObservationSchema(BaseModel):
    """Wrapper around the results array (spec §II ObservationSchema)."""

    model_config = ConfigDict(extra="forbid")

    results: list[ObservationResultSchema] = Field(
        description="Array of result entries (one per tool call or action)."
    )


# ---------------------------------------------------------------------------
# Agent and step schemas
# ---------------------------------------------------------------------------


class AgentSchema(BaseModel):
    """Agent identity at trajectory root (spec §II AgentSchema)."""

    model_config = ConfigDict(extra="forbid")

    name: str = Field(description="Agent system name.")
    version: str = Field(description="Agent system version.")
    model_name: str | None = Field(
        default=None,
        description="Default LLM model for the trajectory (step-level overrides).",
    )
    tool_definitions: list[dict[str, Any]] | None = Field(
        default=None,
        description="OpenAI-style function definitions (each: {type, function}).",
    )
    extra: dict[str, Any] | None = None


class StepObject(BaseModel):
    """One step in the trajectory (spec §II StepObject)."""

    model_config = ConfigDict(extra="forbid")

    step_id: int = Field(description="Ordinal index starting from 1.")
    timestamp: str | None = Field(
        default=None, description="ISO 8601 timestamp (e.g. '2025-10-16T14:30:00Z')."
    )
    source: Literal["system", "user", "agent"] = Field(description="Step originator.")
    model_name: str | None = Field(
        default=None,
        description="Per-step LLM model override. Only on source='agent'.",
    )
    reasoning_effort: str | float | None = Field(
        default=None, description="Effort level (low/medium/high or float). Only on source='agent'."
    )
    message: str | list[ContentPart] = Field(
        description="Dialogue message. May be empty string. Required."
    )
    reasoning_content: str | None = Field(
        default=None, description="Explicit internal reasoning. Only on source='agent'."
    )
    tool_calls: list[ToolCallSchema] | None = Field(
        default=None,
        description="Structured tool calls for this turn. Only on source='agent'.",
    )
    observation: ObservationSchema | None = Field(
        default=None,
        description="Environment feedback / tool results for this step.",
    )
    metrics: MetricsSchema | None = Field(
        default=None, description="LLM metrics. Only on source='agent'."
    )
    extra: dict[str, Any] | None = None
    llm_call_count: int | None = Field(
        default=None,
        description=(
            "Number of LLM inferences this step represents. "
            "1 = normal; >1 = aggregated; 0 on source='agent' = deterministic dispatch "
            "(metrics + reasoning_content MUST be absent). Null = not tracked."
        ),
    )
    is_copied_context: bool | None = Field(
        default=None,
        description=(
            "True iff this step was retained across a compaction boundary "
            "(SFT consumers MUST filter out)."
        ),
    )

    @model_validator(mode="after")
    def _check_agent_only_fields(self) -> StepObject:
        """Spec §II: model_name / reasoning_effort / reasoning_content /
        tool_calls / metrics are agent-only."""
        if self.source != "agent":
            for field_name in (
                "model_name",
                "reasoning_effort",
                "reasoning_content",
                "tool_calls",
                "metrics",
            ):
                if getattr(self, field_name) is not None:
                    raise ValueError(
                        f"StepObject.{field_name} is only applicable when source='agent' "
                        f"(got source={self.source!r})."
                    )
        return self

    @model_validator(mode="after")
    def _check_deterministic_dispatch(self) -> StepObject:
        """Spec §II: llm_call_count=0 on source='agent' ⇒ metrics + reasoning_content absent."""
        if (
            self.source == "agent"
            and self.llm_call_count == 0
            and (self.metrics is not None or self.reasoning_content is not None)
        ):
            raise ValueError(
                "StepObject.llm_call_count=0 on source='agent' (deterministic dispatch) "
                "requires `metrics` and `reasoning_content` to be absent (spec §II)."
            )
        return self


# ---------------------------------------------------------------------------
# Trajectory root
# ---------------------------------------------------------------------------


class Trajectory(BaseModel):
    """ATIF root document (spec §II Root-Level Metadata)."""

    model_config = ConfigDict(extra="forbid")

    schema_version: Literal["ATIF-v1.7"] = SCHEMA_VERSION
    session_id: str | None = Field(
        default=None,
        description=(
            "Run-scoped identifier (MAY be shared across sibling subagents / continuations). "
            "Optional in v1.7."
        ),
    )
    trajectory_id: str | None = Field(
        default=None,
        description=(
            "Per-document unique id. REQUIRED on embedded subagent entries; optional otherwise (v1.7)."
        ),
    )
    agent: AgentSchema = Field(description="Agent identity.")
    steps: list[StepObject] = Field(description="Sequential trajectory steps.")
    notes: str | None = Field(default=None, description="Developer-facing notes.")
    final_metrics: FinalMetricsSchema | None = Field(
        default=None, description="Aggregate metrics across the trajectory."
    )
    continued_trajectory_ref: str | None = Field(
        default=None,
        description="Reference to a continuation trajectory file (if split).",
    )
    extra: dict[str, Any] | None = None
    subagent_trajectories: list[Trajectory] | None = Field(
        default=None,
        description=(
            "Embedded subagent trajectories. Each entry MUST set trajectory_id; "
            "trajectory_ids within this array MUST be unique (spec §II v1.7)."
        ),
    )

    @model_validator(mode="after")
    def _check_subagent_uniqueness(self) -> Trajectory:
        """Spec §II: every embedded subagent MUST have trajectory_id; ids MUST be unique."""
        if self.subagent_trajectories:
            seen: set[str] = set()
            for child in self.subagent_trajectories:
                if not child.trajectory_id:
                    raise ValueError(
                        "Embedded subagent trajectory MUST set trajectory_id (spec §II v1.7)."
                    )
                if child.trajectory_id in seen:
                    raise ValueError(
                        f"Duplicate trajectory_id {child.trajectory_id!r} in "
                        "subagent_trajectories (spec §II v1.7)."
                    )
                seen.add(child.trajectory_id)
        return self


# Resolve forward reference for self-referential subagent_trajectories.
Trajectory.model_rebuild()
