"""Gödel Agent against `Arvid-pku/Godel_Agent@bbb50879`.

Its distinctive claim is recursive self-reference: the proposal that edits the
agent is generated by the agent's *own current* self-improvement prompt. And its
distinctive departure is the acceptance gate, which upstream does not have.
"""
from __future__ import annotations

import pytest

from examples.godel_agent import godel_agent_self_modify as ga


def _task():
    from examples._gsm8k_domain import gsm8k_splits
    return gsm8k_splits(0)[0][0]


def test_the_gateless_flag_exists_and_changes_the_acceptance_rule():
    """It was documented in five places -- this module's docstring, its README,
    `algo-godel-agent.md`, `acceptance-policies.md` and `matrix-overview.md` --
    and the parser rejected it outright with `unrecognized arguments`. The class
    was written and the `build` keyword was there; nothing could reach it.
    """
    assert ga.build(0).engine.acceptance is None
    assert isinstance(ga.build(0, gateless=True).engine.acceptance,
                      ga.AcceptAnyCompiling)

    # And it parses.
    assert ga.main(["--dry-run", "--gateless"]) == 0
    assert ga.main(["--dry-run"]) == 0


def test_the_banner_names_the_acceptance_rule_when_one_is_installed(capsys):
    """A switch that changes what a run accepts belongs in the run's own record,
    not only in the flag that set it."""
    ga.main(["--dry-run", "--gateless"])
    assert "acceptance=AcceptAnyCompiling" in capsys.readouterr().out
    ga.main(["--dry-run"])
    assert "acceptance=" not in capsys.readouterr().out


def test_accept_any_compiling_accepts_what_the_validator_let_through():
    """By the time a candidate reaches this gate it has already compiled under
    the AST gate, which is exactly upstream's situation: a monkey-patch that did
    not crash."""
    decision = ga.AcceptAnyCompiling().accept(object())
    assert decision.accept is True
    assert "gateless" in decision.detail


def test_the_proposal_is_written_by_the_artifacts_own_improvement_prompt():
    """The recursive self-reference the paper is about: an edit is produced by
    applying the agent's *current* `self_improvement_prompt` to its own source.
    A port that used a fixed meta-prompt would run the same loop without the
    property it exists to demonstrate."""
    policy = ga.build(0)
    source = ga.GODEL_INITIAL_SOURCE.replace(
        'return "Inspect and improve your complete policy source. Feedback:\\n"',
        'return "SENTINEL-FROM-THE-ARTIFACT " + "Feedback:\\n"')
    seen = {}

    def llm(prompt, **kw):
        seen["prompt"] = prompt
        return "```python\n" + ga.GODEL_INITIAL_SOURCE + "```"

    policy.propose(llm, source, _task(), "the answer is 5", 0.0)
    assert seen["prompt"].startswith("SENTINEL-FROM-THE-ARTIFACT"), (
        "the meta-prompt did not come from the artifact")


def test_both_functions_are_editable_and_the_surface_is_fixed():
    """`solve_prompt` alone would make it SICA. The self-improvement prompt has
    to be rewritable for the loop to be recursive."""
    assert ga._SURFACE == {"solve_prompt": 1, "self_improvement_prompt": 2}
    with pytest.raises(ValueError):
        ga._godel_source("```python\ndef solve_prompt(q):\n    return q\n```")


def test_an_unparseable_self_edit_proposes_nothing():
    policy = ga.build(0)
    state = {"policy": ga.GODEL_INITIAL_SOURCE}
    assert policy.strategy.to_diff(state, "not python", "w", 1, "a") is None
