#!/usr/bin/env python3
"""Generate multi-format outputs from a specialist definition.

Input: specialist directory containing agent.py and SKILL.md
Output: Python API, CLI tool, MCP server, Agent Skill package, REST wrapper

Usage:
    python scripts/generate_outputs.py agents/specialists/autoresearch/
    python scripts/generate_outputs.py agents/specialists/autoresearch/ --output-dir ./my_output
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Any

import yaml

# ---------------------------------------------------------------------------
# Metadata parsing
# ---------------------------------------------------------------------------


class SpecialistMetadata:
    """Parsed metadata from a specialist's SKILL.md frontmatter."""

    def __init__(self, data: dict[str, Any], specialist_dir: Path) -> None:
        self.name: str = data.get("name", specialist_dir.name)
        self.display_name: str = data.get("display_name", self.name.replace("_", " ").title())
        self.description: str = data.get("description", "No description provided.")
        self.version: str = data.get("version", "0.1.0")
        self.source_repo: str = data.get("source_repo", "unknown/unknown")
        self.license: str = data.get("license", "MIT")
        self.tier: str = data.get("tier", "experimental")
        self.capabilities: list[str] = data.get("capabilities", [])
        self.allowed_tools: list[str] = data.get("allowed_tools", [])
        self.output_formats: list[str] = data.get("output_formats", [])

        # Derived helpers used in templates
        self.class_name: str = _to_class_name(self.name)
        self.module_path: str = f"agents.specialists.{self.name}.agent"
        self.slug: str = self.name  # already snake_case


def _to_class_name(name: str) -> str:
    """Convert a snake_case name to a PascalCase class name."""
    return "".join(word.capitalize() for word in re.split(r"[_\-]", name)) + "Specialist"


def parse_skill_md(skill_md_path: Path) -> SpecialistMetadata:
    """Parse YAML frontmatter from a SKILL.md file.

    Args:
        skill_md_path: Path to the SKILL.md file.

    Returns:
        SpecialistMetadata populated from the frontmatter.

    Raises:
        FileNotFoundError: If the file does not exist.
        ValueError: If frontmatter is missing or malformed.
    """
    if not skill_md_path.exists():
        raise FileNotFoundError(f"SKILL.md not found: {skill_md_path}")

    raw = skill_md_path.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---", raw, re.DOTALL)
    if not match:
        raise ValueError(f"No YAML frontmatter found in {skill_md_path}")

    data: dict[str, Any] = yaml.safe_load(match.group(1)) or {}
    return SpecialistMetadata(data, skill_md_path.parent)


# ---------------------------------------------------------------------------
# Template generators
# ---------------------------------------------------------------------------


def _python_api_template(meta: SpecialistMetadata) -> str:
    """Generate a simple importable Python API module."""
    caps_list = ", ".join(f'"{c}"' for c in meta.capabilities)
    tools_list = ", ".join(f'"{t}"' for t in meta.allowed_tools)
    return f'''\
#!/usr/bin/env python3
"""Python API wrapper for the {meta.display_name}.

Auto-generated by generate_outputs.py — edit to taste.

Source: {meta.source_repo}
Version: {meta.version}
License: {meta.license}

Example:
    import asyncio
    from {meta.name} import run

    result = asyncio.run(run("your query here"))
    print(result)
"""
from __future__ import annotations

import asyncio
from typing import Any

# TODO: Adjust import path to match your project layout.
from {meta.module_path} import {meta.class_name}
from oss_agent_lab.contracts import Intent, Query, SpecialistRequest


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

SPECIALIST_NAME: str = "{meta.name}"
DISPLAY_NAME: str = "{meta.display_name}"
DESCRIPTION: str = "{meta.description}"
VERSION: str = "{meta.version}"
CAPABILITIES: list[str] = [{caps_list}]
ALLOWED_TOOLS: list[str] = [{tools_list}]


def run(
    query: str,
    action: str = "{meta.capabilities[0] if meta.capabilities else "run"}",
    domain: str = "general",
    parameters: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Run the {meta.display_name} synchronously.

    Args:
        query: The user query or topic.
        action: The intent action (one of: {", ".join(meta.capabilities)}).
        domain: The intent domain.
        parameters: Optional extra parameters forwarded to the specialist.

    Returns:
        The specialist result dict.
    """
    return asyncio.run(_run_async(query, action, domain, parameters))


async def run_async(
    query: str,
    action: str = "{meta.capabilities[0] if meta.capabilities else "run"}",
    domain: str = "general",
    parameters: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Run the {meta.display_name} asynchronously.

    Args:
        query: The user query or topic.
        action: The intent action.
        domain: The intent domain.
        parameters: Optional extra parameters.

    Returns:
        The specialist result dict.
    """
    return await _run_async(query, action, domain, parameters)


async def _run_async(
    query: str,
    action: str,
    domain: str,
    parameters: dict[str, Any] | None,
) -> dict[str, Any]:
    specialist = {meta.class_name}()
    request = SpecialistRequest(
        intent=Intent(action=action, domain=domain, confidence=1.0, parameters=parameters or {{}}),
        query=Query(user_input=query),
        specialist_name=SPECIALIST_NAME,
    )
    response = await specialist.execute(request)
    return response.result
'''


def _cli_template(meta: SpecialistMetadata) -> str:
    """Generate a Click-based CLI wrapper."""
    caps_help = " | ".join(meta.capabilities) if meta.capabilities else "run"
    return f'''\
#!/usr/bin/env python3
"""CLI wrapper for the {meta.display_name}.

Auto-generated by generate_outputs.py — edit to taste.

Usage:
    python {meta.slug}_cli.py run "your query here"
    python {meta.slug}_cli.py run "your query here" --action research --domain science
    python {meta.slug}_cli.py info
"""
from __future__ import annotations

import asyncio
import json
import sys
from typing import Any

import click

# TODO: Adjust import path to match your project layout.
from {meta.module_path} import {meta.class_name}
from oss_agent_lab.contracts import Intent, Query, SpecialistRequest


@click.group()
@click.version_option(version="{meta.version}", prog_name="{meta.slug}")
def cli() -> None:
    """{meta.display_name} — {meta.description}"""


@cli.command("run")
@click.argument("query")
@click.option(
    "--action",
    default="{meta.capabilities[0] if meta.capabilities else "run"}",
    show_default=True,
    help="Intent action ({caps_help}).",
)
@click.option("--domain", default="general", show_default=True, help="Intent domain.")
@click.option("--param", "-p", multiple=True, metavar="KEY=VALUE", help="Extra parameters.")
@click.option("--json-output", "json_output", is_flag=True, help="Output raw JSON.")
def cmd_run(
    query: str,
    action: str,
    domain: str,
    param: tuple[str, ...],
    json_output: bool,
) -> None:
    """Run the specialist on QUERY."""
    parameters: dict[str, Any] = {{}}
    for kv in param:
        if "=" not in kv:
            click.echo(f"ERROR: --param must be KEY=VALUE, got: {{kv!r}}", err=True)
            sys.exit(1)
        k, v = kv.split("=", 1)
        parameters[k] = v

    result = asyncio.run(_execute(query, action, domain, parameters))

    if json_output:
        click.echo(json.dumps(result, indent=2))
    else:
        # TODO: Replace with richer formatted output using rich/tabulate.
        click.echo(f"Result for '{{query}}':")
        click.echo(json.dumps(result, indent=2))


@cli.command("info")
def cmd_info() -> None:
    """Display specialist metadata."""
    click.echo(f"Name:         {meta.name}")
    click.echo(f"Display:      {meta.display_name}")
    click.echo(f"Version:      {meta.version}")
    click.echo(f"Source:       {meta.source_repo}")
    click.echo(f"Description:  {meta.description}")
    click.echo(f"Capabilities: {", ".join(meta.capabilities)}")
    click.echo(f"Tools:        {", ".join(meta.allowed_tools)}")


async def _execute(
    query: str,
    action: str,
    domain: str,
    parameters: dict[str, Any],
) -> dict[str, Any]:
    specialist = {meta.class_name}()
    request = SpecialistRequest(
        intent=Intent(action=action, domain=domain, confidence=1.0, parameters=parameters),
        query=Query(user_input=query),
        specialist_name="{meta.name}",
    )
    response = await specialist.execute(request)
    return response.result


if __name__ == "__main__":
    cli()
'''


def _mcp_template(meta: SpecialistMetadata) -> str:
    """Generate an MCP JSON-RPC server stub."""
    tool_registrations = "\n".join(
        f'''\
    {{
        "name": "{tool}",
        "description": "TODO: describe the {tool} tool",
        "inputSchema": {{
            "type": "object",
            "properties": {{
                "query": {{"type": "string", "description": "The input query"}},
            }},
            "required": ["query"],
        }},
    }},'''
        for tool in meta.allowed_tools
    )
    return f'''\
#!/usr/bin/env python3
"""MCP (Model Context Protocol) JSON-RPC server stub for {meta.display_name}.

Auto-generated by generate_outputs.py — edit to taste.

This stub implements the MCP wire protocol over stdio. Each tool defined in
SKILL.md is registered and dispatched to the underlying specialist.

Usage:
    python {meta.slug}_mcp.py

Protocol: https://modelcontextprotocol.io/specification
"""
from __future__ import annotations

import asyncio
import json
import logging
import sys
from typing import Any

# TODO: Adjust import path to match your project layout.
from {meta.module_path} import {meta.class_name}
from oss_agent_lab.contracts import Intent, Query, SpecialistRequest

logger = logging.getLogger("{meta.name}_mcp")

# ---------------------------------------------------------------------------
# Tool registry
# ---------------------------------------------------------------------------

TOOLS: list[dict[str, Any]] = [
{tool_registrations}
]

SPECIALIST_NAME = "{meta.name}"
SPECIALIST_VERSION = "{meta.version}"

# ---------------------------------------------------------------------------
# MCP JSON-RPC handler
# ---------------------------------------------------------------------------


class MCPServer:
    """Minimal MCP server over stdio (newline-delimited JSON)."""

    def __init__(self) -> None:
        self._specialist = {meta.class_name}()

    async def handle(self, message: dict[str, Any]) -> dict[str, Any] | None:
        """Dispatch an incoming JSON-RPC message and return the response."""
        method = message.get("method", "")
        msg_id = message.get("id")

        if method == "initialize":
            return self._ok(msg_id, {{
                "protocolVersion": "2024-11-05",
                "capabilities": {{"tools": {{}}}},
                "serverInfo": {{"name": SPECIALIST_NAME, "version": SPECIALIST_VERSION}},
            }})

        if method == "tools/list":
            return self._ok(msg_id, {{"tools": TOOLS}})

        if method == "tools/call":
            return await self._call_tool(msg_id, message.get("params", {{}}))

        if method == "notifications/initialized":
            return None  # no response for notifications

        return self._error(msg_id, -32601, f"Method not found: {{method}}")

    async def _call_tool(
        self, msg_id: int | str | None, params: dict[str, Any]
    ) -> dict[str, Any]:
        tool_name: str = params.get("name", "")
        arguments: dict[str, Any] = params.get("arguments", {{}})
        query: str = arguments.get("query", "")

        if tool_name not in {{t["name"] for t in TOOLS}}:
            return self._error(msg_id, -32602, f"Unknown tool: {{tool_name}}")

        try:
            # TODO: Route to the appropriate specialist method by tool_name.
            request = SpecialistRequest(
                intent=Intent(
                    action=tool_name,
                    domain="general",
                    confidence=1.0,
                    parameters=arguments,
                ),
                query=Query(user_input=query),
                specialist_name=SPECIALIST_NAME,
            )
            response = await self._specialist.execute(request)
            content = [{{"type": "text", "text": json.dumps(response.result, indent=2)}}]
            return self._ok(msg_id, {{"content": content}})
        except Exception as exc:  # noqa: BLE001
            logger.exception("Tool execution failed")
            return self._error(msg_id, -32603, str(exc))

    @staticmethod
    def _ok(msg_id: int | str | None, result: Any) -> dict[str, Any]:
        return {{"jsonrpc": "2.0", "id": msg_id, "result": result}}

    @staticmethod
    def _error(msg_id: int | str | None, code: int, message: str) -> dict[str, Any]:
        return {{"jsonrpc": "2.0", "id": msg_id, "error": {{"code": code, "message": message}}}}


async def main() -> None:
    """Run the MCP server, reading JSON-RPC messages from stdin."""
    logging.basicConfig(level=logging.WARNING, stream=sys.stderr)
    server = MCPServer()
    loop = asyncio.get_event_loop()
    reader = asyncio.StreamReader()
    protocol = asyncio.StreamReaderProtocol(reader)
    await loop.connect_read_pipe(lambda: protocol, sys.stdin)

    writer_transport, writer_protocol = await loop.connect_write_pipe(
        asyncio.BaseProtocol, sys.stdout.buffer
    )
    writer = asyncio.StreamWriter(writer_transport, writer_protocol, reader, loop)

    while True:
        line = await reader.readline()
        if not line:
            break
        try:
            message = json.loads(line.decode())
        except json.JSONDecodeError:
            continue
        response = await server.handle(message)
        if response is not None:
            writer.write((json.dumps(response) + "\\n").encode())
            await writer.drain()


if __name__ == "__main__":
    asyncio.run(main())
'''


def _skill_template(meta: SpecialistMetadata) -> str:
    """Generate an Agent Skill package wrapper."""
    caps_list = ", ".join(f'"{c}"' for c in meta.capabilities)
    short_name = meta.class_name[: -len("Specialist")]
    return f'''\
#!/usr/bin/env python3
"""Agent Skill wrapper for {meta.display_name}.

Auto-generated by generate_outputs.py — edit to taste.

This module exposes the specialist as a reusable Skill that can be registered
with any orchestrator supporting the Agent Skill protocol (e.g. Claude's skill
runner, LangChain agent toolkits, or a custom router).

Usage:
    from {meta.slug}_skill import {short_name}Skill

    skill = {short_name}Skill()
    result = await skill.execute({{"query": "your query here"}})
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

# TODO: Adjust import path to match your project layout.
from {meta.module_path} import {meta.class_name}
from oss_agent_lab.contracts import Intent, Query, SpecialistRequest


@dataclass
class SkillManifest:
    """Declarative metadata describing this skill to an orchestrator."""

    name: str = "{meta.name}"
    display_name: str = "{meta.display_name}"
    description: str = "{meta.description}"
    version: str = "{meta.version}"
    capabilities: list[str] = field(default_factory=lambda: [{caps_list}])
    # TODO: Add parameter schema in JSON Schema format for validation.
    input_schema: dict[str, Any] = field(default_factory=lambda: {{
        "type": "object",
        "properties": {{
            "query": {{"type": "string", "description": "The user query or topic."}},
            "action": {{"type": "string", "description": "The intent action to perform."}},
            "domain": {{"type": "string", "description": "The intent domain."}},
            "parameters": {{"type": "object", "description": "Extra specialist parameters."}},
        }},
        "required": ["query"],
    }})


class {short_name}Skill:
    """{meta.display_name} packaged as a reusable Agent Skill.

    Register this with your orchestrator to expose {meta.name} capabilities
    through a standard skill interface.
    """

    manifest: SkillManifest = SkillManifest()

    def __init__(self) -> None:
        self._specialist = {meta.class_name}()

    async def execute(self, inputs: dict[str, Any]) -> dict[str, Any]:
        """Execute the skill with the given inputs.

        Args:
            inputs: Dict conforming to SkillManifest.input_schema. Must contain
                    at minimum a "query" key.

        Returns:
            Dict containing the specialist result under key "result", plus
            "status" and "specialist_name".
        """
        query: str = inputs["query"]
        action: str = inputs.get("action", "{meta.capabilities[0] if meta.capabilities else "run"}")
        domain: str = inputs.get("domain", "general")
        parameters: dict[str, Any] = inputs.get("parameters", {{}})

        request = SpecialistRequest(
            intent=Intent(action=action, domain=domain, confidence=1.0, parameters=parameters),
            query=Query(user_input=query),
            specialist_name=self.manifest.name,
        )
        response = await self._specialist.execute(request)
        return {{
            "status": response.status,
            "specialist_name": response.specialist_name,
            "result": response.result,
        }}

    def describe(self) -> dict[str, Any]:
        """Return the skill manifest as a plain dict (for registration)."""
        return {{
            "name": self.manifest.name,
            "display_name": self.manifest.display_name,
            "description": self.manifest.description,
            "version": self.manifest.version,
            "capabilities": self.manifest.capabilities,
            "input_schema": self.manifest.input_schema,
        }}
'''


def _rest_template(meta: SpecialistMetadata) -> str:
    """Generate a FastAPI REST wrapper stub."""
    return f'''\
#!/usr/bin/env python3
"""REST API wrapper for {meta.display_name} (FastAPI).

Auto-generated by generate_outputs.py — edit to taste.

Requires:  pip install fastapi uvicorn

Usage:
    uvicorn {meta.slug}_rest:app --host 0.0.0.0 --port 8000 --reload

Endpoints:
    POST /run        — Execute the specialist.
    GET  /health     — Health check.
    GET  /info       — Specialist metadata.
"""
from __future__ import annotations

from typing import Any

# TODO: Install fastapi and uvicorn if not already present.
try:
    from fastapi import FastAPI, HTTPException
    from fastapi.responses import JSONResponse
    from pydantic import BaseModel, Field
except ImportError as exc:
    raise ImportError(
        "fastapi and pydantic are required for the REST wrapper. "
        "Install with: pip install fastapi uvicorn"
    ) from exc

# TODO: Adjust import path to match your project layout.
from {meta.module_path} import {meta.class_name}
from oss_agent_lab.contracts import Intent, Query, SpecialistRequest

app = FastAPI(
    title="{meta.display_name} REST API",
    description="{meta.description}",
    version="{meta.version}",
)

_specialist = {meta.class_name}()


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------


class RunRequest(BaseModel):
    """Payload for POST /run."""

    query: str = Field(..., description="The user query or topic.")
    action: str = Field(
        default="{meta.capabilities[0] if meta.capabilities else "run"}",
        description="Intent action ({", ".join(meta.capabilities)}).",
    )
    domain: str = Field(default="general", description="Intent domain.")
    parameters: dict[str, Any] = Field(
        default_factory=dict, description="Optional specialist parameters."
    )


class RunResponse(BaseModel):
    """Response from POST /run."""

    status: str
    specialist_name: str
    result: dict[str, Any]


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@app.post("/run", response_model=RunResponse, summary="Execute the specialist")
async def run(payload: RunRequest) -> RunResponse:
    """Execute the {meta.display_name} on the given query.

    Returns the specialist response, including the result dict, status,
    and specialist name.
    """
    try:
        request = SpecialistRequest(
            intent=Intent(
                action=payload.action,
                domain=payload.domain,
                confidence=1.0,
                parameters=payload.parameters,
            ),
            query=Query(user_input=payload.query),
            specialist_name="{meta.name}",
        )
        response = await _specialist.execute(request)
        return RunResponse(
            status=response.status,
            specialist_name=response.specialist_name,
            result=response.result,
        )
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.get("/health", summary="Health check")
async def health() -> JSONResponse:
    """Return a simple health payload."""
    return JSONResponse({{"status": "ok", "specialist": "{meta.name}"}})


@app.get("/info", summary="Specialist metadata")
async def info() -> JSONResponse:
    """Return metadata about this specialist."""
    return JSONResponse({{
        "name": "{meta.name}",
        "display_name": "{meta.display_name}",
        "description": "{meta.description}",
        "version": "{meta.version}",
        "source_repo": "{meta.source_repo}",
        "tier": "{meta.tier}",
        "capabilities": {meta.capabilities!r},
        "allowed_tools": {meta.allowed_tools!r},
    }})


# ---------------------------------------------------------------------------
# Entry point (uvicorn auto-discovers `app`)
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
'''


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

_FORMAT_SUBDIRS = {
    "python_api": "python_api",
    "cli": "cli",
    "mcp_server": "mcp",
    "agent_skill": "skills",
    "rest_api": "rest",
}

_FORMAT_SUFFIXES = {
    "python_api": "",
    "cli": "_cli",
    "mcp_server": "_mcp",
    "agent_skill": "_skill",
    "rest_api": "_rest",
}

_FORMAT_GENERATORS = {
    "python_api": _python_api_template,
    "cli": _cli_template,
    "mcp_server": _mcp_template,
    "agent_skill": _skill_template,
    "rest_api": _rest_template,
}


def generate_outputs(
    specialist_dir: Path,
    output_dir: Path | None = None,
) -> dict[str, Path]:
    """Generate all output formats for a specialist.

    Parses SKILL.md frontmatter, then writes one file per output format into
    the appropriate subdirectory of ``output_dir``.

    Args:
        specialist_dir: Path to the specialist directory containing agent.py
                        and SKILL.md.
        output_dir: Root directory for generated files. Defaults to an
                    ``output/`` sibling of the project root inferred from
                    specialist_dir.

    Returns:
        Dict mapping format name (e.g. "python_api") to the generated Path.

    Raises:
        FileNotFoundError: If SKILL.md does not exist in specialist_dir.
        ValueError: If SKILL.md has no valid YAML frontmatter.
    """
    specialist_dir = specialist_dir.resolve()
    skill_md = specialist_dir / "SKILL.md"
    meta = parse_skill_md(skill_md)

    # Resolve output root: default to <project_root>/output
    if output_dir is None:
        # Walk up from specialist_dir looking for pyproject.toml as project root.
        project_root = _find_project_root(specialist_dir) or specialist_dir.parents[2]
        output_dir = project_root / "output"

    generated: dict[str, Path] = {}

    for fmt_key, generator in _FORMAT_GENERATORS.items():
        subdir_name = _FORMAT_SUBDIRS[fmt_key]
        suffix = _FORMAT_SUFFIXES[fmt_key]
        target_dir = output_dir / subdir_name
        target_dir.mkdir(parents=True, exist_ok=True)

        filename = f"{meta.slug}{suffix}.py"
        target_path = target_dir / filename
        content = generator(meta)
        target_path.write_text(content, encoding="utf-8")
        generated[fmt_key] = target_path

    return generated


def _find_project_root(start: Path) -> Path | None:
    """Walk up the directory tree looking for pyproject.toml."""
    current = start
    for _ in range(10):
        if (current / "pyproject.toml").exists():
            return current
        parent = current.parent
        if parent == current:
            break
        current = parent
    return None


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate multi-format output wrappers from a specialist directory.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "specialist_dir",
        type=Path,
        help="Path to specialist directory (must contain SKILL.md and agent.py).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        metavar="DIR",
        help="Root directory for generated files (default: <project_root>/output).",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="Print generated file paths after writing.",
    )
    args = parser.parse_args()

    try:
        generated = generate_outputs(args.specialist_dir, args.output_dir)
    except (FileNotFoundError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)

    for fmt, path in generated.items():
        print(f"{fmt:15s} {path}")


if __name__ == "__main__":
    main()
