"""Host-side MCP server that exposes user-defined experiment tools.

The server loads tools from the user's Python file (and optionally from
predefined MCP server modules), then serves them over streamable HTTP so that
the agent running inside the Docker container can connect to
``http://host.docker.internal:<port>/mcp``.

A companion ``/invoke`` endpoint accepts JSON ``{"tool": "<name>", "args": {...}}``
and returns pickle-serialized results, enabling the Python client generated by
``client_generator.py`` to call tools with native Python objects.

The server runs in a separate process so it does not block the main CLI.
When ``--update-tools`` is active, a built-in ``reload_tools`` MCP tool is
registered so the agent can trigger a reload itself.  The parent process
detects the signal via a ``multiprocessing.Event`` and restarts the server.
"""

from __future__ import annotations

import logging
import multiprocessing
import os
import signal
import sys
from pathlib import Path
from typing import Callable, Optional

from safe_lab_agents.mcp.loader import load_module_exports
from safe_lab_agents.utils import find_free_port
from safe_lab_agents.mcp import tool_utils

logger = logging.getLogger(__name__)


class _BearerAuthMiddleware:
    """Pure-ASGI middleware enforcing a shared ``Authorization: Bearer`` token.

    Implemented as raw ASGI (not Starlette's ``BaseHTTPMiddleware``) so it does
    not buffer responses — buffering would break the streamable-HTTP ``/mcp``
    SSE stream the agent connects over.

    ``GET /health`` is exempt so the host's :func:`wait_for_server` (which has no
    token) can poll liveness.
    """

    def __init__(self, app, token: str) -> None:
        self.app = app
        self._expected = token

    async def __call__(self, scope, receive, send):
        import secrets

        if scope["type"] == "http" and scope.get("path") != "/health":
            header = ""
            for key, value in scope.get("headers", []):
                if key == b"authorization":
                    header = value.decode("latin-1")
                    break
            token = header[7:] if header.startswith("Bearer ") else ""
            if not secrets.compare_digest(token, self._expected):
                await send(
                    {
                        "type": "http.response.start",
                        "status": 401,
                        "headers": [(b"content-type", b"text/plain")],
                    }
                )
                await send({"type": "http.response.body", "body": b"unauthorized"})
                return
        await self.app(scope, receive, send)


class ExperimentMCPServer:
    """Manage the lifecycle of an MCP server exposing experiment tools.

    Args:
        tools_file: Path to the user's Python file containing tool functions.
        port: TCP port to bind to.  ``0`` means auto-select a free port.
        predefined_servers: Optional list of predefined server names whose
            tools should also be registered.
    """

    def __init__(
        self,
        tools_file: Path,
        port: int = 0,
        predefined_servers: Optional[list[str]] = None,
        shared_dir: Optional[Path] = None,
        update_tools: bool = False,
        auth_token: str = "",
    ) -> None:
        # Shared secret the agent and generated clients must present as
        # ``Authorization: Bearer <token>`` on every request.  Mandatory: the
        # server binds all interfaces (LAN-reachable, required so containers can
        # reach it across the Docker/Podman VM gateway), so it must never run
        # unauthenticated.
        if not auth_token:
            raise ValueError(
                "ExperimentMCPServer requires a non-empty auth_token; refusing to "
                "start an instrument-control server without authentication."
            )
        self.tools_file = Path(tools_file).resolve()
        self.port: int = port if port != 0 else find_free_port()
        self.predefined_servers = predefined_servers or []
        self.shared_dir = Path(shared_dir).resolve() if shared_dir is not None else None
        self.auth_token = auth_token
        self._process: Optional[multiprocessing.Process] = None
        # One-way signal queue from the MCP subprocess to the parent monitor
        # thread.  Only created when --update-tools is active so the
        # reload_tools MCP tool is registered only when there is a monitor
        # thread ready to handle it.
        self.reload_queue: Optional[multiprocessing.Queue] = (
            multiprocessing.Queue() if update_tools else None
        )

    def start(self) -> int:
        """Start the MCP server in a background process.

        Returns:
            The TCP port the server is listening on.
        """
        self._process = multiprocessing.Process(
            target=_run_server,
            args=(
                self.tools_file,
                self.port,
                self.predefined_servers,
                self.shared_dir,
                self.reload_queue,
                self.auth_token,
            ),
            daemon=True,
        )
        self._process.start()
        logger.info("MCP server process started (pid=%s) on port %d", self._process.pid, self.port)
        return self.port

    def stop(self) -> None:
        """Terminate the MCP server process.

        Sends ``SIGTERM`` first so the subprocess can run its ``finally`` block —
        which invokes ``GRACEFUL_EXPERIMENT_SHUTDOWN`` against the live experiment
        (see ``_run_server``).  The generous join timeout gives a slow hardware
        ``.close()`` time to finish before we escalate to ``SIGKILL``.
        """
        if self._process is not None and self._process.is_alive():
            logger.info("Stopping MCP server (pid=%s)", self._process.pid)
            self._process.terminate()
            self._process.join(timeout=15)
            if self._process.is_alive():
                self._process.kill()
                self._process.join(timeout=2)
        self._process = None

    def shutdown(self) -> None:
        """Stop the server for final session teardown.

        ``GRACEFUL_EXPERIMENT_SHUTDOWN`` runs inside the subprocess (where the
        experiment object lives), triggered by ``stop()`` terminating it — so this
        is now a thin alias for ``stop()``, kept for call-site clarity.
        """
        self.stop()


def _run_server(
    tools_file: Path,
    port: int,
    predefined_server_names: list[str],
    shared_dir: Optional[Path],
    reload_queue: Optional[multiprocessing.Queue],
    auth_token: str = "",
) -> None:
    """Entry point for the server subprocess.

    Creates a FastMCP instance, registers all tools, and starts serving.
    This function blocks until the process is terminated.
    """
    # This is a spawned subprocess (fresh interpreter under `spawn`), so it starts
    # with no logging config — configure it from the inherited LOG_LEVEL so this
    # process's tool-call / auto-log debug output surfaces alongside the host's.
    from safe_lab_agents.utils import configure_logging

    configure_logging(os.environ.get("LOG_LEVEL"))

    # FastMCP's startup banner is suppressed via show_banner=False (below) and
    # the transport is HTTP, so stdout is free — we deliberately do NOT redirect
    # it to devnull: that leaked the file handle and silently swallowed any
    # print() from the user's tools running here on the host.
    #
    # Ignore SIGINT in the child — the parent handles graceful shutdown.
    signal.signal(signal.SIGINT, signal.SIG_IGN)

    from fastmcp import FastMCP  # imported here so the main process stays lean

    mcp = FastMCP("experiment-tools")

    tool_utils.SHARED_DATA_DIR = str(shared_dir.resolve()) if shared_dir is not None else None

    # ---- Register predefined server tools ----
    predefined_python_tools: list = []
    if predefined_server_names:
        from safe_lab_agents.mcp.predefined import get_predefined_server

        for server_name in predefined_server_names:
            predefined = get_predefined_server(server_name)
            for func in predefined.get_tools():
                mcp.add_tool(func)
            predefined_python_tools.extend(predefined.get_python_tools())
            logger.info("Registered predefined server '%s'", server_name)

    # ---- Build wrapper chain from active env-var-activated features ----
    # auto-log innermost (captures instrument time only); kadi outermost.
    active_wrappers: list = []
    auto_logger = None
    if os.environ.get("AUTO_LOG_DIR"):
        from safe_lab_agents.mcp.predefined.autolog import AutoLogger

        # All auto-log state lives on this instance; its bound methods are the
        # wrapper and the batch/analysis control tools.
        auto_logger = AutoLogger.from_env()
        active_wrappers.append(auto_logger.wrapper)
        predefined_python_tools.extend(
            [auto_logger.start_batch, auto_logger.stop_batch, auto_logger.log_analysis]
        )
    def _apply_wrappers(func: Callable) -> Callable:
        for w in active_wrappers:
            func = w(func)
        return func

    # ---- Load user-defined tools (and the shutdown hook, from one evaluation) ----
    try:
        mcp_tools, python_tools, shutdown_hook = load_module_exports(
            tools_file, shared_dir=shared_dir
        )
    except Exception as exc:
        _print_tool_error("startup", exc)
        sys.exit(1)

    # ---- Register MCP tools ----
    for func in (mcp_tools or []):
        wrapped = _wrap_mcp_tool_errors(_apply_wrappers(func))
        mcp.add_tool(wrapped)
    logger.info("Registered %d MCP tool(s)", len(mcp_tools or []))

    # ---- Register reload_tools (only when --update-tools is active) ----
    if reload_queue is not None:
        def reload_tools() -> str:
            """Reload experiment tools from the tools file.

            The tools file lives on the host and is edited by the user, not by
            you.  Call this only when the user tells you they have updated it —
            never on your own — to pick up the new or changed tools without
            restarting the session.  Both MCP tools (available as
            mcp__experiment-tools__*) and Python tools
            (/agent/workspace/tools_client.py) are reloaded.

            The MCP connection will drop briefly and reconnect — reload your
            MCP tool list after reconnection.  For Python tools, re-import
            tools_client.py from /agent/workspace/tools_client.py.

            Returns the updated Python tools description so the agent knows
            the new signatures immediately, or an error message if the tools
            file contains a syntax error (server is NOT restarted in that case).
            """
            try:
                import ast as _ast
                _ast.parse(Path(tools_file).read_text(encoding="utf-8"))
            except SyntaxError as exc:
                return f"Syntax error in tools file — reload cancelled: {exc}"

            python_tools_section = ""
            try:
                from safe_lab_agents.mcp.loader import load_tools_from_file as _ltff
                from safe_lab_agents.mcp.client_generator import _format_tools_info
                _, py_tools = _ltff(tools_file)
                if py_tools:
                    python_tools_section = "\n\nUpdated Python tools:\n" + _format_tools_info(py_tools)
            except Exception:
                pass

            reload_queue.put("reload")
            return (
                "Tools reload scheduled. The MCP connection will drop and reconnect "
                "shortly. You should search for new MCP tools to see the updated MCP tools. "
                "The Python client at /agent/workspace/tools_client.py will also be "
                f"regenerated; re-import it to use updated Python tools.{python_tools_section}"
            )

        mcp.add_tool(reload_tools)

    # ---- Build Python-callable registry (/invoke endpoint) ----
    _python_registry: dict[str, Callable] = {}
    for f in (python_tools or []):
        _python_registry[f.__name__] = _apply_wrappers(f)
    # The predefined auto-log control tools (start_batch/stop_batch/log_analysis)
    # ARE the logging machinery, so they must NOT go through the auto-log wrapper:
    # doing so would record them as fake experiments and make log_analysis record
    # the act of recording. (User tools opt out individually via @no_autolog.)
    for f in predefined_python_tools:
        _python_registry[f.__name__] = f
    logger.info("Registered %d Python tool(s)", len(_python_registry))

    # ---- Health endpoint ----
    @mcp.custom_route("/health", methods=["GET"])
    async def health(request):
        from starlette.responses import JSONResponse
        return JSONResponse({"status": "ok"})

    # ---- Python-callable invoke endpoint ----
    @mcp.custom_route("/invoke", methods=["POST"])
    async def invoke_tool(request):
        import pickle
        from starlette.responses import JSONResponse, Response
        from safe_lab_agents.mcp.serialization import loads_args, validate_and_coerce_args

        body = loads_args(await request.body())
        func = _python_registry.get(body.get("tool"))
        if func is None:
            return Response(status_code=404)
        try:
            coerced = validate_and_coerce_args(func, body.get("args", {}))
        except TypeError as exc:
            return JSONResponse({"error": str(exc)}, status_code=422)
        try:
            result = func(**coerced)
        except Exception as exc:
            import traceback

            return JSONResponse(
                {
                    "error": f"{type(exc).__name__}: {exc}",
                    "traceback": traceback.format_exc(),
                },
                status_code=500,
            )
        return Response(content=pickle.dumps(result), media_type="application/octet-stream")

    # ---- Start serving ----
    # On SIGTERM (sent by the parent's stop()/shutdown()), uvicorn shuts down
    # gracefully and mcp.run() returns, so the finally block runs
    # GRACEFUL_EXPERIMENT_SHUTDOWN here — in the subprocess where the experiment
    # actually lives — on both --update-tools reload and final shutdown.
    run_kwargs: dict = dict(
        transport="streamable-http",
        host="0.0.0.0",
        port=port,
        log_level="warning",
        uvicorn_config={"access_log": False},
        show_banner=False,
        stateless_http=False,
    )
    # Fail closed: the server binds all interfaces, so it must never serve
    # without the bearer-token check installed.
    if not auth_token:
        raise ValueError("MCP server refusing to start without an auth token.")
    from starlette.middleware import Middleware

    run_kwargs["middleware"] = [Middleware(_BearerAuthMiddleware, token=auth_token)]
    logger.info("MCP server listening on 0.0.0.0:%d (bearer-token auth enabled)", port)
    try:
        mcp.run(**run_kwargs)
    finally:
        # Flush any batch the agent left open. The batch lives in THIS
        # subprocess's memory, so it must be persisted here before we exit —
        # write_session_summary runs later in the host process and only reads
        # files already on disk. Runs on both --update-tools reload and final
        # shutdown (see the run_kwargs comment above).
        if auto_logger is not None:
            try:
                flushed = auto_logger.flush_active_batch()
                if flushed:
                    logger.info("auto-log: flushed unclosed batch at shutdown: %s", flushed)
            except Exception:
                logger.warning(
                    "auto-log: failed to flush active batch at shutdown", exc_info=True
                )
        if shutdown_hook is not None:
            logger.info("Calling GRACEFUL_EXPERIMENT_SHUTDOWN")
            try:
                shutdown_hook()
            except Exception as exc:
                logger.warning("GRACEFUL_EXPERIMENT_SHUTDOWN raised an error: %s", exc)


def _wrap_mcp_tool_errors(func: Callable) -> Callable:
    """Wrap an MCP tool so exceptions reach the agent with full detail.

    FastMCP's default surfaces only ``str(exc)``.  This wrapper re-raises as a
    ``ToolError`` carrying the exception type, message, and traceback, so the
    agent sees what actually went wrong inside the tool instead of an opaque
    error.  ``ToolError`` is passed through unchanged (it is already an
    intentional, agent-facing message).
    """
    import functools
    import traceback

    from fastmcp.exceptions import ToolError

    @functools.wraps(func)
    def inner(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except ToolError:
            raise
        except Exception as exc:
            raise ToolError(
                f"{func.__name__} raised {type(exc).__name__}: {exc}\n\n"
                f"{traceback.format_exc()}"
            ) from exc

    return inner


def _format_tool_error(exc: Exception) -> str:
    """Return a concise, human-readable error string for a tools-file exception."""
    return f"{type(exc).__name__}: {exc}"


def _print_tool_error(phase: str, exc: Exception) -> None:
    """Print a clean error to stderr (avoids multiprocessing's raw traceback)."""
    print(
        f"\n[MCP server] Tools file error during {phase}: {_format_tool_error(exc)}\n",
        file=sys.stderr,
        flush=True,
    )
